Repository Homebrew/brew, pull requests merged in 2018-08, with the labels that each got.

#4569 Use `SystemCommand` for `curl`.
  Library/Homebrew/cask/lib/hbc/download_strategy.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/system_command.rb
  Library/Homebrew/test/cask/download_strategy_spec.rb
  Library/Homebrew/test/cask/pkg_spec.rb
  Library/Homebrew/test/support/helper/cask/fake_system_command.rb
  Library/Homebrew/test/system_command_result_spec.rb
  Library/Homebrew/test/system_command_spec.rb
  Library/Homebrew/test/utils/curl_spec.rb
  Library/Homebrew/utils/curl.rb
  Library/Homebrew/utils/github.rb
Labels: in progress

#4583 Remove unneeded RuboCop comment.
  Library/Homebrew/utils/fork.rb
Labels: in progress

#4589 Show `stdout` for `curl` commands.
  Library/Homebrew/utils/curl.rb
Labels: in progress

#4581 Remove non-existent download strategies.
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/download_strategy.rb
Labels: in progress

#4552 Reorder unpack strategies.
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/unpack_strategy.rb
  Library/Homebrew/unpack_strategy/air.rb
  Library/Homebrew/unpack_strategy/bazaar.rb
  Library/Homebrew/unpack_strategy/bzip2.rb
  Library/Homebrew/unpack_strategy/cab.rb
  Library/Homebrew/unpack_strategy/compress.rb
  Library/Homebrew/unpack_strategy/cvs.rb
  Library/Homebrew/unpack_strategy/directory.rb
  Library/Homebrew/unpack_strategy/dmg.rb
  Library/Homebrew/unpack_strategy/executable.rb
  Library/Homebrew/unpack_strategy/fossil.rb
  Library/Homebrew/unpack_strategy/generic_unar.rb
  Library/Homebrew/unpack_strategy/git.rb
  Library/Homebrew/unpack_strategy/gzip.rb
  Library/Homebrew/unpack_strategy/jar.rb
  Library/Homebrew/unpack_strategy/lha.rb
  Library/Homebrew/unpack_strategy/lua_rock.rb
  Library/Homebrew/unpack_strategy/lzip.rb
  Library/Homebrew/unpack_strategy/lzma.rb
  Library/Homebrew/unpack_strategy/mercurial.rb
  Library/Homebrew/unpack_strategy/microsoft_office_xml.rb
  Library/Homebrew/unpack_strategy/otf.rb
  Library/Homebrew/unpack_strategy/p7zip.rb
  Library/Homebrew/unpack_strategy/pkg.rb
  Library/Homebrew/unpack_strategy/rar.rb
  Library/Homebrew/unpack_strategy/self_extracting_executable.rb
  Library/Homebrew/unpack_strategy/sit.rb
  Library/Homebrew/unpack_strategy/subversion.rb
  Library/Homebrew/unpack_strategy/tar.rb
  Library/Homebrew/unpack_strategy/ttf.rb
  Library/Homebrew/unpack_strategy/uncompressed.rb
  Library/Homebrew/unpack_strategy/xar.rb
  Library/Homebrew/unpack_strategy/xz.rb
  Library/Homebrew/unpack_strategy/zip.rb
Labels: in progress

#4587 Use `ditto` instead of `unzip`.
  Library/Homebrew/extend/os/mac/unpack_strategy/zip.rb
  Library/Homebrew/unpack_strategy/zip.rb
Labels: in progress

#4585 Refactor download strategies.
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/resource.rb
  Library/Homebrew/test/download_strategies_spec.rb
Labels: in progress

#4586 Fix `ErrorDuringExecution` initialization.
  Library/Homebrew/utils/popen.rb
Labels: in progress

#4591 Add the SFC PLC to the README and manpage.
  Library/Homebrew/dev-cmd/man.rb
  Library/Homebrew/manpages/brew.1.md.erb
  README.md
  docs/Manpage.md
  manpages/brew-cask.1
  manpages/brew.1
Labels: in progress

#4592 Refactor download strategies.
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/resource.rb
  Library/Homebrew/test/download_strategies_spec.rb
Labels: in progress

#4593 Merge `curl` options used by casks into download strategies.
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/test/download_strategies_spec.rb
Labels: in progress

#4543 Pass `verbose` to unpack strategies.
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/system_command.rb
  Library/Homebrew/unpack_strategy/air.rb
  Library/Homebrew/unpack_strategy/bzip2.rb
  Library/Homebrew/unpack_strategy/cab.rb
  Library/Homebrew/unpack_strategy/dmg.rb
  Library/Homebrew/unpack_strategy/fossil.rb
  Library/Homebrew/unpack_strategy/generic_unar.rb
  Library/Homebrew/unpack_strategy/gzip.rb
  Library/Homebrew/unpack_strategy/lha.rb
  Library/Homebrew/unpack_strategy/lzip.rb
  Library/Homebrew/unpack_strategy/lzma.rb
  Library/Homebrew/unpack_strategy/mercurial.rb
  Library/Homebrew/unpack_strategy/p7zip.rb
  Library/Homebrew/unpack_strategy/rar.rb
  Library/Homebrew/unpack_strategy/subversion.rb
  Library/Homebrew/unpack_strategy/tar.rb
  Library/Homebrew/unpack_strategy/xar.rb
  Library/Homebrew/unpack_strategy/xz.rb
  Library/Homebrew/unpack_strategy/zip.rb
Labels: in progress

#4596 Use `system_command` for `GitDownloadStrategy`.
  Library/Homebrew/download_strategy.rb
Labels: in progress

#4598 Move `temporary_path` to `AbstractFileDownloadStrategy`.
  Library/Homebrew/download_strategy.rb
Labels: in progress

#4597 Change docs to use symbols instead of class names.
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/manpages/brew.1.md.erb
  docs/Manpage.md
Labels: in progress

#4599 Allow specifying cache directory for download strategies.
  Library/Homebrew/download_strategy.rb
Labels: in progress

#4606 docs/New-Maintainer-Checklist: update best practises.
  docs/New-Maintainer-Checklist.md
Labels: in progress

#4601 Use `--` to separate download name and version.
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/test/cmd/fetch_spec.rb
  Library/Homebrew/test/cmd/update-report/reporter_spec.rb
  Library/Homebrew/test/cmd/update-report_spec.rb
  Library/Homebrew/test/download_strategies_spec.rb
Labels: in progress

#4608 Merge download strategy specs.
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/test/download_strategies_spec.rb
Labels: in progress

#4610 Fix `update-report` migration.
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/test/cmd/update-report_spec.rb
Labels: in progress

#4603 Use `system_command` for all download strategies.
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/test/download_strategies_spec.rb
Labels: in progress

#4614 Fix cleanup for files with `--`.
  Library/Homebrew/cleanup.rb
  Library/Homebrew/test/cleanup_spec.rb
Labels: in progress

#4613 Change migration to loop through formulae.
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/test/cmd/update-report_spec.rb
Labels: in progress

#4612 Use `--` for bottles.
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/test/bottle_filename_spec.rb
  Library/Homebrew/test/dev-cmd/bottle_spec.rb
Labels: in progress

#4607 Use normal download strategies for casks.
  Library/Homebrew/cask/lib/hbc/download.rb
  Library/Homebrew/cask/lib/hbc/url.rb
  Library/Homebrew/test/cask/cli/fetch_spec.rb
Labels: in progress

#4617 Remove unused `brew cask _audit_modified_casks` command.
  Library/Homebrew/cask/lib/hbc/cli.rb
  Library/Homebrew/cask/lib/hbc/cli/internal_audit_modified_casks.rb
Labels: in progress

#4616 Remove cask download strategies.
  Library/Homebrew/cask/lib/hbc.rb
  Library/Homebrew/cask/lib/hbc/auditor.rb
  Library/Homebrew/cask/lib/hbc/cli/fetch.rb
  Library/Homebrew/cask/lib/hbc/download_strategy.rb
  Library/Homebrew/cask/lib/hbc/installer.rb
  Library/Homebrew/test/cask/download_strategy_spec.rb
Labels: in progress

#4627 Add new maintainers
  Library/Homebrew/dev-cmd/man.rb
  Library/Homebrew/manpages/brew.1.md.erb
  README.md
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4619 Use `https://` URLs.
  Library/Homebrew/test/cask/cask_loader/from_uri_loader_spec.rb
  Library/Homebrew/test/rubocops/caveats_cop_spec.rb
  Library/Homebrew/test/rubocops/checksum_cop_spec.rb
  Library/Homebrew/test/rubocops/class_cop_spec.rb
  Library/Homebrew/test/rubocops/components_order_cop_spec.rb
  Library/Homebrew/test/rubocops/components_redundancy_cop_spec.rb
  Library/Homebrew/test/rubocops/conflicts_cop_spec.rb
  Library/Homebrew/test/rubocops/dependency_order_cop_spec.rb
  Library/Homebrew/test/rubocops/formula_desc_cop_spec.rb
  Library/Homebrew/test/rubocops/homepage_cop_spec.rb
  Library/Homebrew/test/rubocops/lines_cop_spec.rb
  Library/Homebrew/test/rubocops/options_cop_spec.rb
  Library/Homebrew/test/rubocops/patches_cop_spec.rb
  Library/Homebrew/test/rubocops/text_cop_spec.rb
  Library/Homebrew/test/utils/svn_spec.rb
Labels: in progress

#4621 Only use `ditto` to extract skipped volumes.
  Library/Homebrew/extend/os/mac/unpack_strategy/zip.rb
  Library/Homebrew/unpack_strategy/zip.rb
Labels: in progress

#4628 Unset `HOMEBREW_DISABLE_LOAD_FORMULA` for migration.
  Library/Homebrew/cmd/update-report.rb
Labels: in progress

#4631 Remove trivial method.
  Library/Homebrew/software_spec.rb
Labels: in progress

#4632 Output message when migrating cache entries.
  Library/Homebrew/cmd/update-report.rb
Labels: in progress

#4633 Refactor `Cleanup`.
  Library/Homebrew/cask/lib/hbc/cli/cleanup.rb
  Library/Homebrew/cleanup.rb
  Library/Homebrew/test/cleanup_spec.rb
Labels: in progress

#4634 Add/remove more maintainers.
  Library/Homebrew/dev-cmd/man.rb
  Library/Homebrew/manpages/brew.1.md.erb
  README.md
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4630 Remove environment variables used by `hub`.
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
  bin/brew
Labels: in progress

#4635 Use option parser for `brew cleanup`.
  Library/Homebrew/cleanup.rb
  Library/Homebrew/cmd/cleanup.rb
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/test/cleanup_spec.rb
Labels: in progress

#4335 Mojave: use the CLT SDK where necessary
  Library/Homebrew/extend/os/mac/diagnostic.rb
  Library/Homebrew/extend/os/mac/extend/ENV/std.rb
  Library/Homebrew/extend/os/mac/extend/ENV/super.rb
  Library/Homebrew/os/mac.rb
  Library/Homebrew/os/mac/sdk.rb
  Library/Homebrew/os/mac/xcode.rb
  Library/Homebrew/test/os/mac/diagnostic_spec.rb
  Library/Homebrew/test/os/mac_spec.rb
Labels: discussion, do not merge, in progress

#4638 Remove executable bit from `ruby.rb` and `prof.rb`.
  Library/Homebrew/dev-cmd/prof.rb
  Library/Homebrew/dev-cmd/ruby.rb
Labels: in progress

#4637 Fix Bottle::Filename.new for taps
  Library/Homebrew/software_spec.rb
  Library/Homebrew/test/bottle_filename_spec.rb
Labels: in progress

#4642 Mac.sdk_path_if_needed tests: stub SDK check
  Library/Homebrew/test/os/mac_spec.rb
Labels: in progress

#4622 formula_installer: avoid cyclic dependency on Linux
  Library/Homebrew/formula_installer.rb
Labels: in progress

#4639 Add cask cleanup and per-formula cache cleanup.
  Library/Homebrew/cask/lib/hbc/cask_loader.rb
  Library/Homebrew/cleanup.rb
Labels: in progress

#4647 Per cask/formula `.DS_Store` cleanup
  Library/Homebrew/cleanup.rb
  Library/Homebrew/lock_file.rb
Labels: in progress

#4659 Always fetch at least the latest tag.
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/update-reset.sh
  Library/Homebrew/cmd/update.sh
Labels: in progress

#4663 audit: flag redundant shell_output() exit codes
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4651 Fix `brew cleanup`.
  Library/Homebrew/cleanup.rb
  Library/Homebrew/extend/pathname.rb
  Library/Homebrew/test/cleanup_spec.rb
  Library/Homebrew/test/pathname_spec.rb
  Library/Homebrew/test/version_spec.rb
Labels: in progress

#4667 Only clean up external patches.
  Library/Homebrew/cleanup.rb
Labels: in progress

#4623 cask audit: GitHub `latest` casks shouldn't have an appcast
  Library/Homebrew/cask/lib/hbc/audit.rb
Labels: cask, in progress

#4645 Deprecate `brew cask cleanup`.
  Library/Homebrew/cask/lib/hbc/artifact/abstract_artifact.rb
  Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb
  Library/Homebrew/cask/lib/hbc/cache.rb
  Library/Homebrew/cask/lib/hbc/cli.rb
  Library/Homebrew/cask/lib/hbc/cli/cleanup.rb
  Library/Homebrew/cask/lib/hbc/cli/doctor.rb
  Library/Homebrew/cmd/cleanup.rb
  Library/Homebrew/compat/hbc.rb
  Library/Homebrew/compat/hbc/cli/cleanup.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/manpages/brew-cask.1.md
  Library/Homebrew/test/cask/cli/cleanup_spec.rb
  Library/Homebrew/test/cleanup_spec.rb
  Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb
  completions/bash/brew
  completions/zsh/_brew_cask
  docs/Manpage.md
  manpages/brew-cask.1
  manpages/brew.1
Labels: in progress

#4670 Disable `brew cask search` the same time as `brew cask cleanup`.
  Library/Homebrew/compat/hbc/cli/search.rb
Labels: in progress

#4671 test/unpack_strategy: Handle svn unzip unavailable
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/test/unpack_strategy/jar_spec.rb
  Library/Homebrew/test/unpack_strategy/subversion_spec.rb
  Library/Homebrew/test/unpack_strategy/zip_spec.rb
Labels: in progress

#4679 Warn if os/linux is loaded on generic OS
  Library/Homebrew/os/linux.rb
Labels: in progress

#4682 update-report: solicit donations.
  Library/Homebrew/cmd/update-report.rb
Labels: in progress

#4687 test/ENV: Fix prepend_path for Linuxbrew
  Library/Homebrew/test/ENV_spec.rb
Labels: in progress

#4686 X11Requirement: Recent X11 client is sufficient
  Library/Homebrew/requirements/x11_requirement.rb
Labels: in progress

#4685 check_non_libraries: *.so.* is a valid library
  Library/Homebrew/extend/os/formula_cellar_checks.rb
  Library/Homebrew/extend/os/linux/formula_cellar_checks.rb
  Library/Homebrew/formula_cellar_checks.rb
Labels: in progress

#4691 Refactor `odeprecated`.
  Library/Homebrew/brew.rb
  Library/Homebrew/cask/lib/hbc/cli.rb
  Library/Homebrew/test/utils_spec.rb
  Library/Homebrew/utils.rb
Labels: in progress

#4676 10x/Mojave: update dev tool expected versions
  Library/Homebrew/os/mac/pkgconfig/10.14/sqlite3.pc
  Library/Homebrew/os/mac/xcode.rb
Labels: in progress

#4695 KegOnlyReason: Reasons related to macOS valid only on macOS
  Library/Homebrew/extend/os/formula_support.rb
  Library/Homebrew/extend/os/mac/formula_support.rb
  Library/Homebrew/formula_support.rb
Labels: in progress

#4692 utils/github: Exception handling
  Library/Homebrew/utils/github.rb
Labels: in progress

#4696 BottleSpecification: Do not skip bottle relocation on Linux
  Library/Homebrew/extend/os/linux/software_spec.rb
  Library/Homebrew/extend/os/software_spec.rb
  Library/Homebrew/software_spec.rb
Labels: in progress

#4701 README: add jonchang.
  README.md
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4703 manpage: add `brew bundle check --verbose`
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4700 Hide lockfiles being cleaned up.
  Library/Homebrew/cleanup.rb
Labels: in progress

#4698 audit: fixes for test checks
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/rubocops/class_cop.rb
  Library/Homebrew/test/rubocops/class_cop_spec.rb
Labels: in progress

#4710 audit: don't error when test block is missing
  Library/Homebrew/rubocops/class_cop.rb
Labels: in progress

#4717 Use JSON to marshal errors from children
  Library/Homebrew/build.rb
  Library/Homebrew/dev-cmd/test.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/postinstall.rb
  Library/Homebrew/test.rb
  Library/Homebrew/utils/fork.rb
Labels: in progress

#4723 Revert "Use JSON to marshal errors from children"
  Library/Homebrew/build.rb
  Library/Homebrew/dev-cmd/test.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/postinstall.rb
  Library/Homebrew/test.rb
  Library/Homebrew/utils/fork.rb
Labels: in progress

#4620 Add analytics to cask installs
  Library/Homebrew/cask/lib/hbc/installer.rb
  Library/Homebrew/cmd/update-report.rb
  docs/Analytics.md
Labels: cask, in progress

#4716 brew.sh: Allow developers to specify curl/git paths
  Library/Homebrew/brew.sh
Labels: features, in progress

#4678 OS::Mac.mdfind: No need to guard on OS.mac?
  Library/Homebrew/os/mac.rb
Labels: in progress

#4727 conflicts_cop: remove `node@` from whitelist
  Library/Homebrew/rubocops/conflicts_cop.rb
Labels: in progress

#4731 Use `cp` instead of `FileUtils.copy_entry`.
  Library/Homebrew/unpack_strategy/directory.rb
Labels: in progress

#4728 Ignore unparsable system languages.
  Library/Homebrew/cask/lib/hbc/dsl.rb
Labels: in progress

#4735 `.tar.lz` ≠ `.tar.lzma`
  Library/Homebrew/unpack_strategy/tar.rb
Labels: in progress

#4747 manpage: update from latest homebrew-bundle docs.
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4742 audit: remove "`bottle` is not defined"
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4754 extract: update docs
  docs/Versions.md
Labels: in progress

#4762 Check version conflicts using linkage.
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/linkage_checker.rb
Labels: in progress

#4764 audit: Add null check on style results
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4766 Don’t use `CLI::Cleanup` in `Auditor`.
  Library/Homebrew/cask/lib/hbc/auditor.rb
Labels: in progress

#4765 audit: Use `to_i`during assignment to prevent NPE
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4770 style: Fix npe and add test for corrected offense results
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/style.rb
  Library/Homebrew/test/cmd/style_spec.rb
Labels: in progress

#4776 Fix executable with spaces.
  Library/Homebrew/system_command.rb
  Library/Homebrew/test/system_command_spec.rb
Labels: in progress

#4771 Add `$LOAD_PATH` for RuboCop cops.
  Library/Homebrew/rubocops.rb
  Library/Homebrew/rubocops/caveats_cop.rb
  Library/Homebrew/rubocops/checksum_cop.rb
  Library/Homebrew/rubocops/class_cop.rb
  Library/Homebrew/rubocops/components_order_cop.rb
  Library/Homebrew/rubocops/components_redundancy_cop.rb
  Library/Homebrew/rubocops/conflicts_cop.rb
  Library/Homebrew/rubocops/dependency_order_cop.rb
  Library/Homebrew/rubocops/extend/formula_cop.rb
  Library/Homebrew/rubocops/formula_desc_cop.rb
  Library/Homebrew/rubocops/homepage_cop.rb
  Library/Homebrew/rubocops/lines_cop.rb
  Library/Homebrew/rubocops/options_cop.rb
  Library/Homebrew/rubocops/patches_cop.rb
  Library/Homebrew/rubocops/text_cop.rb
  Library/Homebrew/rubocops/urls_cop.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/rubocops/caveats_cop_spec.rb
  Library/Homebrew/test/rubocops/checksum_cop_spec.rb
  Library/Homebrew/test/rubocops/class_cop_spec.rb
  Library/Homebrew/test/rubocops/components_order_cop_spec.rb
  Library/Homebrew/test/rubocops/components_redundancy_cop_spec.rb
  Library/Homebrew/test/rubocops/conflicts_cop_spec.rb
  Library/Homebrew/test/rubocops/dependency_order_cop_spec.rb
  Library/Homebrew/test/rubocops/formula_desc_cop_spec.rb
  Library/Homebrew/test/rubocops/homepage_cop_spec.rb
  Library/Homebrew/test/rubocops/lines_cop_spec.rb
  Library/Homebrew/test/rubocops/options_cop_spec.rb
  Library/Homebrew/test/rubocops/patches_cop_spec.rb
  Library/Homebrew/test/rubocops/text_cop_spec.rb
  Library/Homebrew/test/rubocops/urls_cop_spec.rb
Labels: in progress

#4775 text_cop: update `cargo build` cop
  Library/Homebrew/rubocops/text_cop.rb
  Library/Homebrew/test/rubocops/text_cop_spec.rb
Labels: in progress

#4774 go: support & use aggressive caching
  Library/Homebrew/cleanup.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/test/cleanup_spec.rb
Labels: in progress

#4759 docs/Maintainer-Guidelines: add lead maintainer guidelines.
  docs/Maintainer-Guidelines.md
Labels: in progress

#4773 superenv: Use 02 optimization flag for Linux builds
  Library/Homebrew/extend/os/linux/extend/ENV/super.rb
Labels: in progress
