Repository Homebrew/brew, pull requests merged in 2018-10, with the labels that each got.

#4991 rubocop: move requirement to configuration file
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/.rubocop_todo.yml
  Library/Homebrew/style.rb
  Library/Homebrew/test/.rubocop.yml
  Library/Homebrew/test/.rubocop_todo.yml
Labels: in progress

#5014 xcode: fix expected Clang version for CLT with Xcode 10 (10A255)
  Library/Homebrew/os/mac/xcode.rb
Labels: in progress

#5017 DevelopmentTools::locate: Prefer brewed tools [Linux]
  Library/Homebrew/extend/os/linux/development_tools.rb
Labels: in progress

#5019 Force `chmod_R` after extracting.
  Library/Homebrew/unpack_strategy.rb
Labels: in progress

#5008 Fix `brew mirror`.
  Library/Homebrew/dev-cmd/mirror.rb
  Library/Homebrew/formula.rb
Labels: in progress

#5009 Fix `atomic_write` inside non-sticky directory.
  Library/Homebrew/extend/pathname.rb
Labels: in progress

#5010 Skip quitting applications when not logged into GUI.
  Library/Homebrew/cask/artifact/abstract_uninstall.rb
  Library/Homebrew/cask/artifact/pkg.rb
  Library/Homebrew/cask/caskroom.rb
  Library/Homebrew/cask/staged.rb
  Library/Homebrew/cask/utils.rb
  Library/Homebrew/system_command.rb
  Library/Homebrew/test/cask/artifact/app_spec.rb
  Library/Homebrew/test/support/helper/spec/shared_examples/cask_staged.rb
  Library/Homebrew/test/utils/user_spec.rb
  Library/Homebrew/utils/user.rb
Labels: in progress

#5023 keg_relocate: Fix Error: wrong number of arguments [Linux]
  Library/Homebrew/extend/os/linux/keg_relocate.rb
Labels: bug, in progress

#4383 cli_parser: man-pages and help text generation using Homebrew::CLI::Parser
  Library/Homebrew/cli_parser.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
  Library/Homebrew/dev-cmd/create.rb
  Library/Homebrew/dev-cmd/edit.rb
  Library/Homebrew/dev-cmd/extract.rb
  Library/Homebrew/dev-cmd/formula.rb
  Library/Homebrew/dev-cmd/irb.rb
  Library/Homebrew/dev-cmd/linkage.rb
  Library/Homebrew/dev-cmd/man.rb
  Library/Homebrew/dev-cmd/mirror.rb
  Library/Homebrew/dev-cmd/prof.rb
  Library/Homebrew/dev-cmd/pull.rb
  Library/Homebrew/dev-cmd/release-notes.rb
  Library/Homebrew/dev-cmd/tap-new.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/dev-cmd/update-test.rb
  Library/Homebrew/help.rb
  Library/Homebrew/manpages/brew.1.md.erb
  Library/Homebrew/test/cmd/help_spec.rb
  Library/Homebrew/utils/formatter.rb
  docs/Manpage.md
  manpages/brew-cask.1
  manpages/brew.1
Labels: in progress

#5012 -march=native is default. Hardware::CPU: Add Skylake [Linux]
  Library/Homebrew/compilers.rb
  Library/Homebrew/extend/ENV/std.rb
  Library/Homebrew/extend/ENV/super.rb
  Library/Homebrew/extend/os/linux/hardware/cpu.rb
  Library/Homebrew/hardware.rb
Labels: in progress

#5024 CoreTap.default_remote: Use Linuxbrew/core [Linux]
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/extend/os/linux/tap.rb
  Library/Homebrew/extend/os/tap.rb
  Library/Homebrew/tap.rb
Labels: in progress

#5018 relocation_formulae: Poured bottles depend on gcc [Linux]
  .travis.yml
  Library/Homebrew/extend/os/linux/keg_relocate.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/keg_relocate.rb
  Library/Homebrew/test/formula_installer_bottle_spec.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: in progress

#5168 audit: check for `bottle do` blocks in new formulae
  Library/Homebrew/dev-cmd/audit.rb
Labels: do not merge
