Repository Homebrew/brew, pull requests merged in 2018-09, with the labels that each got.

#4662 Resolve URL to get real file extension.
  Library/Homebrew/brew.rb
  Library/Homebrew/cask/lib/hbc/download.rb
  Library/Homebrew/cleanup.rb
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/extend/pathname.rb
  Library/Homebrew/test/cask/cli/reinstall_spec.rb
  Library/Homebrew/test/cmd/--cache_spec.rb
  Library/Homebrew/test/cmd/fetch_spec.rb
  Library/Homebrew/test/cmd/update-report_spec.rb
  Library/Homebrew/test/download_strategies_spec.rb
  Library/Homebrew/test/update_migrator_spec.rb
  Library/Homebrew/update_migrator.rb
  Library/Homebrew/utils.rb
Labels: in progress

#4785 Skip `mtime` for non-existent symlink.
  Library/Homebrew/cleanup.rb
Labels: in progress

#4788 Skip migration if cache is empty or doesn’t exist.
  Library/Homebrew/update_migrator.rb
Labels: in progress

#4789 Avoid network call in `#initialize`.
  Library/Homebrew/download_strategy.rb
Labels: in progress

#4791 Fix `CurlApacheMirrorDownloadStrategy` URL resolution.
  Library/Homebrew/download_strategy.rb
Labels: in progress

#4778 cleanup: fix go_cache cleanup
  Library/Homebrew/cleanup.rb
Labels: in progress

#4794 tests: set HOME.
  Library/Homebrew/dev-cmd/tests.rb
Labels: in progress

#4784 Improve Homebrew/brew line length.
  Library/.rubocop.yml
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/build_options.rb
  Library/Homebrew/cask/lib/hbc/artifact/abstract_artifact.rb
  Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb
  Library/Homebrew/cask/lib/hbc/artifact/installer.rb
  Library/Homebrew/cask/lib/hbc/artifact/moved.rb
  Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb
  Library/Homebrew/cask/lib/hbc/audit.rb
  Library/Homebrew/cask/lib/hbc/cli/doctor.rb
  Library/Homebrew/cask/lib/hbc/dsl.rb
  Library/Homebrew/cask/lib/hbc/installer.rb
  Library/Homebrew/cask/lib/hbc/pkg.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
  Library/Homebrew/dev-cmd/create.rb
  Library/Homebrew/dev-cmd/man.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/extend/os/mac/system_config.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/global.rb
  Library/Homebrew/keg.rb
  Library/Homebrew/language/python_virtualenv_constants.rb
  Library/Homebrew/missing_formula.rb
  Library/Homebrew/os/mac/xcode.rb
  Library/Homebrew/requirements/x11_requirement.rb
  Library/Homebrew/rubocops/class_cop.rb
  Library/Homebrew/rubocops/components_order_cop.rb
  Library/Homebrew/rubocops/dependency_order_cop.rb
  Library/Homebrew/rubocops/homepage_cop.rb
  Library/Homebrew/rubocops/lines_cop.rb
  Library/Homebrew/rubocops/patches_cop.rb
  Library/Homebrew/style.rb
  Library/Homebrew/test/cask/accessibility_spec.rb
  Library/Homebrew/test/cask/artifact/app_spec.rb
  Library/Homebrew/test/cask/artifact/pkg_spec.rb
  Library/Homebrew/test/cask/cask_spec.rb
  Library/Homebrew/test/cask/cli/install_spec.rb
  Library/Homebrew/test/cask/cli/style_spec.rb
  Library/Homebrew/test/cask/cli/uninstall_spec.rb
  Library/Homebrew/test/cask/cli/zap_spec.rb
  Library/Homebrew/test/cask/depends_on_spec.rb
  Library/Homebrew/test/cask/installer_spec.rb
  Library/Homebrew/test/cask/pkg_spec.rb
  Library/Homebrew/test/download_strategies_spec.rb
  Library/Homebrew/test/rubocops/urls_cop_spec.rb
  Library/Homebrew/test/system_command_spec.rb
  Library/Homebrew/test/tab_spec.rb
  Library/Homebrew/test/tap_spec.rb
  Library/Homebrew/test/update_migrator_spec.rb
  Library/Homebrew/test/utils_spec.rb
  Library/Homebrew/test/version_spec.rb
  Library/Homebrew/unpack_strategy/dmg.rb
  Library/Homebrew/unpack_strategy/generic_unar.rb
  Library/Homebrew/utils/github.rb
Labels: in progress

#4795 tests: handle file leaks and SVN test prompt.
  .gitignore
  Library/Homebrew/test/utils/svn_spec.rb
  Library/Homebrew/utils/svn.rb
Labels: in progress

#4798 Revert "Add `$LOAD_PATH` for RuboCop cops."
  Library/Homebrew/rubocops.rb
  Library/Homebrew/rubocops/caveats_cop.rb
  Library/Homebrew/rubocops/checksum_cop.rb
  Library/Homebrew/rubocops/class_cop.rb
  Library/Homebrew/rubocops/components_order_cop.rb
  Library/Homebrew/rubocops/components_redundancy_cop.rb
  Library/Homebrew/rubocops/conflicts_cop.rb
  Library/Homebrew/rubocops/dependency_order_cop.rb
  Library/Homebrew/rubocops/extend/formula_cop.rb
  Library/Homebrew/rubocops/formula_desc_cop.rb
  Library/Homebrew/rubocops/homepage_cop.rb
  Library/Homebrew/rubocops/lines_cop.rb
  Library/Homebrew/rubocops/options_cop.rb
  Library/Homebrew/rubocops/patches_cop.rb
  Library/Homebrew/rubocops/text_cop.rb
  Library/Homebrew/rubocops/urls_cop.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/rubocops/caveats_cop_spec.rb
  Library/Homebrew/test/rubocops/checksum_cop_spec.rb
  Library/Homebrew/test/rubocops/class_cop_spec.rb
  Library/Homebrew/test/rubocops/components_order_cop_spec.rb
  Library/Homebrew/test/rubocops/components_redundancy_cop_spec.rb
  Library/Homebrew/test/rubocops/conflicts_cop_spec.rb
  Library/Homebrew/test/rubocops/dependency_order_cop_spec.rb
  Library/Homebrew/test/rubocops/formula_desc_cop_spec.rb
  Library/Homebrew/test/rubocops/homepage_cop_spec.rb
  Library/Homebrew/test/rubocops/lines_cop_spec.rb
  Library/Homebrew/test/rubocops/options_cop_spec.rb
  Library/Homebrew/test/rubocops/patches_cop_spec.rb
  Library/Homebrew/test/rubocops/text_cop_spec.rb
  Library/Homebrew/test/rubocops/urls_cop_spec.rb
Labels: in progress

#4797 .rubocop: tweak rules.
  Library/.rubocop.yml
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/build.rb
  Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb
  Library/Homebrew/cask/lib/hbc/audit.rb
  Library/Homebrew/cask/lib/hbc/cli.rb
  Library/Homebrew/cask/lib/hbc/cli/doctor.rb
  Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb
  Library/Homebrew/cask/lib/hbc/download.rb
  Library/Homebrew/cask/lib/hbc/dsl.rb
  Library/Homebrew/cask/lib/hbc/dsl/depends_on.rb
  Library/Homebrew/cask/lib/hbc/installer.rb
  Library/Homebrew/cask/lib/hbc/metadata.rb
  Library/Homebrew/cask/lib/hbc/staged.rb
  Library/Homebrew/cask/lib/hbc/utils.rb
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/cmd/outdated.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/debrew.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/linkage.rb
  Library/Homebrew/dev-cmd/pull.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/extend/ARGV.rb
  Library/Homebrew/extend/os/mac/requirements/java_requirement.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/keg.rb
  Library/Homebrew/locale.rb
  Library/Homebrew/migrator.rb
  Library/Homebrew/os/mac/architecture_list.rb
  Library/Homebrew/requirements/java_requirement.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/rubocops/patches_cop_spec.rb
  Library/Homebrew/unpack_strategy.rb
  Library/Homebrew/unpack_strategy/dmg.rb
  Library/Homebrew/utils.rb
  Library/Homebrew/utils/inreplace.rb
Labels: in progress

#4752 Use JSON to marshal errors from children
  Library/Homebrew/build.rb
  Library/Homebrew/dev-cmd/test.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/global.rb
  Library/Homebrew/postinstall.rb
  Library/Homebrew/test.rb
  Library/Homebrew/test/formula_installer_spec.rb
  Library/Homebrew/test/support/fixtures/failball.rb
  Library/Homebrew/test/support/lib/config.rb
  Library/Homebrew/test/utils/fork_spec.rb
  Library/Homebrew/utils/fork.rb
Labels: in progress

#4808 Remove some `#popen_read`s.
  Library/Homebrew/extend/os/mac/system_config.rb
  Library/Homebrew/readall.rb
  Library/Homebrew/requirements/java_requirement.rb
  Library/Homebrew/system_command.rb
  Library/Homebrew/system_config.rb
  Library/Homebrew/test/cask/pkg_spec.rb
  Library/Homebrew/test/java_requirement_spec.rb
  Library/Homebrew/test/support/helper/cask/fake_system_command.rb
  Library/Homebrew/test/system_command_result_spec.rb
Labels: in progress

#4810 super/cc: fix -mmacosx-version-min on Mojave.
  Library/Homebrew/shims/super/cc
Labels: in progress

#4816 Revert "Use JSON to marshal errors from children"
  Library/Homebrew/build.rb
  Library/Homebrew/dev-cmd/test.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/global.rb
  Library/Homebrew/postinstall.rb
  Library/Homebrew/test.rb
  Library/Homebrew/test/formula_installer_spec.rb
  Library/Homebrew/test/support/fixtures/failball.rb
  Library/Homebrew/test/support/lib/config.rb
  Library/Homebrew/test/utils/fork_spec.rb
  Library/Homebrew/utils/fork.rb
Labels: in progress

#4817 docs/Formula-Cookbook: preach what we practise
  docs/Formula-Cookbook.md
Labels: documentation

#4821 Fix detecting `P7Zip` from symbol.
  Library/Homebrew/unpack_strategy.rb
Labels: in progress

#4822 Fix `downloads` directory not being created.
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/utils/curl.rb
Labels: in progress

#4823 Refactor `Hbc::Verify`.
  Library/Homebrew/cask/verify.rb
  Library/Homebrew/cask/verify/checksum.rb
  Library/Homebrew/test/cask/verify/checksum_spec.rb
  Library/Homebrew/test/cask/verify_spec.rb
Labels: in progress

#4819 utils: Use JSON to marshal child errors
  Library/Homebrew/build.rb
  Library/Homebrew/dev-cmd/test.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/global.rb
  Library/Homebrew/postinstall.rb
  Library/Homebrew/test.rb
  Library/Homebrew/test/formula_installer_spec.rb
  Library/Homebrew/test/support/fixtures/failball.rb
  Library/Homebrew/test/support/lib/config.rb
  Library/Homebrew/test/utils/fork_spec.rb
  Library/Homebrew/utils/fork.rb
Labels: in progress

#4824 Change regex to match `filename` if header also contains `filename*`.
  Library/Homebrew/download_strategy.rb
Labels: in progress

#4829 README: add maintainers.
  README.md
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4799 Add `$LOAD_PATH` for RuboCop cops.
  Library/Homebrew/global.rb
  Library/Homebrew/load_path.rb
  Library/Homebrew/rubocops.rb
  Library/Homebrew/rubocops/caveats_cop.rb
  Library/Homebrew/rubocops/checksum_cop.rb
  Library/Homebrew/rubocops/class_cop.rb
  Library/Homebrew/rubocops/components_order_cop.rb
  Library/Homebrew/rubocops/components_redundancy_cop.rb
  Library/Homebrew/rubocops/conflicts_cop.rb
  Library/Homebrew/rubocops/dependency_order_cop.rb
  Library/Homebrew/rubocops/extend/formula_cop.rb
  Library/Homebrew/rubocops/formula_desc_cop.rb
  Library/Homebrew/rubocops/homepage_cop.rb
  Library/Homebrew/rubocops/lines_cop.rb
  Library/Homebrew/rubocops/options_cop.rb
  Library/Homebrew/rubocops/patches_cop.rb
  Library/Homebrew/rubocops/text_cop.rb
  Library/Homebrew/rubocops/urls_cop.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/rubocop_spec.rb
  Library/Homebrew/test/rubocops/caveats_cop_spec.rb
  Library/Homebrew/test/rubocops/checksum_cop_spec.rb
  Library/Homebrew/test/rubocops/class_cop_spec.rb
  Library/Homebrew/test/rubocops/components_order_cop_spec.rb
  Library/Homebrew/test/rubocops/components_redundancy_cop_spec.rb
  Library/Homebrew/test/rubocops/conflicts_cop_spec.rb
  Library/Homebrew/test/rubocops/dependency_order_cop_spec.rb
  Library/Homebrew/test/rubocops/formula_desc_cop_spec.rb
  Library/Homebrew/test/rubocops/homepage_cop_spec.rb
  Library/Homebrew/test/rubocops/lines_cop_spec.rb
  Library/Homebrew/test/rubocops/options_cop_spec.rb
  Library/Homebrew/test/rubocops/patches_cop_spec.rb
  Library/Homebrew/test/rubocops/text_cop_spec.rb
  Library/Homebrew/test/rubocops/urls_cop_spec.rb
Labels: in progress

#4835 Remove redundant namespacing.
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/generic-artifact-absolute-target.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/with-generic-artifact.rb
Labels: in progress

#4834 Deprecate `brew cask --version`.
  Library/Homebrew/cask/all.rb
  Library/Homebrew/cask/cmd.rb
  Library/Homebrew/cask/cmd/doctor.rb
  Library/Homebrew/cask/version.rb
  Library/Homebrew/cmd/--version.rb
  Library/Homebrew/compat/cask.rb
  Library/Homebrew/compat/cask/cmd/--version.rb
  Library/Homebrew/test/cask/cli/--version_spec.rb
  Library/Homebrew/test/cask/cli/doctor_spec.rb
Labels: in progress

#4836 Rename `test/cask/cli` to `test/cask/cmd`.
  Library/Homebrew/test/cask/cmd/audit_spec.rb
  Library/Homebrew/test/cask/cmd/cat_spec.rb
  Library/Homebrew/test/cask/cmd/create_spec.rb
  Library/Homebrew/test/cask/cmd/doctor_spec.rb
  Library/Homebrew/test/cask/cmd/edit_spec.rb
  Library/Homebrew/test/cask/cmd/fetch_spec.rb
  Library/Homebrew/test/cask/cmd/home_spec.rb
  Library/Homebrew/test/cask/cmd/info_spec.rb
  Library/Homebrew/test/cask/cmd/install_spec.rb
  Library/Homebrew/test/cask/cmd/internal_stanza_spec.rb
  Library/Homebrew/test/cask/cmd/list_spec.rb
  Library/Homebrew/test/cask/cmd/options_spec.rb
  Library/Homebrew/test/cask/cmd/outdated_spec.rb
  Library/Homebrew/test/cask/cmd/quarantine_spec.rb
  Library/Homebrew/test/cask/cmd/reinstall_spec.rb
  Library/Homebrew/test/cask/cmd/shared_examples/invalid_option.rb
  Library/Homebrew/test/cask/cmd/shared_examples/requires_cask_token.rb
  Library/Homebrew/test/cask/cmd/style_spec.rb
  Library/Homebrew/test/cask/cmd/uninstall_spec.rb
  Library/Homebrew/test/cask/cmd/upgrade_spec.rb
  Library/Homebrew/test/cask/cmd/zap_spec.rb
Labels: in progress

#4837 Use classes for instance doubles.
  Library/Homebrew/test/cache_store_spec.rb
  Library/Homebrew/test/cask/artifact/installer_spec.rb
Labels: in progress

#4831 std: use HOMEBREW_ARCH env var on Linux
  Library/Homebrew/extend/ENV/std.rb
Labels: features

#4839 Revert "std: use HOMEBREW_ARCH env var on Linux"
  Library/Homebrew/extend/ENV/std.rb
Labels: in progress

#4841 os/mac: also update install on version bumps.
  Library/Homebrew/os/mac.rb
Labels: in progress

#4842 gitignore: general cleanup
  .gitignore
Labels: in progress

#4843 dev-cmd/edit: simplify project view handling.
  Library/Homebrew/dev-cmd/edit.rb
Labels: in progress

#4840 Update minimum Git version.
  Library/Homebrew/brew.sh
  Library/Homebrew/diagnostic.rb
Labels: in progress

#4830 cmd/info: display analytics data.
  Library/Homebrew/cmd/info.rb
  docs/Manpage.md
  docs/Querying-Brew.md
  manpages/brew.1
Labels: in progress

#4845 docs: various updates.
  docs/Acceptable-Formulae.md
  docs/Analytics.md
  docs/Bottles.md
  docs/Building-Against-Non-Homebrew-Dependencies.md
  docs/C++-Standard-Libraries.md
  docs/External-Commands.md
  docs/FAQ.md
  docs/Formula-Cookbook.md
  docs/How-To-Open-a-Homebrew-Pull-Request.md
  docs/Interesting-Taps-and-Forks.md
  docs/Maintainers-Avoiding-Burnout.md
  docs/Prose-Style-Guidelines.md
  docs/Querying-Brew.md
  docs/Shell-Completion.md
  docs/Taps.md
  docs/Tips-N'-Tricks.md
  docs/Versions.md
Labels: in progress

#4832 LinkageChecker: Report linkage of unwanted system libraries [Linux]
  Library/Homebrew/extend/os/linkage_checker.rb
  Library/Homebrew/extend/os/linux/linkage_checker.rb
  Library/Homebrew/linkage_checker.rb
Labels: in progress

#4850 docs: fix typo from #4845.
  docs/C++-Standard-Libraries.md
Labels: in progress

#4844 Improve writable directory handling
  Library/Homebrew/cleanup.rb
  Library/Homebrew/cmd/reinstall.rb
  Library/Homebrew/config.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/install.rb
  Library/Homebrew/keg.rb
  Library/Homebrew/lock_file.rb
  Library/Homebrew/test/cleanup_spec.rb
  Library/Homebrew/test/diagnostic_spec.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/test/support/lib/config.rb
  Library/Homebrew/update_migrator.rb
  docs/Troubleshooting.md
Labels: in progress

#4855 keg: don't require Caskroom to be writable.
  Library/Homebrew/keg.rb
Labels: in progress

#4847 Check for range support instead of rescuing error.
  Library/Homebrew/dev-cmd/pull.rb
  Library/Homebrew/test/download_strategies_spec.rb
  Library/Homebrew/utils/curl.rb
Labels: in progress

#4846 docs/Maintainer-Guidelines: add more guidelines.
  docs/Maintainer-Guidelines.md
Labels: in progress

#4868 cmd/update: follow GitHub API redirects.
  Library/Homebrew/cmd/update.sh
Labels: in progress

#4871 Don’t add error when changing checksum to `:no_check`.
  Library/Homebrew/cask/audit.rb
Labels: in progress

#4851 Add Homebrew::DEFAULT_PREFIX for Linux
  Library/Homebrew/cmd/--prefix.rb
  Library/Homebrew/cmd/link.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/tap-new.rb
  Library/Homebrew/extend/os/analytics.rb
  Library/Homebrew/extend/os/mac/utils/analytics.rb
  Library/Homebrew/global.rb
  Library/Homebrew/os/global.rb
  Library/Homebrew/os/linux/global.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/system_config.rb
  Library/Homebrew/test/utils/analytics_spec.rb
  Library/Homebrew/update_migrator.rb
  Library/Homebrew/utils/analytics.rb
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4875 Elide prefix "/usr/local" in bottle block
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/global.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/system_config.rb
Labels: in progress

#4884 docs/Maintainer-Guidelines: retire lead maintainer position in Febuary.
  docs/Maintainer-Guidelines.md
Labels: in progress

#4888 README: remove DomT4.
  README.md
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4872 Resolve formulae in `brew cleanup`.
  Library/Homebrew/cleanup.rb
  Library/Homebrew/extend/ARGV.rb
  Library/Homebrew/formulary.rb
Labels: in progress

#4892 dev-cmd/bottle: fix --keep-old with --root-url
  Library/Homebrew/dev-cmd/bottle.rb
Labels: in progress

#4887 cmd/shellenv: use Bash.
  Library/Homebrew/cmd/shellenv.rb
  Library/Homebrew/cmd/shellenv.sh
  Library/Homebrew/test/cmd/shellenv_spec.rb
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4890 Elide default root_url in the bottle block
  Library/Homebrew/dev-cmd/bottle.rb
Labels: in progress

#4891 use 'number_readable' when displaying analytics
  Library/Homebrew/cmd/info.rb
Labels: in progress

#4895 Use Bundler to manage vendor directory
  .gitignore
  Library/Homebrew/cask/artifact/pkg.rb
  Library/Homebrew/extend/string.rb
  Library/Homebrew/load_path.rb
  Library/Homebrew/os/mac/mach.rb
  Library/Homebrew/system_command.rb
  Library/Homebrew/vendor/.bundle/config
  Library/Homebrew/vendor/Gemfile
  Library/Homebrew/vendor/Gemfile.lock
  Library/Homebrew/vendor/bundle-standalone/bundler/setup.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/backports-3.8.0/lib/backports/2.4.0/string/match.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/plist-3.3.0/lib/plist.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/plist-3.3.0/lib/plist/generator.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/plist-3.3.0/lib/plist/parser.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/plist-3.3.0/lib/plist/version.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/ruby-macho-2.0.0/lib/macho.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/ruby-macho-2.0.0/lib/macho/exceptions.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/ruby-macho-2.0.0/lib/macho/fat_file.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/ruby-macho-2.0.0/lib/macho/headers.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/ruby-macho-2.0.0/lib/macho/load_commands.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/ruby-macho-2.0.0/lib/macho/macho_file.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/ruby-macho-2.0.0/lib/macho/sections.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/ruby-macho-2.0.0/lib/macho/structure.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/ruby-macho-2.0.0/lib/macho/tools.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/ruby-macho-2.0.0/lib/macho/utils.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/ruby-macho-2.0.0/lib/macho/view.rb
Labels: in progress

#4899 Update vendored gems
  Library/Homebrew/vendor/Gemfile.lock
  Library/Homebrew/vendor/bundle-standalone/bundler/setup.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/backports-3.11.4/lib/backports/2.4.0/string/match.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/backports-3.8.0/lib/backports/2.4.0/string/match.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/plist-3.3.0/lib/plist/generator.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/plist-3.4.0/lib/plist.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/plist-3.4.0/lib/plist/generator.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/plist-3.4.0/lib/plist/parser.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/plist-3.4.0/lib/plist/version.rb
Labels: in progress

#4900 Make remaining `curl` respect `HOMEBREW_CURLRC`
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/utils/analytics.rb
Labels: in progress

#4901 Retry all specs with `:needs_network`.
  Library/Homebrew/test/cmd/search_spec.rb
  Library/Homebrew/test/cmd/services_spec.rb
  Library/Homebrew/test/dev-cmd/pull_spec.rb
  Library/Homebrew/test/spec_helper.rb
Labels: in progress

#4897 Remove `__MACOSX` directory after unzipping.
  Library/Homebrew/unpack_strategy/zip.rb
Labels: in progress

#4902 Use ActiveSupport Object#blank? and #present?
  .gitignore
  Library/Homebrew/cask/cmd/doctor.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/extend/os/linux/diagnostic.rb
  Library/Homebrew/global.rb
  Library/Homebrew/missing_formula.rb
  Library/Homebrew/vendor/Gemfile
  Library/Homebrew/vendor/Gemfile.lock
  Library/Homebrew/vendor/bundle-standalone/bundler/setup.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/core_ext/object/blank.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/core_ext/regexp.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/collection/map/mri_map_backend.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/collection/map/non_concurrent_map_backend.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/constants.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/abstract_lockable_object.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/abstract_object.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/condition.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/jruby_lockable_object.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/jruby_object.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/lock.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/lockable_object.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_object.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/object.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/rbx_lockable_object.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/rbx_object.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/truffle_lockable_object.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/truffle_object.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/volatile.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/utility/engine.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/utility/native_extension_loader.rb
Labels: in progress

#4906 Add `String#delete_prefix` backport.
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/pull.rb
  Library/Homebrew/extend/ARGV.rb
  Library/Homebrew/extend/string.rb
  Library/Homebrew/linkage_checker.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/backports-3.11.4/lib/backports/2.5.0/string/delete_prefix.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/backports-3.11.4/lib/backports/tools/arguments.rb
Labels: in progress

#4918 Update RuboCop to 0.58.2.
  Library/Homebrew/constants.rb
  Library/Homebrew/test/Gemfile.lock
Labels: in progress

#4927 Library/.rubocop.yml: disable `RescueEnsureAlignment`
  Library/.rubocop.yml
  Library/Homebrew/.rubocop.yml
Labels: in progress

#4912 Use ActiveSupport Hash#deep_merge
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/global.rb
  Library/Homebrew/utils.rb
  Library/Homebrew/utils/hash.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/core_ext/hash/deep_merge.rb
Labels: in progress

#4913 Use ActiveSupport File.atomic_write
  Library/Homebrew/extend/pathname.rb
  Library/Homebrew/global.rb
  Library/Homebrew/test/pathname_spec.rb
  Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/core_ext/file/atomic.rb
Labels: in progress

#4929 Utils::Analytics.custom_prefix_label: Fix typo
  Library/Homebrew/utils/analytics.rb
Labels: in progress

#4932 update-reset: allow specifying repositories.
  Library/Homebrew/cmd/update-reset.sh
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4933 test/Gemfile: add ronn.
  Library/Homebrew/test/Gemfile
Labels: in progress

#4862 make dependency_order_cop a regular audit
  Library/Homebrew/rubocops/dependency_order_cop.rb
  Library/Homebrew/test/rubocops/dependency_order_cop_spec.rb
Labels: in progress

#4935 Update `Gemfile.lock`.
  Library/Homebrew/test/Gemfile.lock
Labels: in progress

#4934 Add `SystemCommand::Result#merged_output`.
  Library/Homebrew/system_command.rb
  Library/Homebrew/test/system_command_result_spec.rb
Labels: in progress

#4853 utils/fork: Check if error pipe is closed
  Library/Homebrew/exceptions.rb
  Library/Homebrew/utils/fork.rb
Labels: in progress

#4938 Cleanup Travis and CI configuration.
  Library/Homebrew/extend/os/mac/diagnostic.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/utils/curl.rb
  azure-pipelines.yml
Labels: in progress

#4909 Run tests with `HOMEBREW_DEVELOPER` unset.
  Library/Homebrew/brew.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/test/cmd/uninstall_spec.rb
  Library/Homebrew/test/formula_installer_spec.rb
  Library/Homebrew/test/utils_spec.rb
  Library/Homebrew/utils.rb
Labels: in progress

#4949 cache_store: handle corrupt DBM database.
  Library/Homebrew/cache_store.rb
  Library/Homebrew/system_command.rb
  Library/Homebrew/test/cache_store_spec.rb
  Library/Homebrew/utils/ruby.sh
Labels: in progress

#4941 super/cc: further bump -mmacosx-version-min on Mojave
  Library/Homebrew/shims/super/cc
Labels: in progress

#4952 shims/super/cc: detect High Sierra differently.
  Library/Homebrew/brew.sh
  Library/Homebrew/shims/scm/git
  Library/Homebrew/shims/super/cc
Labels: in progress

#4948 Install and use RuboCop RSpec by default.
  Library/Homebrew/.rubocop-rspec.yml
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/.rubocop_todo.yml
  Library/Homebrew/cmd/style.rb
  Library/Homebrew/style.rb
  Library/Homebrew/test/Gemfile
  Library/Homebrew/test/Gemfile.lock
  Library/Homebrew/test/bottle_filename_spec.rb
  Library/Homebrew/test/cache_store_spec.rb
  Library/Homebrew/test/cask/artifact/app_spec.rb
  Library/Homebrew/test/cask/artifact/installer_spec.rb
  Library/Homebrew/test/cask/cask_spec.rb
  Library/Homebrew/test/cask/cmd/info_spec.rb
  Library/Homebrew/test/cask/cmd/style_spec.rb
  Library/Homebrew/test/cask/depends_on_spec.rb
  Library/Homebrew/test/cask/quarantine_spec.rb
  Library/Homebrew/test/cask/verify_spec.rb
  Library/Homebrew/test/cleanup_spec.rb
  Library/Homebrew/test/cli_parser_spec.rb
  Library/Homebrew/test/diagnostic_checks_spec.rb
  Library/Homebrew/test/download_strategies_spec.rb
  Library/Homebrew/test/error_during_execution_spec.rb
  Library/Homebrew/test/exceptions_spec.rb
  Library/Homebrew/test/formulary_spec.rb
  Library/Homebrew/test/linkage_cache_store_spec.rb
  Library/Homebrew/test/messages_spec.rb
  Library/Homebrew/test/os/mac_spec.rb
  Library/Homebrew/test/system_command_result_spec.rb
  Library/Homebrew/test/system_command_spec.rb
  Library/Homebrew/test/unpack_strategy/directory_spec.rb
  Library/Homebrew/test/unpack_strategy/subversion_spec.rb
  Library/Homebrew/test/update_migrator_spec.rb
  Library/Homebrew/test/utils/analytics_spec.rb
  Library/Homebrew/test/utils/curl_spec.rb
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4950 Mojave is being released
  Library/Homebrew/os/mac.rb
  docs/Installation.md
Labels: in progress

#4863 components_order_cop: add all components
  Library/Homebrew/rubocops/components_order_cop.rb
Labels: in progress

#4959 cache_store: handle missing process.
  Library/Homebrew/cache_store.rb
  docs/Analytics.md
Labels: in progress

#4960 cache_store_spec: fix bad rebase.
  Library/Homebrew/test/cache_store_spec.rb
Labels: in progress

#4958 language/haskell: use `v1` commands
  Library/Homebrew/language/haskell.rb
Labels: in progress

#4967 system_config: add `HOMEBREW_MACOS_VERSION_NUMERIC` to `boring_keys`
  Library/Homebrew/system_config.rb
Labels: in progress

#4971 system_config: don't print default HOMEBREW_GIT value.
  Library/Homebrew/system_config.rb
Labels: in progress

#4833 language/python: support pypy
  Library/Homebrew/language/python.rb
  Library/Homebrew/test/language/python_spec.rb
Labels: in progress

#4983 cache_store: check DBM values size.
  Library/Homebrew/cache_store.rb
Labels: in progress

#4876 java_requirement, cask dsl caveats: JDK 11
  Library/Homebrew/cask/dsl/caveats.rb
  Library/Homebrew/requirements/java_requirement.rb
Labels: in progress

#4984 cache_store: use JSON.
  Library/Homebrew/cache_store.rb
  Library/Homebrew/linkage_cache_store.rb
  Library/Homebrew/test/cache_store_spec.rb
Labels: in progress

#4970 keg: further tweak directory constants.
  .travis.yml
  Library/Homebrew/cleanup.rb
  Library/Homebrew/cmd/prune.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/install.rb
  Library/Homebrew/keg.rb
  Library/Homebrew/test/spec_helper.rb
  azure-pipelines.yml
Labels: in progress

#4992 keg: remove TOP_LEVEL_DIRECTORIES.
  Library/Homebrew/keg.rb
Labels: in progress

#5003 os/mac/diagnostic: don't complain about Xcode version on Azure.
  Library/Homebrew/extend/os/mac/diagnostic.rb
Labels: in progress

#4994 config: hide optional system packages.
  Library/Homebrew/extend/os/mac/system_config.rb
  Library/Homebrew/system_config.rb
Labels: in progress

#4995 Default compiler is gcc on Linux
  Library/Homebrew/compilers.rb
  Library/Homebrew/development_tools.rb
  Library/Homebrew/extend/ENV/shared.rb
  Library/Homebrew/extend/os/development_tools.rb
  Library/Homebrew/extend/os/linux/development_tools.rb
  Library/Homebrew/test/compiler_selector_spec.rb
Labels: in progress
