Repository Homebrew/brew, pull requests merged in 2018-05, with the labels that each got.

#4128 Remove completions for (un)linkapps commands
  completions/bash/brew
  completions/zsh/_brew
Labels: in progress

#4152 lines_cop: Add deprected options audit for depends_on
  Library/Homebrew/rubocops/extend/formula_cop.rb
  Library/Homebrew/rubocops/lines_cop.rb
  Library/Homebrew/test/rubocops/lines_cop_spec.rb
Labels: in progress

#4154 Use new GitHub issue template format
  .github/ISSUE_TEMPLATE/Reproducible-Bug-Report.md
  docs/Troubleshooting.md
Labels: in progress

#4116 Fix `zap --force` for uninstalled casks
  Library/Homebrew/cask/lib/hbc/artifact/moved.rb
  Library/Homebrew/cask/lib/hbc/cli/zap.rb
  Library/Homebrew/manpages/brew-cask.1.md
  manpages/brew-cask.1
Labels: cask

#4160 formula: improve to_hash output.
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/test/formula_spec.rb
Labels: in progress

#4172 cask caveats dsl: add license
  Library/Homebrew/cask/lib/hbc/dsl/caveats.rb
Labels: cask, in progress

#4183 cask upgrade: ensure cache exists
  Library/Homebrew/cask/lib/hbc/cli/upgrade.rb
Labels: cask, in progress

#4186 Clean up `compat`.
  Library/Homebrew/compat/ENV/shared.rb
  Library/Homebrew/compat/dependable.rb
  Library/Homebrew/compat/extend/string.rb
  Library/Homebrew/compat/formula.rb
  Library/Homebrew/compat/gpg.rb
  Library/Homebrew/compat/hbc.rb
  Library/Homebrew/compat/hbc/cache.rb
  Library/Homebrew/compat/hbc/cask_loader.rb
  Library/Homebrew/compat/hbc/caskroom.rb
  Library/Homebrew/compat/hbc/cli/update.rb
  Library/Homebrew/compat/hbc/dsl.rb
  Library/Homebrew/compat/os/mac.rb
  Library/Homebrew/test/cask/cli_spec.rb
Labels: in progress

#4184 Remove unused `include Utils`.
  Library/Homebrew/cask/lib/hbc.rb
Labels: in progress

#4182 Move `--version` logic into `cmd/--version.rb`.
  Library/Homebrew/brew.rb
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/--version.rb
  Library/Homebrew/global.rb
Labels: in progress

#4174 Add compatibility layer for handling Cask Tap migration.
  Library/Homebrew/cask/lib/hbc/audit.rb
  Library/Homebrew/cask/lib/hbc/cli/search.rb
  Library/Homebrew/cask/lib/hbc/version.rb
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/compat.rb
  Library/Homebrew/compat/tap.rb
  Library/Homebrew/extend/git_repository.rb
  Library/Homebrew/missing_formula.rb
  Library/Homebrew/test/cask/cli/info_spec.rb
  Library/Homebrew/test/cask/cli/style_spec.rb
  Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb
Labels: in progress

#4187 python_virtualenv_constants: update virtualenv to 16.0.0
  Library/Homebrew/language/python_virtualenv_constants.rb
Labels: in progress, python

#4191 Get rid of unnecessary `cd`s.
  Library/Homebrew/extend/git_repository.rb
  Library/Homebrew/utils.rb
Labels: in progress

#3835 audit: `--new-formula`, Don't fail CI instead comment on PR about audit violations
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
  Library/Homebrew/test/dev-cmd/audit_spec.rb
  Library/Homebrew/utils/github.rb
Labels: in progress

#4201 audit: add back new formulae condition for patches
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4202 Remove some integration tests
  Library/Homebrew/test/cmd/analytics_spec.rb
  Library/Homebrew/test/cmd/command_spec.rb
  Library/Homebrew/test/cmd/desc_spec.rb
  Library/Homebrew/test/cmd/install_spec.rb
  Library/Homebrew/test/cmd/link_spec.rb
  Library/Homebrew/test/cmd/migrate_spec.rb
  Library/Homebrew/test/cmd/switch_spec.rb
  Library/Homebrew/test/deps_spec.rb
  Library/Homebrew/test/dev-cmd/pull_spec.rb
  Library/Homebrew/test/dev-cmd/ruby_spec.rb
  Library/Homebrew/test/dev-cmd/tap_spec.rb
  Library/Homebrew/test/dev-cmd/test_spec.rb
Labels: in progress

#4170 audit: new formulae should not have options
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/rubocops/options_cop.rb
  Library/Homebrew/test/rubocops/options_cop_spec.rb
Labels: in progress

#4205 spec_helper: don't truncate output expectations.
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/linkage_checker.rb
  Library/Homebrew/test/spec_helper.rb
Labels: in progress

#4207 cli_parser: Add depends_on, required_for and conflicts for switch options
  Library/Homebrew/cli_parser.rb
  Library/Homebrew/test/cli_parser_spec.rb
Labels: in progress

#4195 Activate Homebrew-Cask tap migration.
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/compat/tap.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/cmd/update-report_spec.rb
  Library/Homebrew/test/spec_helper.rb
Labels: in progress

#4209 Reset `repo_var` so it actually is re-computed.
  Library/Homebrew/compat/tap.rb
Labels: in progress

#4210 Update Homebrew-Cask references.
  .github/ISSUE_TEMPLATE/Reproducible-Bug-Report.md
  Library/Homebrew/cask/lib/hbc/audit.rb
  Library/Homebrew/cask/lib/hbc/cli/search.rb
  Library/Homebrew/cask/lib/hbc/dsl/caveats.rb
  Library/Homebrew/cask/lib/hbc/locations.rb
  Library/Homebrew/cask/lib/hbc/utils.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/manpages/brew-cask.1.md
  Library/Homebrew/manpages/brew.1.md.erb
  Library/Homebrew/missing_formula.rb
  Library/Homebrew/requirements/java_requirement.rb
  Library/Homebrew/test/cask/cli_spec.rb
  Library/Homebrew/test/cask/dsl_spec.rb
  Library/Homebrew/test/cmd/cask_spec.rb
  Library/Homebrew/test/cmd/search_spec.rb
  Library/Homebrew/test/spec_helper.rb
  completions/bash/brew
  completions/zsh/_brew_cask
  docs/Acceptable-Formulae.md
  docs/Formula-Cookbook.md
  docs/Manpage.md
  docs/Troubleshooting.md
  manpages/brew-cask.1
  manpages/brew.1
Labels: in progress

#4211 Update Cask tap regex.
  Library/Homebrew/tap_constants.rb
Labels: in progress

#4214 Fix `rspec` deprecations.
  Library/Homebrew/test/cache_store_spec.rb
  Library/Homebrew/test/spec_helper.rb
Labels: in progress

#4221 Fall back to `CaskLoader.load` to get a better error message.
  Library/Homebrew/cask/lib/hbc/caskroom.rb
Labels: in progress

#4213 Refactoring
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/compat/tap.rb
  Library/Homebrew/tap.rb
Labels: in progress

#4067 list.rb: use CLI::Parser and improve handling of flags
  Library/Homebrew/cmd/list.rb
Labels: in progress

#4229 Fix tap unavailable error for migrated Cask taps.
  Library/Homebrew/compat/tap.rb
Labels: in progress

#4238 cmd/list: add common `ls` options.
  Library/Homebrew/cmd/list.rb
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4246 download_strategy: fix bzr --HEAD downloads.
  Library/Homebrew/download_strategy.rb
Labels: in progress

#4247 bump-formula-pr: improve bad argument handling.
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
Labels: in progress
