Repository Homebrew/brew, pull requests merged in 2018-07, with the labels that each got.

#4399 Remove unneeded RuboCop comment.
  Library/Homebrew/debrew.rb
Labels: in progress

#4300 Upgrade to Rubocop 0.57.2
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/build_environment.rb
  Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb
  Library/Homebrew/cask/lib/hbc/container/cab.rb
  Library/Homebrew/cask/lib/hbc/container/generic_unar.rb
  Library/Homebrew/cask/lib/hbc/container/gpg.rb
  Library/Homebrew/cask/lib/hbc/container/gzip.rb
  Library/Homebrew/cask/lib/hbc/container/lzma.rb
  Library/Homebrew/cask/lib/hbc/container/tar.rb
  Library/Homebrew/cask/lib/hbc/container/xar.rb
  Library/Homebrew/cask/lib/hbc/container/xz.rb
  Library/Homebrew/cask/lib/hbc/macos.rb
  Library/Homebrew/cmd/diy.rb
  Library/Homebrew/constants.rb
  Library/Homebrew/cxxstdlib.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/create.rb
  Library/Homebrew/dev-cmd/edit.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/extend/os/mac/system_config.rb
  Library/Homebrew/keg.rb
  Library/Homebrew/metafiles.rb
  Library/Homebrew/migrator.rb
  Library/Homebrew/missing_formula.rb
  Library/Homebrew/options.rb
  Library/Homebrew/test/Gemfile.lock
  Library/Homebrew/test/cask/pkg_spec.rb
  Library/Homebrew/test/utils/tty_spec.rb
  Library/Homebrew/test/utils_spec.rb
Labels: in progress

#4409 install: don't exit on Homebrew.failed?
  Library/Homebrew/install.rb
Labels: in progress

#4412 Re-enable tests by removing a stray rspec `:focus`
  Library/Homebrew/test/cask/system_command_spec.rb
Labels: discussion, in progress

#4357 Show tapped casks.
  Library/Homebrew/cmd/tap-info.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/formatter_spec.rb
  Library/Homebrew/utils/formatter.rb
Labels: in progress

#4414 components_redundancy: audit `stable do` without a head or devel spec
  Library/Homebrew/rubocops/components_redundancy_cop.rb
  Library/Homebrew/test/rubocops/components_redundancy_cop_spec.rb
Labels: in progress

#4397 brew.sh: Don't allow system tmp dirs as prefixes
  Library/Homebrew/brew.sh
  Library/Homebrew/config.rb
Labels: in progress

#4416 audit: exact match throttled formula names
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4415 Cleanup HOMEBREW_TEMP handling
  Library/Homebrew/brew.sh
  Library/Homebrew/config.rb
  Library/Homebrew/dev-cmd/update-test.rb
  Library/Homebrew/system_config.rb
Labels: in progress

#4403 Update `Gemfile.lock` and use `Pathname#/`.
  Library/Homebrew/test/Gemfile.lock
  Library/Homebrew/test/support/lib/config.rb
Labels: in progress

#4344 cask audit: check for devmate and hockeyapp appcasts
  Library/Homebrew/cask/lib/hbc/audit.rb
  Library/Homebrew/test/cask/audit_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/devmate-with-appcast.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/devmate-without-appcast.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/hockeyapp-with-appcast.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/hockeyapp-without-appcast.rb
Labels: cask, in progress

#4417 vendor: ruby-macho 2.0
  Library/Homebrew/vendor/README.md
  Library/Homebrew/vendor/macho/macho.rb
  Library/Homebrew/vendor/macho/macho/fat_file.rb
  Library/Homebrew/vendor/macho/macho/headers.rb
  Library/Homebrew/vendor/macho/macho/load_commands.rb
  Library/Homebrew/vendor/macho/macho/macho_file.rb
  Library/Homebrew/vendor/macho/macho/sections.rb
  Library/Homebrew/vendor/macho/macho/structure.rb
  Library/Homebrew/vendor/macho/macho/utils.rb
  Library/Homebrew/vendor/macho/macho/view.rb
Labels: in progress

#4421 config: handle HOMEBREW_TEMP being unset.
  Library/Homebrew/config.rb
Labels: in progress

#4418 Refactor and fix VCS download strategies.
  Library/Homebrew/download_strategy.rb
Labels: in progress

#4411 audit: disallow unstable specs for versioned formulae
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4424 Refactor staging step for download strategies.
  Library/Homebrew/download_strategy.rb
Labels: in progress

#4422 bottle_block_cop: remove
  Library/Homebrew/rubocops.rb
  Library/Homebrew/rubocops/bottle_block_cop.rb
  Library/Homebrew/test/rubocops/bottle_block_cop_spec.rb
Labels: in progress

#4352 travis.yml: update xcode to 9.4
  .travis.yml
Labels: in progress

#4427 Download refactoring
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/resource.rb
Labels: in progress

#4428 extend/ENV: support CX11 for LLVM Clang.
  Library/Homebrew/extend/ENV/shared.rb
  Library/Homebrew/extend/ENV/std.rb
  Library/Homebrew/extend/ENV/super.rb
  Library/Homebrew/test/ENV_spec.rb
Labels: in progress

#4431 download_strategy: use tar xf.
  Library/Homebrew/download_strategy.rb
Labels: in progress

#4430 formula_installer: correctly handle build dep reqs.
  Library/Homebrew/formula_installer.rb
Labels: in progress

#4429 linkage: fix output of optional dependencies.
  Library/Homebrew/formula.rb
  Library/Homebrew/linkage_checker.rb
Labels: in progress

#4434 Remove unused `incremental_hash` method.
  Library/Homebrew/cask/lib/hbc/verify/checksum.rb
  Library/Homebrew/extend/pathname.rb
  Library/Homebrew/test/cask/verify/checksum_spec.rb
Labels: in progress

#4435 CLT: correct header package bundle ID
  Library/Homebrew/os/mac/xcode.rb
Labels: in progress

#4441 link: stop unneeded force linking on Mojave/CLT 10.
  Library/Homebrew/cmd/link.rb
Labels: in progress

#4426 Simplify `Hbc::SystemCommand::Result#plist`.
  Library/Homebrew/cask/lib/hbc/system_command.rb
  Library/Homebrew/test/cask/system_command_result_spec.rb
  Library/Homebrew/test/spec_helper.rb
Labels: in progress

#4444 link: fix undefined `dep_f`
  Library/Homebrew/cmd/link.rb
Labels: in progress

#4445 link: refactor, reorder and fix bugs.
  Library/Homebrew/cmd/link.rb
  Library/Homebrew/test/cmd/link_spec.rb
Labels: in progress

#4446 tab: if parsing JSON fails output the filename.
  Library/Homebrew/tab.rb
  Library/Homebrew/test/tab_spec.rb
Labels: in progress

#4406 language/python, docs: updates for python 3.7
  Library/Homebrew/language/python.rb
  docs/Gems,-Eggs-and-Perl-Modules.md
  docs/Homebrew-and-Python.md
Labels: in progress, python

#4449 global: handle HOMEBREW_BOTTLE_DOMAIN fallback.
  Library/Homebrew/global.rb
Labels: in progress

#4450 diagnostic: be clearer about what we support.
  Library/Homebrew/extend/os/mac/diagnostic.rb
Labels: in progress

#4455 Use more descriptive heredoc names.
  Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb
  Library/Homebrew/cask/lib/hbc/cli/create.rb
  Library/Homebrew/dev-cmd/mirror.rb
  Library/Homebrew/dev-cmd/tap-new.rb
  Library/Homebrew/extend/pathname.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_creator.rb
  Library/Homebrew/language/python.rb
  Library/Homebrew/sandbox.rb
  Library/Homebrew/test/cask/artifact/pkg_spec.rb
  Library/Homebrew/test/cask/cask_loader/from_content_loader_spec.rb
  Library/Homebrew/test/cask/cask_loader/from_uri_loader_spec.rb
  Library/Homebrew/test/cask/cli/cat_spec.rb
  Library/Homebrew/test/cask/cli/create_spec.rb
  Library/Homebrew/test/cask/cli/uninstall_spec.rb
  Library/Homebrew/test/cask/pkg_spec.rb
  Library/Homebrew/test/cask/system_command_result_spec.rb
  Library/Homebrew/test/cmd/custom-external-command_spec.rb
  Library/Homebrew/test/cmd/install_spec.rb
  Library/Homebrew/test/cmd/irb_spec.rb
  Library/Homebrew/test/cmd/link_spec.rb
  Library/Homebrew/test/cmd/options_spec.rb
  Library/Homebrew/test/cmd/switch_spec.rb
  Library/Homebrew/test/cmd/uses_spec.rb
  Library/Homebrew/test/deps_spec.rb
  Library/Homebrew/test/dev-cmd/audit_spec.rb
  Library/Homebrew/test/dev-cmd/test_spec.rb
  Library/Homebrew/test/formula_installer_spec.rb
  Library/Homebrew/test/formulary_spec.rb
  Library/Homebrew/test/java_requirement_spec.rb
  Library/Homebrew/test/missing_formula_spec.rb
  Library/Homebrew/test/rubocops/checksum_cop_spec.rb
  Library/Homebrew/test/rubocops/class_cop_spec.rb
  Library/Homebrew/test/rubocops/components_order_cop_spec.rb
  Library/Homebrew/test/rubocops/dependency_order_cop_spec.rb
  Library/Homebrew/test/rubocops/formula_desc_cop_spec.rb
  Library/Homebrew/test/rubocops/homepage_cop_spec.rb
  Library/Homebrew/test/rubocops/patches_cop_spec.rb
  Library/Homebrew/test/rubocops/urls_cop_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/with-uninstall-script-app.rb
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
  Library/Homebrew/test/tap_spec.rb
  Library/Homebrew/test/utils_spec.rb
Labels: in progress

#4281 Xcode: fix version detection with unknown clang
  Library/Homebrew/os/mac/xcode.rb
Labels: in progress

#4380 Properly append values to HOMEBREW_CCCFG
  Library/Homebrew/extend/ENV/shared.rb
  Library/Homebrew/extend/ENV/super.rb
  Library/Homebrew/extend/os/mac/extend/ENV/super.rb
Labels: in progress

#4420 audit: ensure `bottle` is defined
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4456 audit: check for optional and recommended requirements on new formulae
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4461 Use Ruby 2.3.7
  Library/Homebrew/cmd/vendor-install.sh
  Library/Homebrew/extend/fileutils.rb
  Library/Homebrew/extend/os/linux/hardware/cpu.rb
  Library/Homebrew/extend/os/mac/diagnostic.rb
  Library/Homebrew/test/cask/cli_spec.rb
  Library/Homebrew/utils/ruby.sh
  Library/Homebrew/vendor/portable-ruby-version
Labels: in progress

#4467 ruby.sh: cleanup gems on portable Ruby installation.
  Library/Homebrew/utils/ruby.sh
Labels: in progress

#4465 mktemp: move to Formula and compat.
  Library/Homebrew/compat/fileutils.rb
  Library/Homebrew/extend/fileutils.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/mktemp.rb
  Library/Homebrew/resource.rb
  Library/Homebrew/test/download_strategies_spec.rb
Labels: in progress

#4361 Display collected caveats at end of `install` or `upgrade`
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/reinstall.rb
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/global.rb
  Library/Homebrew/messages.rb
  Library/Homebrew/test/messages_spec.rb
Labels: in progress

#4468 `Hbc::init` does not exist anymore.
  Library/Homebrew/test/cask/cli_spec.rb
Labels: in progress

#4471 requirement: add mktemp function.
  Library/Homebrew/requirement.rb
Labels: in progress

#4457 cask audit: check for `latest` with `auto_updates`
  Library/Homebrew/cask/lib/hbc/audit.rb
  Library/Homebrew/test/cask/audit_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/latest-with-auto-updates.rb
Labels: cask, in progress

#4472 formula: move mktemp.
  Library/Homebrew/formula.rb
  Library/Homebrew/mktemp.rb
  Library/Homebrew/resource.rb
Labels: in progress

#4469 Don’t expand `executable` path in `SystemCommand`.
  Library/Homebrew/cask/lib/hbc/system_command.rb
  Library/Homebrew/test/cask/container/naked_spec.rb
  Library/Homebrew/test/support/helper/cask/fake_system_command.rb
Labels: in progress

#4392 Disable more deprecations.
  Library/Homebrew/cmd/tap.rb
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/compat.rb
  Library/Homebrew/compat/ENV/shared.rb
  Library/Homebrew/compat/dependable.rb
  Library/Homebrew/compat/dependency_collector.rb
  Library/Homebrew/compat/download_strategy.rb
  Library/Homebrew/compat/extend/string.rb
  Library/Homebrew/compat/fileutils.rb
  Library/Homebrew/compat/formula.rb
  Library/Homebrew/compat/formula_support.rb
  Library/Homebrew/compat/gpg.rb
  Library/Homebrew/compat/hbc.rb
  Library/Homebrew/compat/hbc/cask_loader.rb
  Library/Homebrew/compat/hbc/cli.rb
  Library/Homebrew/compat/hbc/cli/update.rb
  Library/Homebrew/compat/hbc/dsl.rb
  Library/Homebrew/compat/os/mac.rb
  Library/Homebrew/compat/requirements.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/extend/fileutils.rb
  Library/Homebrew/extend/pathname.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/global.rb
  Library/Homebrew/resource.rb
  Library/Homebrew/test/cask/dsl_spec.rb
  Library/Homebrew/test/dependency_collector_spec.rb
  Library/Homebrew/test/formula_spec.rb
  Library/Homebrew/test/formula_support_spec.rb
  Library/Homebrew/test/mpi_requirement_spec.rb
  Library/Homebrew/test/pathname_spec.rb
Labels: in progress

#4477 formulary: catch argument errors.
  Library/Homebrew/formulary.rb
Labels: in progress

#4478 formulary: handle missing methods.
  Library/Homebrew/formulary.rb
Labels: in progress

#4343 cask info: display `auto_updates`
  Library/Homebrew/cask/lib/hbc/cli/info.rb
  Library/Homebrew/cask/lib/hbc/cli/upgrade.rb
  Library/Homebrew/test/cask/cli/info_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/with-auto-updates.rb
Labels: cask, in progress

#4474 Refactor containers and automatically determine dependencies.
  Library/Homebrew/cask/lib/hbc/container.rb
  Library/Homebrew/cask/lib/hbc/container/air.rb
  Library/Homebrew/cask/lib/hbc/container/base.rb
  Library/Homebrew/cask/lib/hbc/container/bzip2.rb
  Library/Homebrew/cask/lib/hbc/container/cab.rb
  Library/Homebrew/cask/lib/hbc/container/criteria.rb
  Library/Homebrew/cask/lib/hbc/container/directory.rb
  Library/Homebrew/cask/lib/hbc/container/dmg.rb
  Library/Homebrew/cask/lib/hbc/container/executable.rb
  Library/Homebrew/cask/lib/hbc/container/generic_unar.rb
  Library/Homebrew/cask/lib/hbc/container/gpg.rb
  Library/Homebrew/cask/lib/hbc/container/gzip.rb
  Library/Homebrew/cask/lib/hbc/container/lzma.rb
  Library/Homebrew/cask/lib/hbc/container/otf.rb
  Library/Homebrew/cask/lib/hbc/container/pkg.rb
  Library/Homebrew/cask/lib/hbc/container/rar.rb
  Library/Homebrew/cask/lib/hbc/container/seven_zip.rb
  Library/Homebrew/cask/lib/hbc/container/sit.rb
  Library/Homebrew/cask/lib/hbc/container/svn_repository.rb
  Library/Homebrew/cask/lib/hbc/container/tar.rb
  Library/Homebrew/cask/lib/hbc/container/ttf.rb
  Library/Homebrew/cask/lib/hbc/container/xar.rb
  Library/Homebrew/cask/lib/hbc/container/xz.rb
  Library/Homebrew/cask/lib/hbc/container/zip.rb
  Library/Homebrew/cask/lib/hbc/installer.rb
  Library/Homebrew/unpack_strategy.rb
Labels: in progress

#4480 Clear `Tap` cache before each example.
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb
Labels: in progress

#4479 Change `Container::me?` to `Container::can_extract?`.
  Library/Homebrew/cask/lib/hbc/artifact/nested_container.rb
  Library/Homebrew/cask/lib/hbc/container.rb
  Library/Homebrew/cask/lib/hbc/container/air.rb
  Library/Homebrew/cask/lib/hbc/container/base.rb
  Library/Homebrew/cask/lib/hbc/container/bzip2.rb
  Library/Homebrew/cask/lib/hbc/container/cab.rb
  Library/Homebrew/cask/lib/hbc/container/dmg.rb
  Library/Homebrew/cask/lib/hbc/container/executable.rb
  Library/Homebrew/cask/lib/hbc/container/generic_unar.rb
  Library/Homebrew/cask/lib/hbc/container/gpg.rb
  Library/Homebrew/cask/lib/hbc/container/gzip.rb
  Library/Homebrew/cask/lib/hbc/container/lzma.rb
  Library/Homebrew/cask/lib/hbc/container/naked.rb
  Library/Homebrew/cask/lib/hbc/container/otf.rb
  Library/Homebrew/cask/lib/hbc/container/pkg.rb
  Library/Homebrew/cask/lib/hbc/container/rar.rb
  Library/Homebrew/cask/lib/hbc/container/self_extracting_executable.rb
  Library/Homebrew/cask/lib/hbc/container/seven_zip.rb
  Library/Homebrew/cask/lib/hbc/container/sit.rb
  Library/Homebrew/cask/lib/hbc/container/svn_repository.rb
  Library/Homebrew/cask/lib/hbc/container/tar.rb
  Library/Homebrew/cask/lib/hbc/container/ttf.rb
  Library/Homebrew/cask/lib/hbc/container/xar.rb
  Library/Homebrew/cask/lib/hbc/container/xz.rb
  Library/Homebrew/cask/lib/hbc/container/zip.rb
  Library/Homebrew/cask/lib/hbc/installer.rb
Labels: in progress

#4483 Handle missing formulae in runtime_dependencies
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/linkage_checker.rb
  Library/Homebrew/tab.rb
Labels: in progress

#4481 Add two new unpack strategies.
  Library/Homebrew/unpack_strategy.rb
Labels: in progress

#4484 Add support for nested archives.
  Library/Homebrew/test/unpack_strategy_spec.rb
  Library/Homebrew/unpack_strategy.rb
Labels: in progress

#4489 Move error to the right place.
  Library/Homebrew/cask/lib/hbc/installer.rb
Labels: in progress

#4486 Assimilate `Container`s with `UnpackStrategy`.
  Library/Homebrew/cask/lib/hbc/artifact/nested_container.rb
  Library/Homebrew/cask/lib/hbc/container/air.rb
  Library/Homebrew/cask/lib/hbc/container/base.rb
  Library/Homebrew/cask/lib/hbc/container/bzip2.rb
  Library/Homebrew/cask/lib/hbc/container/cab.rb
  Library/Homebrew/cask/lib/hbc/container/dmg.rb
  Library/Homebrew/cask/lib/hbc/container/generic_unar.rb
  Library/Homebrew/cask/lib/hbc/container/gpg.rb
  Library/Homebrew/cask/lib/hbc/container/gzip.rb
  Library/Homebrew/cask/lib/hbc/container/lzma.rb
  Library/Homebrew/cask/lib/hbc/container/naked.rb
  Library/Homebrew/cask/lib/hbc/container/rar.rb
  Library/Homebrew/cask/lib/hbc/container/seven_zip.rb
  Library/Homebrew/cask/lib/hbc/container/svn_repository.rb
  Library/Homebrew/cask/lib/hbc/container/tar.rb
  Library/Homebrew/cask/lib/hbc/container/xar.rb
  Library/Homebrew/cask/lib/hbc/container/xz.rb
  Library/Homebrew/cask/lib/hbc/container/zip.rb
  Library/Homebrew/cask/lib/hbc/installer.rb
  Library/Homebrew/test/cask/container/naked_spec.rb
  Library/Homebrew/test/cask/installer_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/container-bzip2.rb
Labels: in progress

#4495 Use `extract_nestedly` for staging.
  Library/Homebrew/download_strategy.rb
Labels: in progress

#4497 Fix typo.
  Library/Homebrew/test/PATH_spec.rb
Labels: in progress

#4499 Use non-legacy test example in PR template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: in progress

#4502 formula: handle unavailable missing formulae.
  Library/Homebrew/formula.rb
Labels: in progress

#4410 Cask json
  Library/Homebrew/cask/lib/hbc/cask.rb
  Library/Homebrew/cask/lib/hbc/cli/info.rb
Labels: cask

#4500 Refactor `$LOAD_PATH`.
  Library/Homebrew/brew.rb
  Library/Homebrew/config.rb
  Library/Homebrew/dev-cmd/ruby.rb
  Library/Homebrew/dev-cmd/test.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/global.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
  Library/Homebrew/test/support/lib/config.rb
Labels: in progress

#4506 Revert "Explicitly chmod exec script files"
  Library/Homebrew/extend/pathname.rb
Labels: in progress

#4508 ruby.sh: remove linkage cache on upgrade.
  Library/Homebrew/utils/ruby.sh
Labels: in progress

#4511 Don't pass down basename when extracting nestedly.
  Library/Homebrew/unpack_strategy.rb
Labels: in progress

#4513 fix cask seven_zip containers
  Library/Homebrew/cask/lib/hbc/container/seven_zip.rb
Labels: in progress

#4516 Fix `zsh` completion.
  completions/zsh/_brew
  completions/zsh/_brew_cask
Labels: in progress

#4515 Add test for basename in `#extract_nestedly`.
  Library/Homebrew/test/unpack_strategy_spec.rb
  Library/Homebrew/unpack_strategy.rb
Labels: in progress

#4521 man: improve messaging on no `ronn` output.
  Library/Homebrew/dev-cmd/man.rb
Labels: in progress

#4520 Add HOMEBREW_FORCE_BOTTLE variable
  Library/Homebrew/brew.sh
  Library/Homebrew/extend/ARGV.rb
  Library/Homebrew/manpages/brew.1.md.erb
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4518 fix cask rar containers
  Library/Homebrew/cask/lib/hbc/container/rar.rb
Labels: in progress

#4523 Fix JAR detection.
  Library/Homebrew/unpack_strategy.rb
Labels: in progress

#4488 Refactor `Hbc::SystemCommand`.
  Library/Homebrew/cask/lib/hbc/artifact/artifact.rb
  Library/Homebrew/cask/lib/hbc/artifact/installer.rb
  Library/Homebrew/cask/lib/hbc/artifact/pkg.rb
  Library/Homebrew/cask/lib/hbc/artifact/relocated.rb
  Library/Homebrew/cask/lib/hbc/exceptions.rb
  Library/Homebrew/cask/lib/hbc/system_command.rb
  Library/Homebrew/cask/lib/hbc/utils.rb
  Library/Homebrew/cask/lib/hbc/utils/hash_validator.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/extend/hash_validator.rb
  Library/Homebrew/extend/os/linux/keg_relocate.rb
  Library/Homebrew/os/linux/elf.rb
  Library/Homebrew/patch.rb
  Library/Homebrew/test/cask/system_command_spec.rb
  Library/Homebrew/test/error_during_execution_spec.rb
  Library/Homebrew/test/exceptions_spec.rb
  Library/Homebrew/utils.rb
  Library/Homebrew/utils/popen.rb
Labels: in progress

#4525 Remove `Hbc::Container::Criteria`.
  Library/Homebrew/cask/lib/hbc/container.rb
  Library/Homebrew/cask/lib/hbc/container/criteria.rb
Labels: in progress

#4531 Increase spec timeout to 30 seconds
  Library/Homebrew/test/cask/system_command_spec.rb
Labels: in progress

#4524 Fix missing `super`.
  Library/Homebrew/unpack_strategy.rb
Labels: in progress

#4535 Fix `Searchable` when collection contains `nil`.
  Library/Homebrew/searchable.rb
  Library/Homebrew/test/searchable_spec.rb
Labels: in progress

#4537 bottle: add --json and --merge docs.
  Library/Homebrew/dev-cmd/bottle.rb
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4536 Add `system_command` helpers.
  Library/Homebrew/cask/lib/hbc/artifact/nested_container.rb
  Library/Homebrew/cask/lib/hbc/container/air.rb
  Library/Homebrew/cask/lib/hbc/container/base.rb
  Library/Homebrew/cask/lib/hbc/container/bzip2.rb
  Library/Homebrew/cask/lib/hbc/container/cab.rb
  Library/Homebrew/cask/lib/hbc/container/dmg.rb
  Library/Homebrew/cask/lib/hbc/container/generic_unar.rb
  Library/Homebrew/cask/lib/hbc/container/gzip.rb
  Library/Homebrew/cask/lib/hbc/container/lzma.rb
  Library/Homebrew/cask/lib/hbc/container/naked.rb
  Library/Homebrew/cask/lib/hbc/container/rar.rb
  Library/Homebrew/cask/lib/hbc/container/seven_zip.rb
  Library/Homebrew/cask/lib/hbc/container/svn_repository.rb
  Library/Homebrew/cask/lib/hbc/container/tar.rb
  Library/Homebrew/cask/lib/hbc/container/xar.rb
  Library/Homebrew/cask/lib/hbc/container/xz.rb
  Library/Homebrew/cask/lib/hbc/container/zip.rb
  Library/Homebrew/cask/lib/hbc/installer.rb
  Library/Homebrew/system_command.rb
  Library/Homebrew/test/cask/container/dmg_spec.rb
  Library/Homebrew/test/cask/container/naked_spec.rb
Labels: in progress

#4538 audit: output new formula issue comment failure message.
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4534 Remove `Hbc::Container::Gpg`.
  Library/Homebrew/cask/lib/hbc/container.rb
  Library/Homebrew/cask/lib/hbc/container/gpg.rb
Labels: in progress

#4540 Refactor unpack strategies into separate files.
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/test/unpack_strategy/bazaar_spec.rb
  Library/Homebrew/test/unpack_strategy/bzip2_spec.rb
  Library/Homebrew/test/unpack_strategy/cvs_spec.rb
  Library/Homebrew/test/unpack_strategy/directory_spec.rb
  Library/Homebrew/test/unpack_strategy/git_spec.rb
  Library/Homebrew/test/unpack_strategy/gzip_spec.rb
  Library/Homebrew/test/unpack_strategy/jar_spec.rb
  Library/Homebrew/test/unpack_strategy/lha_spec.rb
  Library/Homebrew/test/unpack_strategy/lzip_spec.rb
  Library/Homebrew/test/unpack_strategy/mercurial_spec.rb
  Library/Homebrew/test/unpack_strategy/p7zip_spec.rb
  Library/Homebrew/test/unpack_strategy/rar_spec.rb
  Library/Homebrew/test/unpack_strategy/shared_examples.rb
  Library/Homebrew/test/unpack_strategy/subversion_spec.rb
  Library/Homebrew/test/unpack_strategy/tar_spec.rb
  Library/Homebrew/test/unpack_strategy/uncompressed_spec.rb
  Library/Homebrew/test/unpack_strategy/xar_spec.rb
  Library/Homebrew/test/unpack_strategy/xz_spec.rb
  Library/Homebrew/test/unpack_strategy/zip_spec.rb
  Library/Homebrew/test/unpack_strategy_spec.rb
  Library/Homebrew/unpack_strategy.rb
  Library/Homebrew/unpack_strategy/bazaar.rb
  Library/Homebrew/unpack_strategy/bzip2.rb
  Library/Homebrew/unpack_strategy/compress.rb
  Library/Homebrew/unpack_strategy/cvs.rb
  Library/Homebrew/unpack_strategy/directory.rb
  Library/Homebrew/unpack_strategy/fossil.rb
  Library/Homebrew/unpack_strategy/git.rb
  Library/Homebrew/unpack_strategy/gzip.rb
  Library/Homebrew/unpack_strategy/jar.rb
  Library/Homebrew/unpack_strategy/lha.rb
  Library/Homebrew/unpack_strategy/lua_rock.rb
  Library/Homebrew/unpack_strategy/lzip.rb
  Library/Homebrew/unpack_strategy/mercurial.rb
  Library/Homebrew/unpack_strategy/microsoft_office_xml.rb
  Library/Homebrew/unpack_strategy/p7zip.rb
  Library/Homebrew/unpack_strategy/rar.rb
  Library/Homebrew/unpack_strategy/subversion.rb
  Library/Homebrew/unpack_strategy/tar.rb
  Library/Homebrew/unpack_strategy/uncompressed.rb
  Library/Homebrew/unpack_strategy/xar.rb
  Library/Homebrew/unpack_strategy/xz.rb
  Library/Homebrew/unpack_strategy/zip.rb
Labels: in progress

#4542 Change Mojave bottle behaviour
  Library/Homebrew/brew.sh
  Library/Homebrew/extend/ARGV.rb
  Library/Homebrew/extend/os/mac/utils/bottles.rb
  Library/Homebrew/manpages/brew.1.md.erb
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4544 utils/github: remove full stop from the "skipping" comment
  Library/Homebrew/utils/github.rb
Labels: in progress

#4547 Don’t rescue `NameError` for `#run`.
  Library/Homebrew/cask/lib/hbc/cli.rb
Labels: in progress

#4549 Add `Tap#command_file?` method.
  Library/Homebrew/tap.rb
Labels: in progress

#4545 Make `HOMEBREW_TAP_PATH_REGEX` also match exact path.
  Library/Homebrew/tap_constants.rb
  Library/Homebrew/test/tap_spec.rb
Labels: in progress

#4548 Tweak code coverage logic
  Library/Homebrew/.simplecov
  Library/Homebrew/test/.codecov.yml
Labels: in progress

#4557 link: when refusing to link display keg only caveats instead.
  Library/Homebrew/caveats.rb
  Library/Homebrew/cmd/--env.rb
  Library/Homebrew/cmd/link.rb
  Library/Homebrew/utils/shell.rb
Labels: in progress

#4559 Don’t match `MZ` for `Cab`.
  Library/Homebrew/test/.codecov.yml
  Library/Homebrew/unpack_strategy/cab.rb
Labels: in progress

#4555 audit: change the "unstable" spec message to devel/head
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4561 Use `SystemCommand` for `curl`.
  Library/Homebrew/cask/lib/hbc/download_strategy.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/system_command.rb
  Library/Homebrew/test/cask/download_strategy_spec.rb
  Library/Homebrew/test/cask/pkg_spec.rb
  Library/Homebrew/test/support/helper/cask/fake_system_command.rb
  Library/Homebrew/test/system_command_result_spec.rb
  Library/Homebrew/test/system_command_spec.rb
  Library/Homebrew/test/utils/curl_spec.rb
  Library/Homebrew/utils/curl.rb
  Library/Homebrew/utils/github.rb
Labels: in progress

#4564 Raise error when file does not contain a cask.
  Library/Homebrew/cask/lib/hbc/cask.rb
  Library/Homebrew/cask/lib/hbc/cask_loader.rb
  Library/Homebrew/cask/lib/hbc/exceptions.rb
  Library/Homebrew/test/cask/cask_loader/from__path_loader_spec.rb
  Library/Homebrew/test/cask/dsl_spec.rb
Labels: in progress

#4567 Revert "Use `SystemCommand` for `curl`."
  Library/Homebrew/cask/lib/hbc/download_strategy.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/system_command.rb
  Library/Homebrew/test/cask/download_strategy_spec.rb
  Library/Homebrew/test/cask/pkg_spec.rb
  Library/Homebrew/test/support/helper/cask/fake_system_command.rb
  Library/Homebrew/test/system_command_result_spec.rb
  Library/Homebrew/test/system_command_spec.rb
  Library/Homebrew/test/utils/curl_spec.rb
  Library/Homebrew/utils/curl.rb
  Library/Homebrew/utils/github.rb
Labels: in progress

#4568 formula: handle unavailable versioned formulae.
  Library/Homebrew/formula.rb
Labels: in progress

#4572 Refactor `Hbc::URL`.
  Library/Homebrew/cask/lib/hbc/dsl.rb
  Library/Homebrew/cask/lib/hbc/dsl/stanza_proxy.rb
  Library/Homebrew/cask/lib/hbc/url.rb
  Library/Homebrew/lazy_object.rb
  Library/Homebrew/test/cask/download_strategy_spec.rb
  Library/Homebrew/test/cask/dsl/stanza_proxy_spec.rb
  Library/Homebrew/test/lazy_object_spec.rb
Labels: in progress

#4573 Add spec for SVN directory name containing `@`.
  Library/Homebrew/test/unpack_strategy/subversion_spec.rb
Labels: in progress

#4571 Remove unused `brew cask _dump` command.
  Library/Homebrew/cask/lib/hbc/cask.rb
  Library/Homebrew/cask/lib/hbc/cli.rb
  Library/Homebrew/cask/lib/hbc/cli/internal_dump.rb
Labels: cask, in progress
