Repository Homebrew/brew, pull requests merged in 2018-04, with the labels that each got.

#4014 python_virtualenv_constants: update virtualenv to 15.2.0
  Library/Homebrew/language/python_virtualenv_constants.rb
Labels: python

#4029 Add message to `set_ownership`
  Library/Homebrew/cask/lib/hbc/staged.rb
Labels: cask

#4034 docs: update FAQ and Installation.
  docs/FAQ.md
  docs/Installation.md
Labels: in progress

#4007 official_taps: deprecate homebrew/php.
  Library/Homebrew/official_taps.rb
Labels: do not merge

#4033 audit (strict): check for build.with? dependencies.
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4037 keg: don't remove versioned aliases on unlink.
  Library/Homebrew/keg.rb
Labels: in progress

#4038 docs/Installation: note curl usage on <=10.7.
  docs/Installation.md
Labels: in progress

#4039 cli_parser: undefine OpenStruct instance tap.
  Library/Homebrew/cli_parser.rb
Labels: in progress

#4042 compat/formula: remove patches.
  Library/Homebrew/compat/formula.rb
Labels: in progress

#4044 urls_cop: Search for func calls to match `url` and `mirror` calls
  Library/Homebrew/rubocops/extend/formula_cop.rb
  Library/Homebrew/rubocops/urls_cop.rb
Labels: in progress

#4045 Only read curlrc if HOMEBREW_CURLRC is set.
  Library/Homebrew/cmd/vendor-install.sh
  Library/Homebrew/test/utils/curl_spec.rb
  Library/Homebrew/utils/curl.rb
Labels: in progress

#4053 compat/extend/string: fix odisabled return.
  Library/Homebrew/compat/extend/string.rb
Labels: in progress

#4061 docs/Analytics: note retention period.
  docs/Analytics.md
Labels: in progress

#4073 cli_parser: Refactor required argument for flag to '='
  Library/Homebrew/cli_parser.rb
  Library/Homebrew/dev-cmd/pull.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/dev-cmd/update-test.rb
  Library/Homebrew/test/cli_parser_spec.rb
Labels: in progress

#4075 Add missing `MacOS.release` deprecation.
  Library/Homebrew/compat.rb
  Library/Homebrew/compat/os/mac.rb
Labels: in progress

#4077 Update `rubocop-cask` to 0.18.1.
  Library/Homebrew/constants.rb
Labels: in progress

#4071 audit: new formulae should not have a HEAD spec
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4072 Cask Refactoring
  Library/Homebrew/cask/lib/hbc.rb
  Library/Homebrew/cask/lib/hbc/cask.rb
  Library/Homebrew/cask/lib/hbc/caskroom.rb
  Library/Homebrew/cask/lib/hbc/cli/audit.rb
  Library/Homebrew/cask/lib/hbc/cli/info.rb
  Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb
  Library/Homebrew/cask/lib/hbc/cli/list.rb
  Library/Homebrew/cask/lib/hbc/cli/outdated.rb
  Library/Homebrew/cask/lib/hbc/cli/search.rb
  Library/Homebrew/cask/lib/hbc/cli/style.rb
  Library/Homebrew/cask/lib/hbc/cli/upgrade.rb
  Library/Homebrew/cask/lib/hbc/macos.rb
  Library/Homebrew/cask/lib/hbc/qualified_token.rb
  Library/Homebrew/cask/lib/hbc/scopes.rb
  Library/Homebrew/cask/lib/hbc/utils.rb
  Library/Homebrew/test/cask/artifact/generic_artifact_spec.rb
  Library/Homebrew/test/cask/artifact/two_apps_incorrect_spec.rb
  Library/Homebrew/test/cask/cask_spec.rb
  Library/Homebrew/test/cask/cli/audit_spec.rb
  Library/Homebrew/test/cask/cli/style_spec.rb
  Library/Homebrew/test/cask/dsl_spec.rb
  Library/Homebrew/test/cask/scopes_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/compat/with-dsl-version.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/generic-artifact-no-target.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/invalid/invalid-generic-artifact-no-target.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/with-generic-artifact-no-target.rb
Labels: in progress

#4082 RuboCop 0.55.0.
  Library/Homebrew/cask/lib/hbc/metadata.rb
  Library/Homebrew/cli_parser.rb
  Library/Homebrew/constants.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/keg.rb
Labels: in progress

#4083 Remove Xcode.installed? guards.
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_support.rb
  Library/Homebrew/os/mac/xcode.rb
Labels: in progress

#4081 formula_support: deprecate more keg_only reasons.
  Library/Homebrew/compat/formula_support.rb
  Library/Homebrew/formula_support.rb
Labels: in progress

#4085 Xcode 9.3
  Library/Homebrew/os/mac.rb
  Library/Homebrew/os/mac/xcode.rb
Labels: in progress

#4086 formula: tweak to_hash bottle output.
  Library/Homebrew/formula.rb
Labels: in progress

#4090 requirements: define cask on base class.
  Library/Homebrew/extend/os/mac/requirements/java_requirement.rb
  Library/Homebrew/extend/os/mac/requirements/osxfuse_requirement.rb
  Library/Homebrew/extend/os/mac/requirements/x11_requirement.rb
  Library/Homebrew/requirements/java_requirement.rb
  Library/Homebrew/requirements/osxfuse_requirement.rb
  Library/Homebrew/requirements/x11_requirement.rb
Labels: in progress

#4091 formula: sort aliases in to_hash.
  Library/Homebrew/formula.rb
Labels: in progress

#4092 x11_requirement: move download to base class.
  Library/Homebrew/extend/os/mac/requirements/x11_requirement.rb
  Library/Homebrew/requirements/x11_requirement.rb
Labels: in progress

#4068 Refactor and fix style for some specs.
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/PATH.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/create.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/extend/os/mac/hardware/cpu.rb
  Library/Homebrew/extend/os/mac/requirements/non_binary_osxfuse_requirement.rb
  Library/Homebrew/extend/os/mac/requirements/osxfuse_requirement.rb
  Library/Homebrew/extend/os/requirements/non_binary_osxfuse_requirement.rb
  Library/Homebrew/hardware.rb
  Library/Homebrew/requirements/non_binary_osxfuse_requirement.rb
  Library/Homebrew/requirements/osxfuse_requirement.rb
  Library/Homebrew/test/Gemfile.lock
  Library/Homebrew/test/PATH_spec.rb
  Library/Homebrew/test/formulary_spec.rb
  Library/Homebrew/test/hardware/cpu_spec.rb
  Library/Homebrew/test/hardware_spec.rb
  Library/Homebrew/test/keg_spec.rb
  Library/Homebrew/test/missing_formula_spec.rb
  Library/Homebrew/test/os/linux/osxfuse_requirement_spec.rb
  Library/Homebrew/test/os/mac/osxfuse_requirement_spec.rb
  Library/Homebrew/test/os_requirement_spec.rb
  Library/Homebrew/test/requirements/linux_requirement_spec.rb
  Library/Homebrew/test/requirements/macos_requirement_spec.rb
  Library/Homebrew/test/requirements/non_binary_osxfuse_requirement_spec.rb
  Library/Homebrew/test/requirements/osxfuse_requirement_spec.rb
  Library/Homebrew/test/spec_helper.rb
Labels: in progress

#4104 Fix `MissingFormula` namespacing.
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/test/dev-cmd/audit_spec.rb
Labels: in progress

#4105 components_order_cop: make non-strict
  Library/Homebrew/rubocops/components_order_cop.rb
  Library/Homebrew/test/rubocops/components_order_cop_spec.rb
Labels: in progress

#4108 urls_cop pypiurls: make non-strict
  Library/Homebrew/rubocops/urls_cop.rb
  Library/Homebrew/test/rubocops/urls_cop_spec.rb
Labels: in progress

#4109 components_redundancy_cop: make non-strict
  Library/Homebrew/rubocops/components_redundancy_cop.rb
  Library/Homebrew/test/rubocops/components_redundancy_cop_spec.rb
Labels: in progress

#4111 missing_formula: improve migration messaging.
  Library/Homebrew/missing_formula.rb
Labels: in progress

#4110 formula_desc_cop desclength: make non-strict
  Library/Homebrew/rubocops/formula_desc_cop.rb
  Library/Homebrew/test/rubocops/formula_desc_cop_spec.rb
Labels: in progress

#4114 docs/Acceptable-Formulae: address feedback.
  docs/Acceptable-Formulae.md
Labels: in progress

#4117 linkage_checker: correctly handle multiple taps.
  Library/Homebrew/linkage_checker.rb
Labels: in progress

#4118 formula: read runtime dependencies from more tabs.
  Library/Homebrew/formula.rb
Labels: in progress

#4112 portable-ruby: increase to 2.3.1_1.
  Library/Homebrew/cmd/vendor-install.sh
  Library/Homebrew/vendor/portable-ruby-version
Labels: do not merge

#4122 README: goodbye Alyssa!
  README.md
  docs/Manpage.md
  manpages/brew.1
Labels: in progress
