Repository Homebrew/brew, pull requests merged in 2018-06, with the labels that each got.

#4204 audit: github notability
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4251 Moving and copying must succeed.
  Library/Homebrew/cask/lib/hbc/artifact/moved.rb
Labels: in progress

#4146 cli: Store parsed args in Homebrew.args and access @args everywhere else
  Library/Homebrew/cli_parser.rb
  Library/Homebrew/cmd/list.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
  Library/Homebrew/dev-cmd/edit.rb
  Library/Homebrew/dev-cmd/irb.rb
  Library/Homebrew/dev-cmd/man.rb
  Library/Homebrew/dev-cmd/pull.rb
  Library/Homebrew/dev-cmd/release-notes.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/dev-cmd/update-test.rb
  Library/Homebrew/test/cli_parser_spec.rb
Labels: in progress

#4255 linkage_cache: cache input data and not results.
  Library/Homebrew/extend/os/mac/formula_cellar_checks.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/linkage_cache_store.rb
  Library/Homebrew/linkage_checker.rb
  Library/Homebrew/tab.rb
  Library/Homebrew/test/linkage_cache_store_spec.rb
Labels: in progress

#4257 runtime_dependencies: include recommended deps.
  Library/Homebrew/build_options.rb
  Library/Homebrew/formula.rb
Labels: in progress

#4258 Formula#update_head_version: fix PATH.
  Library/Homebrew/formula.rb
Labels: in progress

#4263 Fix bad formula/tab runtime_dependencies handling
  Library/Homebrew/dependency.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/tab.rb
Labels: in progress

#4259 cli_parser: Rename @bump_args to args
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
Labels: in progress

#4264 Further tweak formula installer runtime dep handling
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/tab.rb
  Library/Homebrew/test/dependency_spec.rb
  Library/Homebrew/test/formula_spec.rb
  Library/Homebrew/test/formulary_spec.rb
  Library/Homebrew/test/tab_spec.rb
Labels: in progress

#4267 options_cop: formula -> formulae
  Library/Homebrew/rubocops/options_cop.rb
  Library/Homebrew/test/rubocops/options_cop_spec.rb
Labels: in progress

#4266 Fix code style in `audit` spec.
  Library/Homebrew/test/dev-cmd/audit_spec.rb
Labels: in progress

#4269 linkage: Fix `brew linkage --reverse`
  Library/Homebrew/linkage_checker.rb
Labels: in progress

#4268 linkage: Use Parser to parse args
  Library/Homebrew/dev-cmd/linkage.rb
Labels: in progress

#4271 create: Use Parser to parse args
  Library/Homebrew/dev-cmd/create.rb
  Library/Homebrew/formula_creator.rb
Labels: in progress

#4224 HBC: Make language stanza order not matter
  Library/Homebrew/cask/lib/hbc/dsl.rb
  Library/Homebrew/locale.rb
  Library/Homebrew/test/locale_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/with-languages.rb
Labels: cask, in progress

#4290 linkage_checker: fix cache invalidation.
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/keg.rb
  Library/Homebrew/linkage_cache_store.rb
  Library/Homebrew/linkage_checker.rb
Labels: in progress

#4278 cask audit: check for sourceforge appcast
  Library/Homebrew/cask/lib/hbc/audit.rb
  Library/Homebrew/test/cask/audit_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/sourceforge-with-appcast.rb
Labels: cask, in progress

#4302 missing_formula: update haskell-platform message
  Library/Homebrew/missing_formula.rb
Labels: in progress

#4253 Refactor `search`.
  Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb
  Library/Homebrew/cask/lib/hbc/cli/search.rb
  Library/Homebrew/cli_parser.rb
  Library/Homebrew/cmd/desc.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/descriptions.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/search.rb
  Library/Homebrew/searchable.rb
  Library/Homebrew/test/cask/cli/search_spec.rb
  Library/Homebrew/test/cmd/search_remote_tap_spec.rb
  Library/Homebrew/test/cmd/search_spec.rb
  Library/Homebrew/test/search_spec.rb
  Library/Homebrew/test/searchable_spec.rb
  Library/Homebrew/utils/formatter.rb
Labels: in progress

#4305 text_cop: require `dep ensure` to use `-vendor-only`
  Library/Homebrew/rubocops/text_cop.rb
  Library/Homebrew/test/rubocops/text_cop_spec.rb
Labels: in progress

#4307 Refactor `search_formulae`.
  Library/Homebrew/search.rb
Labels: in progress

#4309 audit: fix typo
  Library/Homebrew/dev-cmd/audit.rb
Labels: in progress

#4306 Refactor `brew cask search`.
  Library/Homebrew/brew.rb
  Library/Homebrew/cask/lib/hbc/cask.rb
  Library/Homebrew/cask/lib/hbc/cli/search.rb
  Library/Homebrew/cmd/cask.rb
  Library/Homebrew/dev-cmd/irb.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/search.rb
  Library/Homebrew/test/cask/cli/search_spec.rb
  Library/Homebrew/test/emoji_spec.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
  Library/Homebrew/test/utils_spec.rb
Labels: in progress

#4314 Remove `Locations` module.
  Library/Homebrew/cask/lib/hbc.rb
  Library/Homebrew/cask/lib/hbc/cache.rb
  Library/Homebrew/cask/lib/hbc/cask.rb
  Library/Homebrew/cask/lib/hbc/cask_loader.rb
  Library/Homebrew/cask/lib/hbc/caskroom.rb
  Library/Homebrew/cask/lib/hbc/cli.rb
  Library/Homebrew/cask/lib/hbc/cli/cleanup.rb
  Library/Homebrew/cask/lib/hbc/cli/doctor.rb
  Library/Homebrew/cask/lib/hbc/download_strategy.rb
  Library/Homebrew/cask/lib/hbc/dsl.rb
  Library/Homebrew/cask/lib/hbc/installer.rb
  Library/Homebrew/cask/lib/hbc/locations.rb
  Library/Homebrew/cask/lib/hbc/version.rb
  Library/Homebrew/compat/hbc/caskroom.rb
  Library/Homebrew/os/mac.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/cask/accessibility_spec.rb
  Library/Homebrew/test/cask/cask_spec.rb
  Library/Homebrew/test/cask/cli/info_spec.rb
  Library/Homebrew/test/cask/cli/style_spec.rb
  Library/Homebrew/test/cask/cli/uninstall_spec.rb
  Library/Homebrew/test/cask/installer_spec.rb
  Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb
Labels: in progress

#4311 text_cop: require cargo to use `install` instead of `build`
  Library/Homebrew/rubocops/text_cop.rb
  Library/Homebrew/test/rubocops/text_cop_spec.rb
Labels: in progress

#4322 formula_installer: don't pass spec arguments from ARGV to postinstall
  Library/Homebrew/formula_installer.rb
Labels: in progress

#4315 Remove `Hbc.init`.
  Library/Homebrew/cask/lib/hbc.rb
  Library/Homebrew/cask/lib/hbc/cache.rb
  Library/Homebrew/cask/lib/hbc/caskroom.rb
  Library/Homebrew/cask/lib/hbc/cli.rb
  Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb
  Library/Homebrew/cask/lib/hbc/cli/audit.rb
  Library/Homebrew/cask/lib/hbc/cli/cleanup.rb
  Library/Homebrew/cask/lib/hbc/cli/doctor.rb
  Library/Homebrew/cask/lib/hbc/cli/fetch.rb
  Library/Homebrew/cask/lib/hbc/cli/install.rb
  Library/Homebrew/cask/lib/hbc/cli/internal_appcast_checkpoint.rb
  Library/Homebrew/cask/lib/hbc/cli/internal_audit_modified_casks.rb
  Library/Homebrew/cask/lib/hbc/cli/list.rb
  Library/Homebrew/cask/lib/hbc/cli/upgrade.rb
  Library/Homebrew/cask/lib/hbc/download_strategy.rb
  Library/Homebrew/cask/lib/hbc/installer.rb
  Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb
Labels: in progress

#4326 Add `stderr` output to exception.
  Library/Homebrew/style.rb
Labels: in progress

#4327 Support constants in `DependencyOrder` cop.
  Library/Homebrew/rubocops/dependency_order_cop.rb
  Library/Homebrew/test/rubocops/dependency_order_cop_spec.rb
Labels: in progress

#4310 remove appcast checkpoints
  Library/Homebrew/cask/lib/hbc/audit.rb
  Library/Homebrew/cask/lib/hbc/cli.rb
  Library/Homebrew/cask/lib/hbc/cli/internal_appcast_checkpoint.rb
  Library/Homebrew/cask/lib/hbc/cli/internal_audit_modified_casks.rb
  Library/Homebrew/cask/lib/hbc/dsl/appcast.rb
  Library/Homebrew/manpages/brew-cask.1.md
  Library/Homebrew/test/cask/audit_spec.rb
  Library/Homebrew/test/cask/dsl/appcast_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/appcast-checkpoint-sha256-for-empty-string.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/appcast-invalid-checkpoint.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/appcast-missing-checkpoint.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/appcast-with-checkpoint.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/github-with-appcast.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/invalid/invalid-appcast-multiple.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/invalid/invalid-appcast-url.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/latest-with-appcast.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/sourceforge-with-appcast.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/with-appcast.rb
  manpages/brew-cask.1
Labels: cask, in progress

#4337 Refactor `.simplecov`.
  Library/Homebrew/.simplecov
Labels: in progress

#4336 bump-formula-pr: don't unset --mirror= value
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
Labels: in progress

#4329 brew.sh: enable linkage cache for developers.
  Library/Homebrew/brew.sh
  Library/Homebrew/dev-cmd/tests.rb
Labels: in progress

#4334 Mojave: require CLT header package
  Library/Homebrew/extend/os/mac/diagnostic.rb
  Library/Homebrew/extend/os/mac/system_config.rb
  Library/Homebrew/os/mac/xcode.rb
  Library/Homebrew/test/os/mac/diagnostic_spec.rb
Labels: discussion, do not merge, in progress

#4342 Fix `sudo` “Sorry, try again.” delay.
  Library/Homebrew/cask/lib/hbc/system_command.rb
  Library/Homebrew/rubocops/extend/formula_cop.rb
  Library/Homebrew/test/cask/download_strategy_spec.rb
  Library/Homebrew/test/cask/dsl_spec.rb
  Library/Homebrew/test/cask/pkg_spec.rb
  Library/Homebrew/test/cask/system_command_spec.rb
  Library/Homebrew/utils/tty.rb
Labels: cask, in progress

#4346 cask dsl versions: add minor_patch
  Library/Homebrew/cask/lib/hbc/dsl/version.rb
  Library/Homebrew/test/cask/dsl/version_spec.rb
Labels: cask, in progress

#4348 Ignore any version of Go, when it is a dependency of a bottle
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/extend/os/mac/formula_cellar_checks.rb
  Library/Homebrew/rubocops/lines_cop.rb
  Library/Homebrew/test/version_spec.rb
  Library/Homebrew/version.rb
Labels: in progress

#4320 Fix `brew cask doctor` for non-standard installation location
  Library/Homebrew/cask/lib/hbc/cli/doctor.rb
Labels: cask

#4356 Update `search` docs.
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/manpages/brew-cask.1.md
  docs/Manpage.md
  manpages/brew-cask.1
  manpages/brew.1
Labels: in progress

#4232 cask fetch and upgrade: print caveats
  Library/Homebrew/cask/lib/hbc/cli/fetch.rb
  Library/Homebrew/cask/lib/hbc/cli/upgrade.rb
Labels: cask, in progress

#4369 cache_store: create HOMEBREW_CACHE when needed.
  Library/Homebrew/cache_store.rb
Labels: in progress

#4374 mirror: invoke correct curl
  Library/Homebrew/dev-cmd/mirror.rb
Labels: in progress

#4375 mirror: use curl_executable instead of curl function
  Library/Homebrew/dev-cmd/mirror.rb
Labels: in progress

#4376 Revert "Fix SVN downloads of versioned formula by munging directory names"
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/resource.rb
Labels: in progress

#4389 portable-ruby: respect HOMEBREW_BOTTLE_DOMAIN variable.
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/vendor-install.sh
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/global.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/system_config.rb
Labels: in progress

#4391 brew.sh: remove unused variable.
  Library/Homebrew/brew.sh
Labels: in progress

#4390 linkage: enable cache by default.
  Library/Homebrew/brew.sh
  Library/Homebrew/dev-cmd/linkage.rb
  Library/Homebrew/linkage_checker.rb
  Library/Homebrew/test/dev-cmd/linkage_spec.rb
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4372 Readd functionality to list all casks.
  Library/Homebrew/cask/lib/hbc/cask.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/compat/hbc/cli/search.rb
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#4396 DependencyOrder: Fix var initialization bug
  Library/Homebrew/rubocops/dependency_order_cop.rb
Labels: in progress
