Repository Homebrew/brew, pull requests merged in 2019-01, with the labels that each got.

#5470 ErrorDuringExecution: Fix wrong number of arguments
  Library/Homebrew/exceptions.rb
Labels: bug

#5471 needed_libraries: Fix cannot find section .dynamic
  Library/Homebrew/os/linux/elf.rb
Labels: bug

#5507 extend/ARGV: don't warn on --bottle-arch=.
  Library/Homebrew/extend/ARGV.rb
Labels: bug

#5595 CaskSha256MismatchError: link to fix
  Library/Homebrew/cask/exceptions.rb
Labels: cask

#5601 Removed cleanup from cask manpage
  Library/Homebrew/manpages/brew-cask.1.md
  manpages/brew-cask.1
Labels: cask

#5607 Fix check_coretap_git_origin
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/extend/os/linux/tap.rb
  Library/Homebrew/tap.rb
Labels: bug

#5636 Remove unneeded `curl_openssl_or_deps` invocation
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/utils/curl.rb
Labels: bug

#5201 fetch: Use CLI::Parser to parse args
  Library/Homebrew/cmd/fetch.rb
  docs/Manpage.md
  manpages/brew.1
Labels: in progress
