Repository Homebrew/brew, pull requests merged in 2019-03, with the labels that each got.

#5696 elf.rb: avoid corrupted elf files
  Library/Homebrew/os/linux/elf.rb
Labels: bug

#5413 mac/keg_relocate: Rewrite rpaths in install names
  Library/Homebrew/extend/os/mac/keg_relocate.rb
  Library/Homebrew/os/mac/mach.rb
Labels: do not merge, in progress

#5793 install_symlink_p: Fix when dest includes a symlink
  Library/Homebrew/extend/pathname.rb
  Library/Homebrew/test/pathname_spec.rb
Labels: do not merge

#5894 fix_dynamic_linkage: Check HOMEBREW_RELOCATE_METAVARS
  Library/Homebrew/extend/os/mac/keg_relocate.rb
Labels: bug
