Repository Homebrew/brew, pull requests merged in 2019-04, with the labels that each got.

#5940 xcode: upgrade for Xcode 10.2 release
  Library/Homebrew/os/mac.rb
  Library/Homebrew/os/mac/xcode.rb
Labels: do not merge

#5991 Redirect docs.brew.sh/linux to Homebrew on Linux
  docs/Homebrew-on-Linux.md
Labels: documentation

#6027 hbc: remove all *_to_slashes
  Library/Homebrew/cask/dsl/version.rb
  Library/Homebrew/test/cask/dsl/version_spec.rb
Labels: cask

#6040 Endorse AdoptOpenJDK instead of Oracle OpenJDK
  Library/Homebrew/requirements/java_requirement.rb
Labels: do not merge
