Repository Homebrew/brew, pull requests merged in 2020-10, with the labels that each got.

#7925 dev-cmd: add dispatch-build-bottle command
  Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
  Library/Homebrew/test/dev-cmd/dispatch-build-bottle_spec.rb
  completions/internal_commands_list.txt
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#9001 bug fix: add missing header param to url class
  Library/Homebrew/cask/url.rb
Labels: cask

#9016 Revert "Improve @-versioned formulae linking."
  Library/Homebrew/cmd/link.rb
  Library/Homebrew/cmd/switch.rb
  Library/Homebrew/cmd/unlink.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/keg.rb
  Library/Homebrew/unlink.rb
  docs/Manpage.md
  manpages/brew.1
Labels: bug
