Repository Homebrew/brew, pull requests merged in 2020-03, with the labels that each got.

#7019 brew: remove most traces of python@2
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/language/python.rb
  docs/Gems,-Eggs-and-Perl-Modules.md
  docs/Homebrew-and-Python.md
  docs/Homebrew-homebrew-core-Merge-Checklist.md
  docs/Python-for-Formula-Authors.md
Labels: documentation, python

#7122 docs/Homebrew-on-Linux.md: Use the bash installer
  docs/Homebrew-on-Linux.md
Labels: enhancement

#7207 cask-caveats-kext: retry installation if it fails
  Library/Homebrew/cask/dsl/caveats.rb
Labels: cask

#7219 .github/workflows/tests.yml: Deploy Docker image
  .github/workflows/tests.yml
Labels: enhancement

#7228 os/mac/xcode: support Xcode 11.4
  Library/Homebrew/os/mac/xcode.rb
Labels: do not merge

#7245 pr-pull: allow to specify tap
  Library/Homebrew/dev-cmd/pr-pull.rb
  docs/Manpage.md
  manpages/brew.1
Labels: needs response
