Repository Homebrew/brew, pull requests merged in 2020-05, with the labels that each got.

#7479 docs/Homebrew-on-Linux.md: Requirements
  docs/Homebrew-on-Linux.md
Labels: documentation

#7494 docker.yml: Deploy the tagged image to Docker Hub
  .github/workflows/docker.yml
Labels: enhancement

#7504 docker.yml: Fix a typo
  .github/workflows/docker.yml
Labels: bug

#7179 Livecheck Formula DSL
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/formula.rb
  Library/Homebrew/livecheck.rb
  Library/Homebrew/test/formula_spec.rb
  Library/Homebrew/test/livecheck_spec.rb
Labels: in progress

#7555 workflows/tests: fix for pre-installed Linuxbrew
  .github/workflows/tests.yml
Labels: bug

#7575 Skip needed_libraries check when patchelf is the bottle being installed.
  Library/Homebrew/os/linux/elf.rb
Labels: gsoc-outreachy

#7617 Base homebrew/brew Docker image on ubuntu:20.04
  .github/workflows/docker.yml
  .github/workflows/tests.yml
  Dockerfile
Labels: enhancement

#7631 docker.yml: Tag homebrew/brew:$brew_version
  .github/workflows/docker.yml
Labels: bug

#7649 Dockerfile: Unset gc.auto and homebrew.devcmdrun
  Dockerfile
Labels: bug

#7545 utils/ruby.sh: search PATH for Ruby on Linux. update.sh: keep HOMEBREW_RUBY_PATH set.
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/utils/ruby.sh
Labels: enhancement

#7656 Instructions to install patchelf, when development tools cant locate …
  Library/Homebrew/extend/os/linux/keg_relocate.rb
Labels: bug

#7650 Clarify what entails a versioned formula
  docs/Versions.md
Labels: documentation
