Repository Homebrew/brew, pull requests merged in 2020-04, with the labels that each got.

#7286 Add `mdimporter` stanza to homebrew cask DSL
  Library/Homebrew/cask/artifact.rb
  Library/Homebrew/cask/artifact/abstract_artifact.rb
  Library/Homebrew/cask/artifact/mdimporter.rb
  Library/Homebrew/cask/cmd.rb
  Library/Homebrew/cask/config.rb
  Library/Homebrew/cask/dsl.rb
  Library/Homebrew/rubocops/cask/constants/stanza.rb
  Library/Homebrew/test/cask/cmd/options_spec.rb
  Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb
Labels: cask

#7333 cli/args: Make build_from_source public instance method
  Library/Homebrew/cli/args.rb
  Library/Homebrew/cli/parser.rb
  Library/Homebrew/extend/ARGV.rb
  Library/Homebrew/fetch.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/global.rb
Labels: do not merge

#7406 pr-upload: Add argument root-url
  Library/Homebrew/dev-cmd/pr-upload.rb
  docs/Manpage.md
  manpages/brew.1
Labels: enhancement

#7407 uses_from_macos: Add gzip rsync to the white list
  Library/Homebrew/rubocops/uses_from_macos.rb
Labels: bug

#7410 pr-upload: Fix a bug introduced by PR #7406
  Library/Homebrew/dev-cmd/pr-upload.rb
Labels: bug

#7433 Lint the homebrew/brew Dockerfile with `hadolint`
  .github/workflows/tests.yml
  Dockerfile
Labels: enhancement
