Repository Homebrew/brew, pull requests merged in 2020-12, with the labels that each got.

#9355 Fix RuboCop offenses.
  Library/Homebrew/extend/os/mac/hardware/cpu.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/rubocops/livecheck.rb
  Library/Homebrew/test/exceptions_spec.rb
Labels: critical

#9358 workflows/triage: skip for BrewTestBot PRs
  .github/workflows/triage.yml
Labels: critical

#7772 add verified parameter to url
  Library/.rubocop.yml
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/url.rb
  Library/Homebrew/rubocops/cask/homepage_matches_url.rb
  Library/Homebrew/rubocops/rubocop-cask.rb
  Library/Homebrew/test/cask/audit_spec.rb
  Library/Homebrew/test/rubocops/cask/homepage_matches_url_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/generic-artifact-relative-target.rb
Labels: cask

#9363 Add missing require in `dev-cmd/irb`.
  Library/Homebrew/dev-cmd/irb.rb
Labels: critical

#9357 Only deprecate "brew list" without arguments
  Library/Homebrew/cmd/list.rb
Labels: critical

#9354 cmd/formulae.sh: compatibility with GNU Sed
  Library/Homebrew/cmd/formulae.sh
Labels: critical

#9374 Mark some `audit` tests with `:needs_network`.
  Library/Homebrew/test/dev-cmd/audit_spec.rb
Labels: critical

#9373 python: update virtualenv
  Library/Homebrew/language/python.rb
Labels: critical

#9377 Suppress `parser` warnings.
  Library/Homebrew/test/rubocop_spec.rb
Labels: critical

#9366 cmd/formulae.sh: fix spaces
  Library/Homebrew/cmd/formulae.sh
Labels: critical

#9379 Fix wrong `force` keyword.
  Library/Homebrew/cmd/fetch.rb
Labels: critical

#9389 formulae: fix sed extended regex flag on macOS.
  Library/Homebrew/cmd/formulae.sh
Labels: critical

#9395 Run `vendor-gems` on Big Sur.
  .github/workflows/vendor-gems.yml
Labels: critical

#9397 style: migrate some lists back to Homebrew/brew
  Library/Homebrew/rubocops/uses_from_macos.rb
  Library/Homebrew/test/rubocops/provided_by_macos_spec.rb
  Library/Homebrew/test/rubocops/uses_from_macos_spec.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/test/support/helper/spec/shared_examples/formulae_exist.rb
  manpages/brew.1
Labels: critical

#9394 Mark `brew bump` test with `:needs_network.
  Library/Homebrew/test/dev-cmd/bump_spec.rb
Labels: critical

#9407 workflows/tests: run vendored gems on macOS 11.
  .github/workflows/tests.yml
Labels: critical

#9404 Fix ZSH FPATH handling
  Library/Homebrew/caveats.rb
  bin/brew
Labels: critical

#9412 Revert "add two flag to deps --installed"
  Library/Homebrew/cmd/deps.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#9413 utils/pypi: return nil for non-pypi-packages from url
  Library/Homebrew/test/utils/pypi_spec.rb
  Library/Homebrew/utils/pypi.rb
Labels: critical

#9398 Ensure default cask tap is installed on `CaskUnavailableError`.
  Library/Homebrew/cask/cask.rbi
  Library/Homebrew/cask/cmd.rb
  Library/Homebrew/cli/named_args.rb
  Library/Homebrew/cmd/home.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/extend/os/mac/tap.rb
  Library/Homebrew/extend/os/tap.rb
  Library/Homebrew/tap.rb
Labels: critical

#9418 brew: re-exec under native arch if requested
  Library/Homebrew/brew.sh
Labels: critical

#9442 brew.sh: don't allow system Ruby on Catalina.
  Library/Homebrew/brew.sh
Labels: critical

#9443 Fix `:arm64_big_sur` bottle ordering.
  Library/Homebrew/hardware.rb
  Library/Homebrew/os/mac/version.rb
Labels: critical

#9444 dev-cmd/dispatch-build-bottle: set ARM labels.
  Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
Labels: critical

#9445 diagnostic: don't complain about creatable directories that don't exist.
  Library/Homebrew/diagnostic.rb
Labels: critical

#9446 dev-cmd/dispatch-build-bottle: remove testing code.
  Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
Labels: critical

#9447 cmd/update: improve shallow clone message.
  Library/Homebrew/cmd/update.sh
Labels: critical

#9448 software_spec: make bottle sorting stable.
  Library/Homebrew/software_spec.rb
Labels: critical

#9452 RbConfig: fix broken MacOS SDK paths
  Library/Homebrew/extend/rbconfig_extension.rb
  Library/Homebrew/utils/gems.rb
Labels: bug, critical

#9456 Fix wrong version mapping in `bump-unversioned-casks`.
  Library/Homebrew/cli/named_args.rb
  Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
  Library/Homebrew/test/unversioned_cask_checker_spec.rb
  Library/Homebrew/unversioned_cask_checker.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#9461 Revert "Fix `:arm64_big_sur` bottle ordering."
  Library/Homebrew/hardware.rb
  Library/Homebrew/os/mac/version.rb
Labels: critical

#9465 Fix macOS Ruby version handling
  Library/Homebrew/extend/rbconfig_extension.rb
  Library/Homebrew/utils/gems.rb
  Library/Homebrew/utils/ruby.sh
Labels: critical

#9474 Add timeout in `bump-unversioned-casks`.
  Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
Labels: critical

#9464 MacOS::Version architecture handling
  Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
  Library/Homebrew/extend/os/mac/utils/bottles.rb
  Library/Homebrew/hardware.rb
  Library/Homebrew/os/mac/version.rb
  Library/Homebrew/test/os/mac/version_spec.rb
Labels: critical

#9479 cleanup: fix portable Ruby behaviour.
  Library/Homebrew/brew.sh
  Library/Homebrew/cleanup.rb
Labels: critical

#9480 caveats: remove ZSH FPATH logic.
  Library/Homebrew/caveats.rb
Labels: critical

#9483 Revert "untap: add --force switch"
  Library/Homebrew/cmd/untap.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#9481 Fix bottle prefix and repository handling
  Library/Homebrew/fetch.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/global.rb
  Library/Homebrew/keg_relocate.rb
  Library/Homebrew/os/linux/global.rb
  Library/Homebrew/os/mac/global.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
  Library/Homebrew/test/os/linux/pathname_spec.rb
  Library/Homebrew/test/support/lib/config.rb
Labels: critical

#9496 Fix `curl_http_content_headers_and_checksum`.
  Library/Homebrew/utils/curl.rb
Labels: critical

#9499 fixtures: add test.dmg
  Library/Homebrew/test/support/fixtures/test.dmg.gz
Labels: critical

#9502 Ignore `Info.plist` for nested apps.
  Library/Homebrew/unversioned_cask_checker.rb
Labels: critical

#9506 Wrap `guess_cask_version` with timeout.
  Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
Labels: critical

#9508 Run `sorbet` workflow on Big Sur.
  .github/workflows/sorbet.yml
Labels: critical

#9095 bottle: add bottle stanza by traversing AST
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/rubocops/components_order.rb
  Library/Homebrew/rubocops/shared/helper_functions.rb
  Library/Homebrew/test/utils/bottles/bottles_spec.rb
  Library/Homebrew/utils/bottles.rb
Labels: in progress

#9467 Refactor `bump-cask-pr`.
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: cask

#9523 Ignore `verified` for `url do` blocks.
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/dsl.rb
  Library/Homebrew/cask/url.rb
Labels: cask, critical

#9527 Remove stale.yml
  .github/stale.yml
Labels: critical

#9528 language/python: update homebrew-virtualenv resource
  Library/Homebrew/language/python.rb
Labels: critical

#9530 pr-upload: tighten json_files glob
  Library/Homebrew/dev-cmd/pr-upload.rb
Labels: critical

#8578 livecheck: add support for casks
  Library/Homebrew/cask/dsl.rb
  Library/Homebrew/dev-cmd/livecheck.rb
  Library/Homebrew/livecheck.rb
  Library/Homebrew/livecheck/livecheck.rb
  Library/Homebrew/rubocops/cask/constants/stanza.rb
  Library/Homebrew/test/livecheck/livecheck_spec.rb
  docs/Manpage.md
  manpages/brew.1
Labels: cask

#9129 Improve type checking documentation.
  .github/PULL_REQUEST_TEMPLATE.md
  Library/Homebrew/dev-cmd/typecheck.rb
  docs/Typechecking.md
Labels: stale

#9512 Fix unbottled dependency handling
  Library/Homebrew/exceptions.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/test/formula_installer_bottle_spec.rb
Labels: critical

#9539 Also cache failed version bump attempts.
  Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
Labels: critical

#9540 Fix parsing version from `PackageInfo` files.
  Library/Homebrew/Gemfile
  Library/Homebrew/Gemfile.lock
  Library/Homebrew/unversioned_cask_checker.rb
Labels: critical

#9522 Enable HOMEBREW_PATCHELF_RB_WRITE by default
  Library/Homebrew/os/linux/global.rb
Labels: enhancement, linux

#10024 Fix install --force-bottle for non-standard prefix
  Library/Homebrew/formula_installer.rb
Labels: bug, critical, needs response

#10025 software_spec: fix cellar any handling.
  Library/Homebrew/software_spec.rb
Labels: critical

#10026 manpage: test-bot: add --build-from-source.
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#9542 odeprecated: handle deprecated and disabled formulae.
  Library/Homebrew/utils.rb
Labels: critical

#10029 Add `BundleVersion` class.
  Library/Homebrew/bundle_version.rb
  Library/Homebrew/test/bundle_version_spec.rb
  Library/Homebrew/test/unversioned_cask_checker_spec.rb
  Library/Homebrew/unversioned_cask_checker.rb
Labels: critical

#10028 dev-cmd/pr-automerge: exclude draft PRs
  Library/Homebrew/dev-cmd/pr-automerge.rb
Labels: critical

#9524 Fix audit for `verified` parameter.
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/test/cask/audit_spec.rb
Labels: critical

#9493 Add audit for unversioned URLs with checksum.
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/test/cask/audit_spec.rb
  Library/Homebrew/test/cask/cmd/cat_spec.rb
  Library/Homebrew/test/cask/dsl_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/adobe-air.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/adobe-illustrator.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/basic-cask.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/no-dsl-version.rb
  Library/Homebrew/test/support/fixtures/third-party/Casks/pharo.rb
Labels: cask

#10034 utils/ruby: silence `which` errors when finding ruby
  Library/Homebrew/utils/ruby.sh
Labels: critical

#9518 Do not build from source on ARM unless explicitly requested
  Library/Homebrew/formula_installer.rb
Labels: in progress

#9503 Relocate @@HOMEBREW_REPOSITORY@@/Library
  Library/Homebrew/formula_cellar_checks.rb
  Library/Homebrew/keg_relocate.rb
  Library/Homebrew/test/global_spec.rb
  bin/brew
Labels: TSC, bug

#10041 Documentation: Fixing xcode-select --switch command line option
  Library/Homebrew/brew.sh
  Library/Homebrew/extend/os/mac/diagnostic.rb
  Library/Homebrew/shims/mac/super/xcrun
Labels: critical

#10045 Remove basic authentication support for GitHub.
  Library/Homebrew/dev-cmd/pr-pull.rb
  Library/Homebrew/utils/github.rb
Labels: critical

#10055 Fix GitHub search behaviour change
  Library/Homebrew/utils/github.rb
Labels: critical

#10057 utils/github: tweak search_code style.
  Library/Homebrew/utils/github.rb
Labels: critical

#10056 More deprecations
  Library/Homebrew/build_options.rb
  Library/Homebrew/cask/cmd.rb
  Library/Homebrew/cli/args.rb
  Library/Homebrew/cmd/gist-logs.rb
  Library/Homebrew/cmd/list.rb
  Library/Homebrew/cmd/outdated.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/cmd/switch.rb
  Library/Homebrew/compat.rb
  Library/Homebrew/compat/cli/parser.rb
  Library/Homebrew/compat/cli/parser.rbi
  Library/Homebrew/compat/formula.rb
  Library/Homebrew/compat/formula.rbi
  Library/Homebrew/compat/global.rb
  Library/Homebrew/compat/global.rbi
  Library/Homebrew/compat/language/haskell.rb
  Library/Homebrew/dev-cmd/diy.rb
  Library/Homebrew/dev-cmd/pr-pull.rb
  Library/Homebrew/env_config.rb
  Library/Homebrew/extend/ENV/std.rb
  Library/Homebrew/extend/ENV/super.rb
  Library/Homebrew/extend/os/mac/requirements/java_requirement.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/requirements/java_requirement.rb
  Library/Homebrew/tab.rb
  Library/Homebrew/test/cask/cmd_spec.rb
  Library/Homebrew/test/cmd/cask_spec.rb
  Library/Homebrew/utils/git.rb
  Library/Homebrew/utils/github.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10058 formula_installer: exclude more from build-from-source warning.
  Library/Homebrew/formula_installer.rb
Labels: critical

#10059 pr-pull: disable --workflow flag
  Library/Homebrew/dev-cmd/pr-pull.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10061 Hide `parser` warning.
  Library/Homebrew/style.rb
Labels: critical

#10066 Systemcommand: Add debug option
  Library/Homebrew/system_command.rb
Labels: critical

#10067 Fix `sudo` prompt.
  Library/Homebrew/system_command.rb
  Library/Homebrew/test/system_command_spec.rb
Labels: critical

#10069 Curl: Add optional debug and retry parameters
  Library/Homebrew/test/utils/curl_spec.rb
  Library/Homebrew/utils/curl.rb
Labels: critical

#10053 shared_audits: add xit to GITHUB_PRERELEASE_ALLOWLIST
  Library/Homebrew/utils/shared_audits.rb
Labels: critical

#10074 upgrade: fix style in help text
  Library/Homebrew/cmd/upgrade.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10073 Strategy: Temporarily remove response caching
  Library/Homebrew/livecheck/strategy.rb
Labels: critical

#10065 cli: fix underlined multi-line help text
  Library/Homebrew/cli/parser.rb
Labels: critical

#10084 Remove language/haskell
  Library/Homebrew/language/haskell.rb
Labels: critical

#10048 test: don't try to use Xcode SDK for build requirement
  Library/Homebrew/extend/os/linux/extend/ENV/std.rb
  Library/Homebrew/extend/os/linux/extend/ENV/super.rb
  Library/Homebrew/extend/os/mac/extend/ENV/std.rb
  Library/Homebrew/extend/os/mac/extend/ENV/super.rb
  Library/Homebrew/os/mac.rb
  Library/Homebrew/test.rb
Labels: critical

#10085 Fix basename for extracting cask downloads.
  Library/Homebrew/cask/artifact/pkg.rb
  Library/Homebrew/cask/download.rb
  Library/Homebrew/cask/installer.rb
Labels: critical

#10089 integration_test: fix indentation for test formulae
  Library/Homebrew/global.rb
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
  Library/Homebrew/test/utils/bottles/bottles_spec.rb
Labels: critical

#10093 install: clarify "on Intel" error if under Rosetta 2.
  Library/Homebrew/install.rb
Labels: critical

#10094 install: switch Rosetta 2/Intel messaging order.
  Library/Homebrew/install.rb
Labels: critical

#10106 Strategy: Manually handle redirections
  Library/Homebrew/livecheck/livecheck.rb
  Library/Homebrew/livecheck/strategy.rb
  Library/Homebrew/livecheck/strategy/page_match.rb
  Library/Homebrew/test/livecheck/strategy/page_match_spec.rb
Labels: critical

#10097 bottle --merge: add more write tests
  Library/Homebrew/test/dev-cmd/bottle_spec.rb
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
Labels: critical

#10087 audit: migrate shared audits to taps
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/tap_auditor.rb
  Library/Homebrew/utils/shared_audits.rb
Labels: do not merge

#10108 formula: add deprecation_date and disable_date methods
  Library/Homebrew/formula.rb
Labels: critical

#10125 Fix `Sparkle` strategy.
  Library/Homebrew/livecheck/strategy.rb
  Library/Homebrew/livecheck/strategy/page_match.rb
  Library/Homebrew/livecheck/strategy/sparkle.rb
Labels: critical

#10118 style: fix on_macos/on_linux resource block checks
  Library/Homebrew/rubocops/components_order.rb
  Library/Homebrew/test/rubocops/components_order_spec.rb
Labels: critical

#10130 bottle --merge: check for all cellars
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#10112 os/mac/sdk: parse version from SDKSettings.json
  Library/Homebrew/os/mac/sdk.rb
Labels: critical

#10132 Remove warning on ARM
  Library/Homebrew/extend/os/mac/diagnostic.rb
  Library/Homebrew/install.rb
Labels: critical

#10040 brew.sh: define minimum required Glibc version
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/vendor-install.sh
  Library/Homebrew/os/linux/glibc.rb
Labels: linux

#10133 cmd/list: Constrain `-lrt` options to formulae
  Library/Homebrew/cli/parser.rb
  Library/Homebrew/cmd/list.rb
Labels: critical

#10138 audit: fix prerelease audit
  Library/Homebrew/utils/shared_audits.rb
Labels: critical

#10141 Remove `:appcast` and rename `:cask_url` to `:url`.
  Library/Homebrew/livecheck.rb
Labels: critical

#10153 Partial revert of #10092
  Library/Homebrew/extend/os/mac/hardware.rb
Labels: critical

#10148 bottle_spec: more cleanup
  Library/Homebrew/test/dev-cmd/bottle_spec.rb
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
Labels: critical

#10159 formula_installer: only require --build-from-source on macOS.
  Library/Homebrew/cli/args.rb
  Library/Homebrew/formula_installer.rb
Labels: critical

#10160 exceptions: fix ErrorDuringExecution status.
  Library/Homebrew/exceptions.rb
Labels: critical

#10161 os/mac/hardware: clarify Rosetta 2 situation with a comment.
  Library/Homebrew/extend/os/mac/hardware.rb
Labels: critical

#10109 bump-cask-pr: ignore closed duplicate PRs
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: cask

#10162 mktemp: avoid directories with @
  Library/Homebrew/mktemp.rb
Labels: critical

#10143 PageMatch: Return fetched content in match_data
  Library/Homebrew/livecheck/livecheck.rb
  Library/Homebrew/livecheck/strategy/page_match.rb
  Library/Homebrew/test/livecheck/strategy/page_match_spec.rb
Labels: critical

#10147 cli/parser: use - instead of _ in cask args
  Library/Homebrew/cli/parser.rb
  Library/Homebrew/test/cli/parser_spec.rb
  completions/bash/brew
  completions/zsh/_brew_cask
  docs/Manpage.md
  manpages/brew.1
Labels: cask

#10144 docs: add deprecate/disable/removal documentation
  docs/Deprecating-Disabling-and-Removing-Formulae.md
  docs/Formula-Cookbook.md
  docs/README.md
Labels: discussion, documentation

#10183 formula_installer: improve no-bottle error message
  Library/Homebrew/formula_installer.rb
Labels: critical

#10189 cleanup: don't do stale check when passing --prune.
  Library/Homebrew/cleanup.rb
Labels: critical

#10184 doctor: disable python symlink message
  Library/Homebrew/diagnostic.rb
Labels: linux

#10178 Documentation updates
  Library/Homebrew/dev-cmd/man.rb
  docs/Maintainer-Guidelines.md
  docs/Manpage.md
  manpages/brew.1
Labels: documentation
