Repository Homebrew/brew, pull requests merged in 2020-06, with the labels that each got.

#7674 Cask: use regex in appcast adjusted_version_stanza
  Library/Homebrew/cask/audit.rb
Labels: cask

#7606 Cask: rename appcast configuration to must_contain
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/dsl/appcast.rb
Labels: cask

#7725 Gemfile: add sorbet and sorbet-runtime
  .gitignore
  Library/Homebrew/Gemfile
Labels: gsoc-outreachy

#7686 utils/ruby.sh: update `test-ruby` (and rename to test_ruby)
  Library/Homebrew/utils/ruby.sh
Labels: enhancement

#7678 needed libraries and dynamic_elf? check using readelf.rb(patchelf gem).
  .gitignore
  Library/Homebrew/Gemfile
  Library/Homebrew/os/linux/elf.rb
  Library/Homebrew/os/linux/global.rb
Labels: do not merge, enhancement

#7779 don't warn "no interpreter found" for Shared ELF objects.
  Library/Homebrew/os/linux/elf.rb
Labels: bug

#7794 Install: permit ARM-based Macs
  Library/Homebrew/install.rb
Labels: enhancement

#7780 enable patchelf.rb when HOMEBREW_DEVELOPER is set
  Library/Homebrew/os/linux/global.rb
Labels: enhancement

#7796 Revert "Enable patchelf.rb for HOMEBREW_DEVELOPERs."
  Library/Homebrew/os/linux/global.rb
Labels: bug

#7799 mac/hardware: cpu: Use ruby-macho's Intel constant
  Library/Homebrew/extend/os/mac/hardware/cpu.rb
Labels: enhancement

#7810 OS::Mac::Version: Change 11.00 to 11.0
  Library/Homebrew/os/mac/version.rb
Labels: bug

#7789 Integrate `--cache` and `home` with cask
  Library/Homebrew/cask/cmd/--cache.rb
  Library/Homebrew/cmd/--cache.rb
  Library/Homebrew/cmd/home.rb
  Library/Homebrew/test/cmd/--cache_spec.rb
  Library/Homebrew/test/cmd/home_spec.rb
  docs/Manpage.md
  manpages/brew.1
Labels: needs response

#7797 Refactoring keg_relocate to use ELFShim#interpreter
  Library/Homebrew/extend/os/linux/keg_relocate.rb
  Library/Homebrew/os/linux/elf.rb
Labels: enhancement, linux

#7835 style: enforce ISO-8601 in deprecation date
  Library/Homebrew/rubocops.rb
  Library/Homebrew/rubocops/deprecate.rb
  Library/Homebrew/test/rubocops/deprecate_spec.rb
Labels: enhancement
