Repository Homebrew/brew, pull requests merged in 2020-09, with the labels that each got.

#7995 CPU: add ability to check for Rosetta
  Library/Homebrew/extend/os/mac/hardware/cpu.rb
  Library/Homebrew/hardware.rb
Labels: enhancement

#8541 Return standard output in `popen_write`
  Library/Homebrew/test/utils/popen_spec.rb
  Library/Homebrew/utils/popen.rb
Labels: usability

#8351 add cask pre-release check
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/utils/shared_audits.rb
Labels: cask

#8569 workflows: migrate to GitHub Container Registry.
  .github/workflows/docker.yml
  .github/workflows/tests.yml
Labels: do not merge

#8627 Add flowchart for managing ready-to-merge PRs
  .editorconfig
  docs/Diagram-Guidelines.md
  docs/Maintainer-Guidelines.md
  docs/README.md
  docs/assets/img/docs/managing-pull-requests.drawio.svg
Labels: documentation

#8688 bump-cask-pr: add support for `:latest`
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: cask

#8710 bash completion: Avoid cask deprecation warnings, learn --cask
  completions/bash/brew
Labels: cask

#8717 Strip escape codes from annotations.
  Library/Homebrew/utils/github/actions.rb
Labels: usability

#8719 Refactor `cask audit` warnings.
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/cmd/audit.rb
  Library/Homebrew/test/cask/audit_spec.rb
  Library/Homebrew/test/cask/cmd/cat_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/adobe-air.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/auto-updates.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/basic-cask.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/latest-with-auto-updates.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/pkg-without-uninstall.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/version-latest.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/with-binary.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/with-installer-manual.rb
  Library/Homebrew/test/support/fixtures/third-party/Casks/pharo.rb
Labels: cask

#8731 bump-cask-pr: fix branch name for versions with colon
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: cask

#8577 livecheck: progress bar for JSON output
  .gitignore
  Library/Homebrew/dev-cmd/livecheck.rb
  Library/Homebrew/livecheck/livecheck.rb
  Library/Homebrew/utils/tty.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/base.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/calculators/length.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/calculators/running_average.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/components.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/components/bar.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/components/percentage.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/components/rate.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/components/time.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/components/title.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/errors/invalid_progress_error.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/format.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/format/formatter.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/format/molecule.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/format/string.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/output.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/outputs/non_tty.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/outputs/null.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/outputs/tty.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/progress.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/refinements.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/refinements/enumerator.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/throttle.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/time.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/timer.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/version.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: in progress
