Repository Homebrew/brew, pull requests merged in 2020-11, with the labels that each got.

#9052 audit: deprecate requirements in core
  Library/Homebrew/rubocops/lines.rb
Labels: discussion, do not merge

#9122 bump-cask-pr: fix for casks that have multiple languages
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: cask

#9109 pr-automerge: don't automerge PRs with linux-only label
  Library/Homebrew/dev-cmd/pr-automerge.rb
Labels: linux

#9246 Fix checksum replacement in `bump-cask-pr`.
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: critical

#9248 Remove amd-power-gadget from prerelease exceptions
  Library/Homebrew/utils/shared_audits.rb
Labels: critical

#9249 dev-cmd/audit: Fix "undefined method audit_exceptions"
  Library/Homebrew/dev-cmd/audit.rb
Labels: critical

#9250 brew.sh: add missing quotes
  Library/Homebrew/brew.sh
Labels: waiting for feedback

#9251 brew.sh: remove HOMEBREW_DEVELOPER condition
  Library/Homebrew/brew.sh
Labels: waiting for feedback

#9255 python: allow multi-digit minor versions
  Library/Homebrew/language/python.rb
Labels: waiting for feedback

#9257 Skip from Saturday/Sunday to end of Monday.
  .github/workflows/triage.yml
Labels: critical

#9262 Skip review for pull requests by BrewTestBot.
  .github/workflows/triage.yml
Labels: critical

#9264 Move logic for calculating date offset into separate function.
  .github/workflows/triage.yml
Labels: critical

#9275 audit: do not check for mixed dependencies
  Library/Homebrew/formula_auditor.rb
Labels: critical

#9277 Add debug information for empty BOM error.
  Library/Homebrew/unpack_strategy/dmg.rb
Labels: critical

#9283 fix update-python-resources for formulae not in a tap
  Library/Homebrew/utils/pypi.rb
Labels: critical

#9282 Add more BOM debug information.
  Library/Homebrew/unpack_strategy/dmg.rb
Labels: critical

#9295 cmd/list: --formula is no longer a default.
  Library/Homebrew/cmd/list.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#9284 pr-pull: fix empty workflow check
  Library/Homebrew/dev-cmd/pr-pull.rb
Labels: critical

#9298 Deprecation fixes
  Library/Homebrew/cask/cmd.rb
  Library/Homebrew/cmd/info.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#9299 Add debug output of `find` command when creating BOM.
  Library/Homebrew/unpack_strategy/dmg.rb
Labels: critical

#9303 Try retrying BOM `find` command.
  Library/Homebrew/unpack_strategy/dmg.rb
Labels: critical

#9308 dev-cmd/unbottled: add new command.
  Library/Homebrew/dev-cmd/unbottled.rb
  Library/Homebrew/test/dev-cmd/unbottled_spec.rb
  completions/internal_commands_list.txt
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#9309 Work around BOM `find` bug.
  Library/Homebrew/unpack_strategy/dmg.rb
Labels: critical

#9310 bottle merge: add support for linux cellar
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/global.rb
Labels: critical

#9319 global: fix `default_prefix?` definition
  Library/Homebrew/global.rb
Labels: critical

#9322 linkage: correctly detect missing kegs.
  Library/Homebrew/keg.rb
  Library/Homebrew/linkage_checker.rb
Labels: critical

#9279 FAQ: Default installation prefix on Linux
  docs/FAQ.md
  docs/Homebrew-on-Linux.md
Labels: documentation, linux

#9337 pypi: downcase main package name
  Library/Homebrew/utils/pypi.rb
Labels: critical

#9327 os/mac/sdk: use OS::Mac.sdk_version.
  Library/Homebrew/os/mac/sdk.rb
Labels: critical

#9318 Formula cookbook: document with_env
  Library/Homebrew/utils.rb
  docs/Formula-Cookbook.md
Labels: documentation

#9351 workflows/tests: update-reset homebrew-cask-versions.
  .github/workflows/tests.yml
Labels: critical

#9330 SDK: allow SDK mismatches if major version matches
  Library/Homebrew/os/mac/sdk.rb
Labels: critical

#9348 linkage_checker: system framework links are harmless.
  Library/Homebrew/linkage_checker.rb
Labels: critical

#9352 global: add more active_support includes.
  Library/Homebrew/global.rb
Labels: critical

#9349 Add missing `require`s for `style` spec.
  Library/Homebrew/test/cask/cmd/style_spec.rb
Labels: critical

#9311 workflows/tests: split out jobs.
  .github/workflows/tests.yml
  Library/Homebrew/.simplecov
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/test/cmd/help_spec.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
  Library/Homebrew/utils/gems.rb
Labels: critical
