Repository Homebrew/brew, pull requests merged in 2020-07, with the labels that each got.

#7752 Support casks in readall
  Library/Homebrew/cmd/readall.rb
  Library/Homebrew/extend/os/linux/readall.rb
  Library/Homebrew/extend/os/readall.rb
  Library/Homebrew/readall.rb
  Library/Homebrew/test/cmd/search_spec.rb
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
  docs/Manpage.md
  manpages/brew.1
Labels: in progress

#7535 workflows/doctor: add macOS `brew doctor` CI.
  .github/workflows/doctor.yml
Labels: in progress

#7971 bottle --merge: Fix bug with cellar :any
  Library/Homebrew/dev-cmd/bottle.rb
Labels: bug

#8047 Change the default locale to C.UTF-8 on Linux
  Library/Homebrew/brew.sh
Labels: enhancement

#7970 introduce ELFShim#rpath, refactor keg_relocate to use the same. return nil on no DT_RPATH, DT_RUNPATH, DT_SONAME, PT_INTERP
  Library/Homebrew/extend/os/linux/keg_relocate.rb
  Library/Homebrew/os/linux/elf.rb
  Library/Homebrew/test/os/linux/pathname_spec.rb
Labels: enhancement

#7985 sorbet: set utils/inreplace.rb to true
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/extend/string.rb
  Library/Homebrew/sorbet/files.yaml
  Library/Homebrew/sorbet/rbi/utils/inreplace.rbi
  Library/Homebrew/test/inreplace_spec.rb
  Library/Homebrew/test/string_spec.rb
  Library/Homebrew/utils/inreplace.rb
Labels: gsoc-outreachy

#8150 Prepend cask name to cask upgrade error message
  Library/Homebrew/cask/cmd/upgrade.rb
Labels: cask
