Repository Homebrew/brew, pull requests merged in 2021-06, with the labels that each got.

#11471 software_spec: fix wrong tab being fetched when bottle isn't unique
  Library/Homebrew/software_spec.rb
Labels: critical

#11475 formula: reject only the latest head keg when cleaning up
  Library/Homebrew/formula.rb
  manpages/brew.1
Labels: critical

#11459 super: fix GCC linkage issue in Linux
  Library/Homebrew/extend/ENV/super.rb
Labels: critical

#11483 formula_auditor: add audit for elasticsearch and kibana
  Library/Homebrew/formula_auditor.rb
Labels: critical

#11500 Revert "fix(vendor-gems): redirect bundler stdout to stderr"
  Library/Homebrew/dev-cmd/vendor-gems.rb
  Library/Homebrew/utils.rb
  Library/Homebrew/utils/gems.rb
Labels: critical

#11506 rubocops: allow uses_from_macos "git"
  Library/Homebrew/rubocops/uses_from_macos.rb
Labels: critical

#11503 shims/super/cc: fix `sysroot` flag handling
  Library/Homebrew/shims/super/cc
Labels: critical

#11493 docs: add terminology to manpage
  Library/Homebrew/manpages/brew.1.md.erb
  docs/Formula-Cookbook.md
  docs/Manpage.md
  manpages/brew.1
Labels: documentation

#11510 cli/parser: allow options to be hidden
  Library/Homebrew/cli/parser.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/commands.rb
  Library/Homebrew/dev-cmd/generate-man-completions.rb
  Library/Homebrew/test/cli/parser_spec.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#11472 os/mac/keg_relocate: add fallback to default Perl version when using tab
  Library/Homebrew/extend/os/mac/keg_relocate.rb
Labels: critical

#11516 formula: improve `to_recursive_bottle_hash`
  Library/Homebrew/formula.rb
Labels: critical

#11535 Cask::Audit: Handle livecheck skip conditions
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/test/cask/audit_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/discontinued.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-skip.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/url-unversioned.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/version-latest.rb
Labels: critical

#11532 formula_installer: restrict use of Formula from Keg
  Library/Homebrew/formula_installer.rb
Labels: critical

#11540 diagnostic: hide some warnings on Apple Silicon.
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/extend/os/mac/diagnostic.rb
Labels: critical

#11544 Fix a pair of tests on Apple silicon
  Library/Homebrew/test/cask/cmd/list_spec.rb
  Library/Homebrew/test/utils/analytics_spec.rb
Labels: critical

#11559 Temporarily revert #11537.
  Library/Homebrew/extend/pathname.rb
  Library/Homebrew/language/java.rb
  Library/Homebrew/test/language/java_spec.rb
  Library/Homebrew/test/utils/path_spec.rb
  Library/Homebrew/utils.rb
  Library/Homebrew/utils/path.rb
Labels: critical

#11560 formula_installer: add fallback to use tap formula
  Library/Homebrew/formula_installer.rb
Labels: critical

#11569 release_notes: refactor/cleanup.
  Library/Homebrew/dev-cmd/release.rb
  Library/Homebrew/release_notes.rb
  Library/Homebrew/test/release_notes_spec.rb
Labels: critical

#11395 repair pubDate statement in livecheck
  Library/Homebrew/livecheck/strategy/sparkle.rb
Labels: in progress

#11592 github_spec: Fix failed test due to expired artifacts
  Library/Homebrew/test/utils/github_spec.rb
Labels: critical

#11591 typecheck: do not generate RBI file for did_you_mean
  Library/Homebrew/dev-cmd/typecheck.rb
Labels: critical

#11597 cleaner: recursively delete info `dir`s
  Library/Homebrew/cleaner.rb
Labels: critical

#11603 test/utils/github_spec: fix artifact number
  Library/Homebrew/test/utils/github_spec.rb
Labels: critical

#11600 dispatch-build-bottle: support self-hosted Linux and unified workflow
  Library/Homebrew/cli/args.rbi
  Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
Labels: critical

#11605 default_prefix: set macOS default prefix on Linux if simulating it
  Library/Homebrew/default_prefix.rb
Labels: critical

#11588 docs: fix cask doc urls to use docs.brew.sh
  Library/.rubocop.yml
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/rubocops/cask/stanza_grouping.rb
  Library/Homebrew/rubocops/cask/stanza_order.rb
  docs/Acceptable-Casks.md
  docs/Cask-Cookbook.md
  docs/FAQ.md
Labels: cask, documentation

#11612 brew: pass GITHUB_ACTIONS_HOMEBREW_MACOS_SELF_HOSTED
  bin/brew
Labels: critical

#11598 Tweak BuildPulse/`rspec-retry` logic
  .github/workflows/tests.yml
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/test/spec_helper.rb
Labels: critical

#11239 formula_auditor: don't allow `bottle :unneeded` in core.
  Library/Homebrew/formula_auditor.rb
Labels: in progress

#11624 Fix BuildPulse handling
  .github/workflows/tests.yml
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/test/utils/repology_spec.rb
  Library/Homebrew/utils/repology.rb
Labels: critical
