Repository Homebrew/brew, pull requests merged in 2021-03, with the labels that each got.

#10746 Revert "Temporarily change default Bintray domain"
  Library/Homebrew/brew.sh
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10752 download_strategy: add comment about Content-Disposition handling
  Library/Homebrew/download_strategy.rb
Labels: critical

#10725 docs/New-Maintainer-Checklist.md: remove automated steps
  docs/New-Maintainer-Checklist.md
Labels: documentation

#10761 formula_installer: fix typo in install_dependency
  Library/Homebrew/formula_installer.rb
Labels: critical

#10763 Revert "shims/mac/super: add ruby shims to set SDKROOT"
  .github/workflows/tests.yml
  Library/Homebrew/shims/mac/super/gem
  Library/Homebrew/shims/mac/super/rake
  Library/Homebrew/shims/mac/super/ruby
  Library/Homebrew/shims/scm/git
  Library/Homebrew/shims/utils.sh
Labels: critical

#10783 test/hardware/cpu_spec: add missing families
  Library/Homebrew/test/hardware/cpu_spec.rb
Labels: critical

#10787 linux/keg_relocate: patchelf dependency is conditional.
  Library/Homebrew/extend/os/linux/keg_relocate.rb
Labels: critical

#10804 development_tools: fix LLVM Clang 10+ version detection
  Library/Homebrew/development_tools.rb
Labels: critical

#10792 formula_installer: reduce dependency expansion computations
  Library/Homebrew/formula_installer.rb
Labels: critical

#10821 Don't touch PATH, GEM_HOME and GEM_PATH when testing formula
  Library/Homebrew/dev-cmd/test.rb
  Library/Homebrew/utils/gems.rb
  Library/Homebrew/utils/gems.rbi
Labels: critical

#10824 Check homepage with both browser and default user agent.
  Library/Homebrew/cask/audit.rb
Labels: critical

#10831 cask_loader: do not auto-tap in FromTapLoader
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cask/exceptions.rb
  Library/Homebrew/cli/named_args.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/test/exceptions_spec.rb
Labels: critical

#10848 README: update sponsors
  README.md
Labels: critical

#10815 formula_installer: further reduce dependency calculations
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/test/formula_installer_spec.rb
Labels: critical

#10860 Simplify package uninstallation.
  Library/Homebrew/cask/pkg.rb
  Library/Homebrew/test/cask/pkg_spec.rb
Labels: critical, security

#10857 README: update TSC, fix linting.
  README.md
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10862 download_strategy: take basename of response-content-disposition query
  Library/Homebrew/download_strategy.rb
Labels: critical

#10863 github_packages: fix HOMEBREW_BOTTLE_DOMAIN usage.
  Library/Homebrew/github_packages.rb
  Library/Homebrew/software_spec.rb
Labels: critical

#10869 Fix broken rmdir script
  Library/Homebrew/cask/pkg.rb
Labels: cask

#10856 workflows/update-manpage: fix issue
  .github/workflows/update-manpage.yml
Labels: critical

#10871 test/cask/audit_spec: add test for slashes in versions
  Library/Homebrew/test/cask/audit_spec.rb
Labels: critical

#10872 github_packages: improve metadata.
  Library/Homebrew/github_packages.rb
Labels: critical

#10879 github/workflows: YAML cleanup.
  .github/workflows/doctor.yml
  .github/workflows/triage-issues.yml
Labels: critical

#10683 bump-cask-pr: support separate downloads for Intel and ARM
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: cask

#10889 Render shell in issue templates.
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: critical

#10890 utils/popen: redirect stderr to /dev/null rather than close
  Library/Homebrew/utils/popen.rb
Labels: critical

#10891 github_packages: use skopeo.
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/github_packages.rb
Labels: critical

#10904 Remove FormulaInstaller.prevent_build_flags
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/reinstall.rb
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/formula_installer.rb
Labels: critical

#10908 Fix Cask handling in `brew deps` and `brew uses`.
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/uses.rb
Labels: critical

#10898 Ignore timeout when checking for HTTPS availability.
  Library/Homebrew/utils/curl.rb
Labels: critical

#10893 New casks should use `livecheck`.
  Library/Homebrew/cask/audit.rb
Labels: cask

#10894 Make `livecheck` audit mandatory for versioned casks.
  Library/Homebrew/cask/audit.rb
Labels: cask

#10910 cmd/upgrade: fix --dry-run
  Library/Homebrew/cmd/upgrade.rb
Labels: critical

#10922 Revert allowing timeouts for commands and downloads
  Library/Homebrew/cask/download.rb
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/extend/time.rb
  Library/Homebrew/sorbet/plugins/using.rb
  Library/Homebrew/system_command.rb
  Library/Homebrew/utils/curl.rb
Labels: critical

#10923 CurlGitHubPackagesDownloadStrategy: revert allowing timeouts
  Library/Homebrew/download_strategy.rb
Labels: critical

#10934 Revert "Fix `uninstall --force` for casks."
  Library/Homebrew/cli/named_args.rb
Labels: critical

#10949 workflows/tests: disable cask-versions audit test
  .github/workflows/tests.yml
Labels: critical

#10950 utils/gems: don't leak BUNDLE_GEMFILE
  Library/Homebrew/utils/gems.rb
Labels: critical

#10955 Fix `BundleVersion` comparison when one part is `nil`.
  Library/Homebrew/bundle_version.rb
  Library/Homebrew/test/bundle_version_spec.rb
Labels: critical

#10961 workflows: fix commit signing
  .github/workflows/sorbet.yml
  .github/workflows/spdx.yml
  .github/workflows/update-manpage.yml
  .github/workflows/vendor-gems.yml
Labels: critical

#10953 formula: make bazel write to .brew_home
  Library/Homebrew/formula.rb
  Library/Homebrew/mktemp.rb
Labels: critical

#10959 shims/super/cc: don't refurbish ld.gold args
  Library/Homebrew/shims/super/cc
Labels: bug, critical

#10962 extend/ENV: make 'passphrase' sensitive
  Library/Homebrew/extend/ENV.rb
Labels: critical

#10947 github_packages: use json_schemer gem.
  .gitignore
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/github_packages.rb
  Library/Homebrew/sorbet/rbi/todo.rbi
  Library/Homebrew/utils/gems.rb
Labels: critical

#10938 pr-upload: Fix GitHub Packages for Linux and third-party taps
  Library/Homebrew/dev-cmd/pr-upload.rb
  Library/Homebrew/github_packages.rb
Labels: bug

#10956 cask uninstall script: allow tilde expansion to '$HOME'
  Library/Homebrew/cask/artifact/abstract_artifact.rb
  Library/Homebrew/test/cask/cmd/uninstall_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/with-uninstall-script-user-relative.rb
Labels: cask

#10964 GitHub Packages tweaks
  Library/Homebrew/dev-cmd/pr-upload.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/github_packages.rb
Labels: critical

#10971 Revert "audit: check for installed empty files"
  Library/Homebrew/formula_cellar_checks.rb
Labels: critical

#10972 cask/dsl/version: remove another invalid character
  Library/Homebrew/cask/dsl/version.rb
Labels: critical

#10948 github_packages: write tab.
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/cleanup.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/pr-upload.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/extend/pathname.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/github_packages.rb
  Library/Homebrew/global.rb
  Library/Homebrew/tab.rb
  Library/Homebrew/test/tab_spec.rb
  Library/Homebrew/utils/bottles.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10979 github_packages: Translate tab.arch to OCI
  Library/Homebrew/github_packages.rb
Labels: bug, critical

#10974 Don't suggest adding unnecessary `appcast`.
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/test/cask/audit_spec.rb
Labels: cask, critical
