Repository Homebrew/brew, pull requests merged in 2021-05, with the labels that each got.

#11301 Fix `shellcheck` style errors on bash completion file
  Library/Homebrew/completions.rb
  Library/Homebrew/completions/bash.erb
  Library/Homebrew/test/completions_spec.rb
  completions/bash/brew
  manpages/brew.1
Labels: critical

#11299 compilers: add gcc-11
  Library/Homebrew/compilers.rb
  Library/Homebrew/shims/linux/super/g++-11
  Library/Homebrew/shims/linux/super/gcc-11
  Library/Homebrew/shims/mac/super/g++-11
  Library/Homebrew/shims/mac/super/gcc-11
  Library/Homebrew/shims/super/g++-11
  Library/Homebrew/shims/super/gcc-11
Labels: critical

#11303 docs/Formula-Cookbook: Fix outdated HEAD hash syntax
  docs/Formula-Cookbook.md
Labels: critical

#11307 extend/pathname: limit `write` override to a refinement
  Library/Homebrew/build.rb
  Library/Homebrew/dev-cmd/extract.rb
  Library/Homebrew/extend/pathname.rb
  Library/Homebrew/formula_creator.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/completions_spec.rb
  Library/Homebrew/test/dev-cmd/audit_spec.rb
  Library/Homebrew/test/formulary_spec.rb
  Library/Homebrew/test/pathname_spec.rb
  Library/Homebrew/test/tab_spec.rb
  Library/Homebrew/test/tap_spec.rb
Labels: critical

#11317 github_packages: add missing root mkpath
  Library/Homebrew/github_packages.rb
Labels: critical

#11319 workflows: rename `update-manpage` to `update-man-completions`
  .github/workflows/update-man-completions.yml
Labels: critical

#11327 docs/Common-Issues: remove Oxford comma.
  docs/Common-Issues.md
Labels: critical

#11326 cask/installer_spec: delete flaky test.
  Library/Homebrew/test/cask/installer_spec.rb
Labels: critical

#11322 bottle: properly set rebuild for new formulae
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11330 utils/ruby.sh: fix Ruby path searching
  Library/Homebrew/utils/ruby.sh
Labels: critical

#11331 extend/os/mac/keg_relocate: implement `RPATH` relocation
  Library/Homebrew/extend/os/mac/keg_relocate.rb
  Library/Homebrew/os/mac/keg.rb
Labels: critical

#11342 formula_installer: set `HOMEBREW_RELOCATE_RPATHS`
  Library/Homebrew/formula_installer.rb
Labels: critical

#11354 os/mac/xcode: support Xcode 12.5
  Library/Homebrew/development_tools.rb
  Library/Homebrew/os/mac/xcode.rb
Labels: critical

#11353 dev-cmd/bump: fix empty array check
  Library/Homebrew/dev-cmd/bump.rb
Labels: critical

#11355 service: delegate more path methods
  Library/Homebrew/service.rb
Labels: critical

#11360 os/mac: use perl 5.18 on Catalina
  Library/Homebrew/os/mac.rb
Labels: critical

#11361 system_command: fix rare scenario of interrupt being reported to stderr
  Library/Homebrew/system_command.rb
Labels: critical

#11375 extend/os/mac/keg_relocate: fix post-bottling dylib ID relocation
  Library/Homebrew/extend/os/mac/keg_relocate.rb
Labels: critical

#11388 utils/pypi: use `opt_bin` for pipgrip
  Library/Homebrew/utils/pypi.rb
Labels: critical

#11392 extend/os/mac/keg_relocate: fix relocation of duplicate `RPATH`s
  Library/Homebrew/extend/os/mac/keg_relocate.rb
Labels: critical

#11376 docs: update maintainer guidelines
  docs/Homebrew-brew-Maintainer-Guide.md
  docs/Homebrew-homebrew-cask-Maintainer-Guide.md
  docs/Homebrew-homebrew-core-Maintainer-Guide.md
  docs/Homebrew-homebrew-core-Merge-Checklist.md
  docs/Maintainer-Guidelines.md
  docs/New-Maintainer-Checklist.md
  docs/README.md
  docs/vale-styles/Homebrew/Titles.yml
Labels: documentation

#11414 dependabot: ignore updates to `actions/stale` and `dessant/lock-threads`
  .github/dependabot.yml
Labels: critical, dependencies, waiting for feedback

#11408 formula: tweak preset `pour_bottle?` symbols
  Library/Homebrew/formula.rb
  Library/Homebrew/test/formula_spec.rb
  docs/Bottles.md
Labels: critical

#11424 dev-cmd/update-maintainers: fix require
  Library/Homebrew/dev-cmd/update-maintainers.rb
Labels: critical

#11431 Fix perl shebang rewriting for `perl` formula
  Library/Homebrew/extend/os/mac/keg_relocate.rb
Labels: critical

#11438 Don't uninstall `stable` keg with `--HEAD`
  Library/Homebrew/formula.rb
  Library/Homebrew/test/formula_spec.rb
Labels: discussion

#11466 linkage_checker: add libatomic
  Library/Homebrew/extend/os/linux/linkage_checker.rb
Labels: critical

#11460 components_order: allow keg_only in on_macos/on_linux blocks
  Library/Homebrew/rubocops/components_order.rb
Labels: critical

#11454 dependency: don't merge formula and cask cache in `::expand`
  Library/Homebrew/dependency.rb
  Library/Homebrew/requirement.rb
Labels: critical
