Repository Homebrew/brew, pull requests merged in 2021-01, with the labels that each got.

#10199 Avoid unnecessary downloads in `audit`.
  Library/Homebrew/utils/curl.rb
Labels: critical

#10198 superenv: filter out /usr/local on ARM if necessary
  Library/Homebrew/shims/super/cc
Labels: superenv

#10230 Ignore `racc` gem.
  .gitignore
Labels: critical

#10224 utils/git: quieter git --version.
  Library/Homebrew/utils/git.rb
Labels: critical

#10237 rubocops/homepage: don't attempt to auto-correct an empty string.
  Library/Homebrew/rubocops/homepage.rb
Labels: critical

#10234 github/workflows: use macos-latest.
  .github/workflows/sorbet.yml
  .github/workflows/tests.yml
  .github/workflows/vendor-gems.yml
Labels: critical

#10235 Don't preprocess URL for `:header_match` strategy.
  Library/Homebrew/livecheck/livecheck.rb
Labels: critical

#10254 Docs: non-cask binaries are not overwritten by --force
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/upgrade.rb
  docs/Manpage.md
  manpages/brew.1
Labels: cask, critical, documentation

#10258 github: check token scopes even if authorized
  Library/Homebrew/utils/github.rb
Labels: critical

#10252 docs: update homebrew-pypi-poet instructions
  docs/Python-for-Formula-Authors.md
Labels: documentation

#10277 utils/ast: Loose the check for Formula class node
  Library/Homebrew/utils/ast.rb
Labels: critical

#10284 Properly pass cask options in `reinstall`.
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/reinstall.rb
Labels: critical

#10295 upgrade: show formula caveats after casks have been updated
  Library/Homebrew/cask/cmd/upgrade.rb
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/messages.rb
Labels: critical

#10304 Ignore invalid keys when reading existing `Cask::Config`.
  Library/.rubocop.yml
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/config.rb
  Library/Homebrew/cli/args.rbi
  Library/Homebrew/lazy_object.rb
Labels: critical

#10315 Cask tests: temporarily disable broken test
  Library/Homebrew/test/cask/cmd/info_spec.rb
Labels: cask, critical

#10316 Popen spec: ensure Rubocop is happy
  Library/Homebrew/test/utils/popen_spec.rb
Labels: critical

#10312 Keg: allow overwriting same-formula conflicts
  Library/Homebrew/keg.rb
Labels: critical

#10320 rubocops: permit `mirror` in OS-specific resources
  Library/Homebrew/rubocops/components_order.rb
  Library/Homebrew/test/rubocops/components_order_spec.rb
Labels: critical

#10324 dev-cmd/tap-new: fix output on newer versions of Git.
  Library/Homebrew/dev-cmd/tap-new.rb
Labels: critical

#10323 Revert "Keg: allow overwriting same-formula conflicts"
  Library/Homebrew/keg.rb
Labels: critical

#10328 cask/cmd/info_spec: remove skipped test.
  Library/Homebrew/test/cask/cmd/info_spec.rb
Labels: critical

#10327 Keg: fix alias and versioned symlink handling.
  Library/Homebrew/keg.rb
  Library/Homebrew/tab.rb
Labels: critical

#10137 Amend the governance document
  docs/Homebrew-Governance.md
Labels: documentation, vote

#10336 keg: check that alias_match_path exists before checking the `.realpath.
  Library/Homebrew/keg.rb
Labels: critical

#10337 cmd,dev-cmd: indicate multiple named args in usage banner
  Library/Homebrew/cmd/--cache.rb
  Library/Homebrew/cmd/--caskroom.rb
  Library/Homebrew/cmd/--cellar.rb
  Library/Homebrew/cmd/--env.rb
  Library/Homebrew/cmd/--prefix.rb
  Library/Homebrew/cmd/--repository.rb
  Library/Homebrew/cmd/cleanup.rb
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/desc.rb
  Library/Homebrew/cmd/fetch.rb
  Library/Homebrew/cmd/home.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/link.rb
  Library/Homebrew/cmd/list.rb
  Library/Homebrew/cmd/migrate.rb
  Library/Homebrew/cmd/missing.rb
  Library/Homebrew/cmd/options.rb
  Library/Homebrew/cmd/outdated.rb
  Library/Homebrew/cmd/pin.rb
  Library/Homebrew/cmd/postinstall.rb
  Library/Homebrew/cmd/readall.rb
  Library/Homebrew/cmd/reinstall.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/cmd/switch.rb
  Library/Homebrew/cmd/tap-info.rb
  Library/Homebrew/cmd/uninstall.rb
  Library/Homebrew/cmd/unlink.rb
  Library/Homebrew/cmd/unpin.rb
  Library/Homebrew/cmd/untap.rb
  Library/Homebrew/cmd/update-reset.sh
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/cmd/uses.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
  Library/Homebrew/dev-cmd/bump.rb
  Library/Homebrew/dev-cmd/command.rb
  Library/Homebrew/dev-cmd/edit.rb
  Library/Homebrew/dev-cmd/formula.rb
  Library/Homebrew/dev-cmd/linkage.rb
  Library/Homebrew/dev-cmd/livecheck.rb
  Library/Homebrew/dev-cmd/mirror.rb
  Library/Homebrew/dev-cmd/pr-publish.rb
  Library/Homebrew/dev-cmd/pr-pull.rb
  Library/Homebrew/dev-cmd/style.rb
  Library/Homebrew/dev-cmd/test.rb
  Library/Homebrew/dev-cmd/unbottled.rb
  Library/Homebrew/dev-cmd/unpack.rb
  Library/Homebrew/dev-cmd/update-python-resources.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10229 Generate bash completions automatically
  Library/Homebrew/cli/parser.rb
  Library/Homebrew/cmd/options.rb
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/commands.rb
  Library/Homebrew/completions.rb
  Library/Homebrew/completions/bash.erb
  Library/Homebrew/dev-cmd/man.rb
  Library/Homebrew/test/completions_spec.rb
  completions/bash/brew
  completions/internal_commands_list.txt
Labels: do not merge, in progress

#10359 completions: remove link
  completions/bash/brew
Labels: critical

#10344 Cask: audit: Do not require appcast on GitHub releases
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/test/cask/audit_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/github-with-appcast.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/github-without-appcast.rb
Labels: cask

#10333 docs: update external command documentation
  docs/External-Commands.md
Labels: documentation

#10362 Replace :x11 symbol as it is no longer available
  docs/Formula-Cookbook.md
Labels: documentation

#10361 Clarification on the use of `:optional` and `:recommended`
  docs/Formula-Cookbook.md
Labels: documentation

#10375 dev-cmd: disable when broken on Apple Silicon.
  Library/Homebrew/dev-cmd/install-bundler-gems.rb
  Library/Homebrew/dev-cmd/man.rb
  Library/Homebrew/dev-cmd/typecheck.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10385 install-bundler-gem: allow on ARM.
  Library/Homebrew/dev-cmd/install-bundler-gems.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10226 completions/zsh: add-cask-option
  completions/zsh/_brew
Labels: do not merge

#10384 exceptions: more handling of nil status.
  Library/Homebrew/exceptions.rb
Labels: critical

#10390 Fix HOMEBREW_BOOTSNAP setup
  Library/.rubocop.yml
  Library/Homebrew/homebrew_bootsnap.rb
  Library/Homebrew/load_path.rb
Labels: critical

#10395 software_spec: change BottleSpecification#checksums to return array
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/software_spec.rb
Labels: critical

#10410 completions/zsh: fix broken zsh tab completion for `brew upgrade`
  completions/zsh/_brew
Labels: critical

#10398 UX fix - Properly allow quarantine in 'upgrade'
  Library/Homebrew/cmd/upgrade.rb
Labels: critical

#10402 utils/curl: use specs when checking http content problems
  Library/Homebrew/resource_auditor.rb
  Library/Homebrew/utils/curl.rb
Labels: critical

#10400 dev-cmd/extract: Improve the usage instructions
  Library/Homebrew/cli/parser.rb
  Library/Homebrew/dev-cmd/extract.rb
  Library/Homebrew/test/cask/cmd/create_spec.rb
  Library/Homebrew/test/cask/cmd/edit_spec.rb
  Library/Homebrew/test/cask/cmd/shared_examples/requires_cask_token.rb
  Library/Homebrew/test/cli/parser_spec.rb
  completions/bash/brew
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10416 homebrew_bootsnap: fix brew tests.
  Library/Homebrew/homebrew_bootsnap.rb
Labels: critical

#10405 named_args: raise error if formula/cask is found but unreadable
  Library/Homebrew/cli/named_args.rb
Labels: critical

#10432 ENV.shared: deprecate ncurses_define
  Library/Homebrew/extend/ENV/shared.rb
Labels: critical

#10428 cask/audit: disallow new cask to have token in tap_migrations.json
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/test/cask/audit_spec.rb
Labels: cask

#10439 spec_helper: fix and improve retry logic.
  Library/.rubocop_rspec.yml
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/test/cleanup_spec.rb
  Library/Homebrew/test/spec_helper.rb
Labels: critical

#10442 Update fish completions to satisfy brew man
  completions/fish/brew.fish
Labels: critical

#10445 tests: cleanup user configuration.
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/test/cleanup_spec.rb
Labels: critical

#10447 software_spec: reverse tag/digest for new bottles.
  Library/Homebrew/software_spec.rb
  Library/Homebrew/test/software_spec_spec.rb
  Library/Homebrew/test/support/fixtures/testball_bottle_cellar.rb
Labels: critical

#10449 cellars: write tag specific cellars
  Library/.rubocop.yml
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/test/dev-cmd/bottle_spec.rb
Labels: critical

#10450 style: do not fail on sha256 lines with cellar information
  Library/Homebrew/rubocops/checksum.rb
Labels: critical

#10452 style: handle line too long for new bottle blocks
  Library/.rubocop.yml
Labels: critical

#10451 style: re-enable sha256 checks for bottle blocks
  Library/Homebrew/rubocops/checksum.rb
  Library/Homebrew/rubocops/extend/formula.rb
  Library/Homebrew/test/rubocops/checksum_spec.rb
Labels: critical

#10460 typecheck: migrate from deprecated flag.
  Library/Homebrew/dev-cmd/typecheck.rb
Labels: critical

#10455 cask/audit: error if `verified` does not match, regardless of `url`
  Library/Homebrew/cask/audit.rb
Labels: cask
