Repository Homebrew/brew, pull requests merged in 2021-02, with the labels that each got.

#10456 cask/audit: underline URLs in audit errors
  Library/Homebrew/cask/audit.rb
Labels: cask

#10469 rubocop.yml: disable Rails/RakeEnvironment
  Library/.rubocop.yml
Labels: critical

#10471 formula: require language/java.
  Library/Homebrew/formula.rb
Labels: critical

#10472 Use new issue templates.
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature.yml
Labels: critical

#10474 ISSUE_TEMPLATE/feature.yml: add missing "you".
  .github/ISSUE_TEMPLATE/feature.yml
Labels: critical

#10475 dev-cmd/prof: allow non-zero exit code.
  Library/Homebrew/dev-cmd/prof.rb
Labels: critical

#10480 homebrew_bootsnap: remove deprecated option.
  Library/Homebrew/homebrew_bootsnap.rb
Labels: critical

#10479 java: fix java_home on macOS
  Library/Homebrew/extend/os/language/java.rb
  Library/Homebrew/extend/os/mac/language/java.rb
  Library/Homebrew/language/java.rb
  Library/Homebrew/test/language/java_spec.rb
Labels: critical

#10481 bootsnap: various improvements.
  Library/.rubocop.yml
  Library/Homebrew/Gemfile
  Library/Homebrew/Gemfile.lock
  Library/Homebrew/cleanup.rb
  Library/Homebrew/env_config.rb
  Library/Homebrew/homebrew_bootsnap.rb
  Library/Homebrew/load_path.rb
  Library/Homebrew/sorbet/rbi/gems/bootsnap@1.7.0.rbi
  Library/Homebrew/sorbet/rbi/gems/msgpack@1.4.2.rbi
  Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
  Library/Homebrew/utils/fork.rb
  Library/Homebrew/vendor/bundle/bundler/setup.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10484 ISSUE_TEMPLATE/bug: tweak checkboxes.
  .github/ISSUE_TEMPLATE/bug.yml
Labels: critical

#10482 workflows/tests: set HOMEBREW_BOOTSNAP.
  .github/workflows/tests.yml
  Library/Homebrew/homebrew_bootsnap.rb
Labels: critical

#10465 cask audit: do not require description for fonts
  Library/Homebrew/cask/audit.rb
Labels: cask

#10488 Deprecate additional arch functions
  Library/Homebrew/hardware.rb
  Library/Homebrew/os/mac/architecture_list.rb
  Library/Homebrew/os/mac/mach.rb
  Library/Homebrew/utils.rb
Labels: critical

#10485 java: improve tests
  Library/Homebrew/extend/os/mac/language/java.rb
  Library/Homebrew/test/language/java_spec.rb
Labels: critical

#10487 env_config: update HOMEBREW_BOOTSNAP description.
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10497 cask/config: fix `explicit_s`
  Library/Homebrew/cask/config.rb
Labels: critical

#10490 utils/github: fix false positive API credential error
  Library/Homebrew/utils/github.rb
Labels: critical

#10499 dev-cmd/release: output blog post release notes.
  Library/Homebrew/dev-cmd/release.rb
Labels: critical

#10502 style: allow long lines for bottle digests
  Library/.rubocop.yml
Labels: critical

#10509 homebrew_bootsnap: disable on ARM.
  Library/Homebrew/homebrew_bootsnap.rb
Labels: critical

#10453 rubocops: add rubocop for old bottle syntax
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/rubocops.rb
  Library/Homebrew/rubocops/bottle.rb
  Library/Homebrew/rubocops/shared/helper_functions.rb
  Library/Homebrew/test/dev-cmd/bottle_spec.rb
  Library/Homebrew/test/rubocops/bottle/bottle_digest_indentation_spec.rb
  Library/Homebrew/test/rubocops/bottle/bottle_format_spec.rb
  Library/Homebrew/test/rubocops/bottle/bottle_order_spec.rb
  Library/Homebrew/test/rubocops/bottle/bottle_tag_indentation_spec.rb
  docs/Bottles.md
Labels: in progress

#10513 docs: add a note about the stability of python 3 formulae
  docs/Homebrew-and-Python.md
Labels: critical

#10516 workflows/vendor-gems: disable for pull requests.
  .github/workflows/vendor-gems.yml
Labels: critical

#10517 rubocops/bottle: disable bottle order check
  Library/Homebrew/rubocops/bottle.rb
  Library/Homebrew/test/rubocops/bottle/bottle_order_spec.rb
Labels: critical

#10521 untap: add missing --force switch
  Library/Homebrew/cmd/untap.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10522 bottle: write bottles in correct order
  Library/Homebrew/software_spec.rb
  Library/Homebrew/test/dev-cmd/bottle_spec.rb
Labels: critical

#10523 style: re-enable bottle order cop
  Library/Homebrew/rubocops/bottle.rb
  Library/Homebrew/test/rubocops/bottle/bottle_order_spec.rb
Labels: critical

#10527 Re-enable `vendor-gems` for pull requests.
  .github/workflows/vendor-gems.yml
Labels: critical

#10533 os/mac/diagnostic: always require dev tools on Apple Silicon
  Library/Homebrew/extend/os/mac/diagnostic.rb
Labels: critical

#10535 utils/github: Provide a better error message when users don't have any GitHub credentials set
  Library/Homebrew/utils/github.rb
Labels: critical

#10537 utils: import {ohai,puts}_stdout_or_stderr
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/utils.rb
  Library/Homebrew/vendor/bundle/bundler/setup.rb
Labels: critical

#10538 homebrew_bootsnap: fail more gracefully.
  Library/Homebrew/homebrew_bootsnap.rb
Labels: critical

#10541 Utils: fix *_stdout_or_stderr helpers
  Library/Homebrew/utils.rb
Labels: critical

#10534 workflows/doctor: fix workflow not running
  .github/workflows/doctor.yml
Labels: critical

#10565 workflows/tests: remove hadolint.
  .github/workflows/tests.yml
Labels: critical

#10566 Undeprecate ENV.O1/ENV.O0
  Library/Homebrew/extend/ENV/shared.rb
  Library/Homebrew/extend/ENV/std.rb
  Library/Homebrew/extend/ENV/super.rb
Labels: critical

#10561 on_os block: allow to contain conflicts_with
  Library/Homebrew/rubocops/components_order.rb
Labels: critical

#10590 os/mac/keg: print stderr on codesign failure
  Library/Homebrew/os/mac/keg.rb
Labels: critical

#10587 non_apple_gcc_version: Use preferred_gcc
  Library/Homebrew/development_tools.rb
Labels: bug

#10605 Gemfile.lock: update sorbet-runtime to match sorbet
  Library/Homebrew/Gemfile.lock
  Library/Homebrew/vendor/bundle/bundler/setup.rb
Labels: critical, dependencies

#10607 .github/ISSUE_TEMPLATE/{bug,feature}.yml: update syntax.
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: critical

#10614 prof: needs at least 1 argument
  Library/Homebrew/dev-cmd/prof.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10602 Acceptable-Casks.md: first pass after moving
  docs/Acceptable-Casks.md
Labels: cask, documentation

#10624 Revert ".github/ISSUE_TEMPLATE/{bug,feature}.yml: update syntax."
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: critical

#10606 cc: remove unneeded linker flag when building with GCC on Linux
  Library/Homebrew/shims/super/cc
Labels: do not merge

#10652 cc: revert change to remove linker flag
  Library/Homebrew/shims/super/cc
Labels: bug, critical

#10625 .github/ISSUE_TEMPLATE/{bug,feature}.yml: update syntax.
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: critical

#10670 download_strategy: fix nounzip strategy ignoring block
  Library/Homebrew/download_strategy.rb
Labels: critical

#10697 pr-upload: Fix a typo affecting Internet Archive
  Library/Homebrew/dev-cmd/pr-upload.rb
Labels: bug, critical

#10694 homebrew_bootsnap: require some developer tools.
  Library/Homebrew/homebrew_bootsnap.rb
Labels: critical

#10704 Revert "Enable HOMEBREW_BOOTSNAP for developers"
  Library/Homebrew/brew.sh
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#10706 Improve Bootsnap behaviour
  Library/Homebrew/homebrew_bootsnap.rb
  Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
  Library/Homebrew/utils/gems.rb
  Library/Homebrew/utils/gems.rbi
Labels: critical

#10713 workflows/update-manpage: set token.
  .github/workflows/update-manpage.yml
Labels: critical

#10637 Specify Meek STV election for PLC & Schulze Condorcet election for Project Leader
  docs/Homebrew-Governance.md
Labels: do not merge, vote

#10718 formula_assertions: add assert_true compat method
  Library/Homebrew/formula_assertions.rb
Labels: critical

#10723 formula_assertions: add assert_not_match compat
  Library/Homebrew/formula_assertions.rb
Labels: critical

#10726 utils/gems: use Gem API rather than ENV to set paths
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
  Library/Homebrew/utils/gems.rb
  Library/Homebrew/utils/rubocop.rb
Labels: critical

#10727 formula_assertions: few more compat methods
  Library/Homebrew/formula_assertions.rb
Labels: critical

#10728 download_strategy: only take basename of Content-Disposition
  Library/Homebrew/download_strategy.rb
Labels: critical

#10735 utils/gems: add installed gems to $LOAD_PATH
  Library/Homebrew/utils/gems.rb
Labels: critical

#10743 Temporarily change default Bintray domain
  Library/Homebrew/brew.sh
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical
