Repository Homebrew/brew, pull requests merged in 2021-04, with the labels that each got.

#10978 github_packages: update mediaType.
  Library/Homebrew/github_packages.rb
Labels: critical

#10985 workflows/tests: remove cask taps audit.
  .github/workflows/tests.yml
Labels: critical

#10987 Allow specifying committer for some `dev-cmd`s
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/pr-pull.rb
  Library/Homebrew/dev-cmd/pr-upload.rb
  Library/Homebrew/test/utils_spec.rb
  Library/Homebrew/utils.rb
Labels: critical

#10993 pr-pull: pass --committer to pr-upload
  Library/Homebrew/dev-cmd/pr-pull.rb
Labels: critical

#10994 pr-pull,upload: don't quote passed --committer value
  Library/Homebrew/dev-cmd/pr-pull.rb
  Library/Homebrew/dev-cmd/pr-upload.rb
Labels: critical

#10973 Implement nested `url do` API.
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/dsl.rb
  Library/Homebrew/cask/url.rb
  Library/Homebrew/cask/url.rbi
  Library/Homebrew/test/cask/audit_spec.rb
Labels: cask

#10977 GitHub Packages Tab download
  Library/Homebrew/cmd/fetch.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/github_packages.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/utils/bottles.rb
Labels: critical

#10984 cmd/vendor-install: use GitHub for portable Ruby.
  Library/Homebrew/cmd/vendor-install.sh
Labels: critical

#11002 Revert "github_packages: update mediaType."
  Library/Homebrew/github_packages.rb
Labels: critical

#10997 github_packages: Rename sh.brew.bottle.digest
  Library/Homebrew/github_packages.rb
  Library/Homebrew/software_spec.rb
Labels: critical

#10995 workflows/{sorbet,spdx}: use origin_branch with git-try-push
  .github/workflows/sorbet.yml
  .github/workflows/spdx.yml
Labels: critical

#10990 system_command: improve EOF handling
  Library/Homebrew/system_command.rb
Labels: critical

#11005 Fix `brew fetch --force` for GitHub Packages bottle tab download.
  Library/Homebrew/cmd/fetch.rb
  Library/Homebrew/software_spec.rb
Labels: critical

#11007 github_packages: set github package type annotation.
  Library/Homebrew/github_packages.rb
Labels: critical

#11009 write_image_index: Remove Docker mediaType
  Library/Homebrew/github_packages.rb
Labels: bug, critical

#11010 GitHub Packages CI upload fixes
  Library/Homebrew/dev-cmd/pr-pull.rb
  Library/Homebrew/github_packages.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#11006 utils/github/api: fix incorrect error when unauthenticated
  Library/Homebrew/utils/github/api.rb
Labels: critical

#11012 github_packages: odie on missing skopeo.
  Library/Homebrew/github_packages.rb
Labels: critical

#10514 Add Codecov GitHub Action step
  .github/codecov.yml
  .github/workflows/tests.yml
  .gitignore
  Library/Homebrew/Gemfile
  Library/Homebrew/Gemfile.lock
  Library/Homebrew/sorbet/rbi/gems/simplecov-cobertura@1.4.2.rbi
  Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/vendor/bundle/bundler/setup.rb
Labels: do not merge

#10954 Speed up `pkg` uninstallation and only call `find` on directories.
  Library/Homebrew/cask/pkg.rb
  Library/Homebrew/cask/utils/rmdir.sh
  Library/Homebrew/shims/linux/super/make
  Library/Homebrew/shims/mac/super/ruby
  Library/Homebrew/shims/mac/super/xcrun
  Library/Homebrew/shims/scm/git
  Library/Homebrew/shims/utils.sh
  Library/Homebrew/style.rb
  Library/Homebrew/test/cask/pkg_spec.rb
Labels: cask

#11014 Adjust YARD config.
  Library/Homebrew/.yardopts
  Library/Homebrew/README.md
  Library/Homebrew/yard/templates/default/docstring/html/internal.erb
  Library/Homebrew/yard/templates/default/docstring/html/private.erb
  Library/Homebrew/yard/templates/default/layout/html/footer.erb
Labels: critical

#11013 github_packages: Add sh.brew.bottle.glibc.version
  Library/Homebrew/github_packages.rb
Labels: critical

#11016 Fix audit annotations for casks.
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/cmd/audit.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/test/cask/audit_spec.rb
Labels: critical

#10958 cask install: fix APFS DMG eject to use physical disk
  Library/Homebrew/test/cask/installer_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/container-apfs-dmg.rb
  Library/Homebrew/test/support/fixtures/cask/container-apfs.dmg
  Library/Homebrew/unpack_strategy/dmg.rb
Labels: cask

#11021 OCI annotation improvements and move platform.variant
  Library/Homebrew/github_packages.rb
Labels: bug, critical

#11024 CurlGitHubPackagesDownloadStrategy: Add Accept
  Library/Homebrew/download_strategy.rb
Labels: bug, critical

#11025 CurlGitHubPackagesDownloadStrategy: Fix third-party taps
  Library/Homebrew/software_spec.rb
Labels: bug, critical

#11034 GitHub Packages cleanup
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/formula_auditor.rb
  Library/Homebrew/github_packages.rb
  Library/Homebrew/hardware.rb
  Library/Homebrew/os.rb
  Library/Homebrew/software_spec.rb
Labels: critical

#11018 acceptable casks: audacity no longer applies
  docs/Acceptable-Casks.md
Labels: cask

#11035 GHCR: Add constant OS::CI_OS_VERSION
  Library/Homebrew/formula_auditor.rb
  Library/Homebrew/github_packages.rb
  Library/Homebrew/os.rb
Labels: critical

#11036 GHCR: Use reject to remove empty hash values
  Library/Homebrew/github_packages.rb
Labels: critical

#11043 Use GITHUB_TOKEN more consistently.
  .github/workflows/sorbet.yml
  .github/workflows/spdx.yml
  .github/workflows/triage-issues.yml
  .github/workflows/triage.yml
  .github/workflows/update-manpage.yml
  .github/workflows/vendor-gems.yml
Labels: critical

#11044 dev-cmd/pr-pull: don't cherry-pick on --no-commit
  Library/Homebrew/dev-cmd/pr-pull.rb
Labels: critical

#11046 dev-cmd/bottle: fix license output.
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11048 github_packages: fix versioned bottle names.
  Library/Homebrew/github_packages.rb
  Library/Homebrew/mktemp.rb
  Library/Homebrew/software_spec.rb
Labels: critical

#11052 github_packages: fix more bulk upload errors.
  Library/Homebrew/dev-cmd/pr-upload.rb
  Library/Homebrew/github_packages.rb
Labels: critical

#11053 github_packages: fix typo.
  Library/Homebrew/github_packages.rb
Labels: critical

#11054 github_packages: remove invalid docker tag characters.
  Library/Homebrew/github_packages.rb
  Library/Homebrew/software_spec.rb
Labels: critical

#11051 debrew: make Debrew::Raise only catch uncaught exceptions
  Library/Homebrew/debrew.rb
  Library/Homebrew/formula_installer.rb
Labels: critical

#11056 github_packages: don't allow `linuxbrew-` prefix.
  Library/Homebrew/github_packages.rb
Labels: critical

#11057 More GitHub Packages bulk upload fixes
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/github_packages.rb
Labels: critical

#11058 github_packages: quiet `skopeo inspect`
  Library/Homebrew/github_packages.rb
Labels: critical

#11050 Only suggest adding `livecheck` it auto-detection fails.
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/test/cask/audit_spec.rb
Labels: critical

#11060 dev-cmd/bottle: don't fail on --keep-old with unchanged values
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/test/dev-cmd/bottle_spec.rb
Labels: critical

#11041 Supports .gz man page
  Library/Homebrew/cask/artifact/manpage.rb
  Library/Homebrew/test/cask/artifact/manpage_spec.rb
  Library/Homebrew/test/support/fixtures/cask/AppWithManpage.zip
  Library/Homebrew/test/support/fixtures/cask/Casks/with-autodetected-manpage-section.rb
Labels: cask

#11066 GHCR: Authorization bearer requires a token
  Library/Homebrew/download_strategy.rb
Labels: bug, critical

#11069 github_packages: rewrite more invalid versions.
  Library/Homebrew/github_packages.rb
Labels: critical

#11068 github_packages: fix `source` for Linuxbrew bottles.
  Library/Homebrew/github_packages.rb
Labels: critical

#11071 Fix Linuxbrew URL handling
  Library/Homebrew/github_packages.rb
  Library/Homebrew/software_spec.rb
Labels: critical

#11070 Default download to GitHub Packages
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/vendor-install.sh
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#11072 github_packages: fix "Uploaded to" organisation.
  Library/Homebrew/github_packages.rb
Labels: critical

#11078 dev-cmd/bottle: avoid outputting new default bottle domain.
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/test/dev-cmd/bottle_spec.rb
Labels: critical

#11079 formula auditor: skip uses_from_macos audit for linux-only formula
  Library/Homebrew/formula_auditor.rb
Labels: critical

#11083 github_packages: fix bottle tag handling
  Library/Homebrew/github_packages.rb
Labels: critical

#11080 dev-cmd/bottle: don't take uniq of arguments
  Library/Homebrew/cli/named_args.rb
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11081 bottle: Set date to the mtime of the bottle file
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11073 Default Homebrew on Linux to use GitHub Packages.
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/vendor-install.sh
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#11075 Deprecate, disable, delete code for next major/minor version.
  Library/Homebrew/cask/dsl/depends_on.rb
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/cask_dependent.rb
  Library/Homebrew/cli/parser.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/compat/early/download_strategy.rb
  Library/Homebrew/dependency_collector.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/mirror.rb
  Library/Homebrew/dev-cmd/release-notes.rb
  Library/Homebrew/extend/ENV/shared.rb
  Library/Homebrew/extend/ENV/std.rb
  Library/Homebrew/extend/ENV/super.rb
  Library/Homebrew/extend/os/linux/requirements/osxfuse_requirement.rb
  Library/Homebrew/extend/os/mac/requirements/osxfuse_requirement.rb
  Library/Homebrew/extend/os/mac/requirements/x11_requirement.rb
  Library/Homebrew/extend/os/requirements/osxfuse_requirement.rb
  Library/Homebrew/extend/os/requirements/x11_requirement.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_assertions.rb
  Library/Homebrew/hardware.rb
  Library/Homebrew/livecheck/livecheck.rb
  Library/Homebrew/requirements.rb
  Library/Homebrew/requirements/osxfuse_requirement.rb
  Library/Homebrew/requirements/tuntap_requirement.rb
  Library/Homebrew/requirements/x11_requirement.rb
  Library/Homebrew/resource_auditor.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/test/dev-cmd/bottle_spec.rb
  Library/Homebrew/test/formula_spec.rb
  Library/Homebrew/test/formulary_spec.rb
  Library/Homebrew/test/software_spec/bottle_spec.rb
  Library/Homebrew/test/support/fixtures/testball_bottle.rb
  Library/Homebrew/utils.rb
  Library/Homebrew/utils/github.rb
  README.md
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Bottles.md
  docs/FAQ.md
  docs/Manpage.md
  docs/New-Maintainer-Checklist.md
  manpages/brew.1
Labels: critical

#11077 Support `all: SHA256` bottles.
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/unbottled.rb
  Library/Homebrew/extend/os/mac/utils/bottles.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/test/dev-cmd/bottle_spec.rb
  Library/Homebrew/utils/bottles.rb
Labels: critical

#11087 requirements: re-add missing `macos_requirement` require.
  Library/Homebrew/requirements.rb
Labels: critical

#11089 Remove some premature `odisabled`
  Library/Homebrew/compat/early/download_strategy.rb
  Library/Homebrew/livecheck/livecheck.rb
Labels: critical

#11088 `Formula#bottle_hash`: various fixes/updates.
  Library/Homebrew/cask/cmd/info.rb
  Library/Homebrew/cask/cmd/list.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/cmd/outdated.rb
  Library/Homebrew/cmd/tap-info.rb
  Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/livecheck/livecheck.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/test/cask/cmd/list_spec.rb
  Library/Homebrew/test/cmd/outdated_spec.rb
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
  Library/Homebrew/utils/github/api.rb
Labels: critical

#11092 Fix GitHub Packages filenames.
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/software_spec.rb
Labels: critical

#11094 software_spec: remove debug statement
  Library/Homebrew/software_spec.rb
Labels: critical

#11095 completions/zsh: fix `__brew_casks()`
  Library/Homebrew/completions/zsh.erb
Labels: critical

#11093 github_packages: support --keep-old
  Library/Homebrew/dev-cmd/pr-upload.rb
  Library/Homebrew/github_packages.rb
Labels: critical

#11097 bintray: fix filename for bottle uploads
  Library/Homebrew/bintray.rb
Labels: critical

#11099 bottle: no need to set cellar anymore
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11104 dev-cmd/bottle: fix incorrect Cellar value in JSON
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11103 github_packages: safer handling of `skopeo inspect`
  Library/Homebrew/github_packages.rb
Labels: critical

#11098 Help/documentation updates
  Library/Homebrew/help.rb
  README.md
Labels: critical

#11114 formula_installer: fix version scheme not being set in the tab
  Library/Homebrew/formula_installer.rb
Labels: critical

#11115 dev-cmd/bottle: don't assume `desc` present.
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11116 software_spec: GitHub Packages/Bintray fixes.
  Library/Homebrew/software_spec.rb
Labels: critical

#11118 github_packages: handle "manifest unknown"
  Library/Homebrew/github_packages.rb
Labels: critical

#11120 Update Big Sur runner labels
  .github/workflows/doctor.yml
  Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
Labels: critical

#11126 brew.sh: remove problematic HOMEBREW_BOTTLE_DOMAIN export
  Library/Homebrew/brew.sh
Labels: critical

#11122 tap-new: fix invalid tap name message
  Library/Homebrew/dev-cmd/tap-new.rb
Labels: critical

#11130 bug.yml: update issue template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: critical

#11138 Use File.read over IO.read
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/pr-upload.rb
Labels: critical

#11145 dev-cmd/bottle: fix INSTALL_RECEIPT appearing in changed_files
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11157 software_spec: fix bottle domain fallback handling
  Library/Homebrew/formula.rb
  Library/Homebrew/resource.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/utils/bottles.rb
Labels: critical

#11146 Always take first item in `Sparkle` strategy.
  Library/Homebrew/livecheck/strategy/sparkle.rb
Labels: do not merge

#11162 brew.sh: add workaround for old auto-updates
  Library/Homebrew/brew.sh
Labels: critical

#11163 dev-cmd/bottle: revert filename in JSON to use single dash always
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11165 dev-cmd/bottle: set uid/gid.
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11166 Revert "dev-cmd/bottle: set uid/gid."
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11169 rubocops/patches: Fix quoting of the patch `url` when autocorrecting
  Library/Homebrew/rubocops/patches.rb
Labels: critical

#11171 Always take latest item in `Sparkle` strategy.
  Library/Homebrew/livecheck/strategy/sparkle.rb
Labels: critical

#11181 bump-cask-pr: add --fork-org flag
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: critical

#11170 rubocops/patches: remove autocorrection of some `url`s
  Library/Homebrew/rubocops/patches.rb
Labels: critical

#10760 rubocops/patches: GitLab patches should use .diff
  Library/Homebrew/rubocops/patches.rb
  Library/Homebrew/test/rubocops/patches_spec.rb
Labels: stale

#11192 workflows/tests: simulate macOS for `brew style homebrew-core`
  .github/workflows/tests.yml
Labels: critical

#11191 style: re-enable GitLab patch URL check
  Library/Homebrew/rubocops/patches.rb
  Library/Homebrew/test/rubocops/patches_spec.rb
Labels: critical

#11208 pod2man: use newer pod2man.
  Library/Homebrew/shims/mac/super/pod2man
Labels: critical

#11210 dev-cmd/bottle: fix libarchive installed check.
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11212 pod2man: further tweak logic.
  Library/Homebrew/shims/mac/super/pod2man
Labels: critical

#11213 shims/mac/super/pod2man: delete.
  Library/Homebrew/shims/mac/super/pod2man
Labels: critical

#11225 Fix shellcheck failures
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/casks.sh
  Library/Homebrew/cmd/formulae.sh
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/cmd/vendor-install.sh
  Library/Homebrew/dev-cmd/rubocop.sh
  Library/Homebrew/shims/mac/super/ruby
  Library/Homebrew/shims/scm/git
  Library/Homebrew/style.rb
  bin/brew
Labels: critical

#11231 Fix bump-formula-pr for taps with ssh remote url.
  Library/Homebrew/tap.rb
  Library/Homebrew/test/tap_spec.rb
Labels: critical

#11137 More official Homebrew taps
  .github/workflows/tests.yml
  Library/Homebrew/commands.rb
  Library/Homebrew/official_taps.rb
  docs/Manpage.md
  manpages/brew.1
Labels: do not merge

#11234 dev-cmd/pr-upload: fix bad args reference.
  Library/Homebrew/dev-cmd/pr-upload.rb
Labels: critical

#11235 dev-cmd/pr-upload: fix json_files handling.
  Library/Homebrew/dev-cmd/pr-upload.rb
Labels: critical

#11237 cleanup: ignore DS_Store access failures.
  Library/Homebrew/cleanup.rb
Labels: critical

#11230 Avoid “Failure while executing; `git config --replace-all homebrew.devcmdrun true` exited with 255.” error.
  Library/Homebrew/settings.rb
Labels: critical

#11251 dev-cmd/bottle: tweak tar and tar arguments.
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11241 update-reset.sh: Fix `shellcheck` style errors
  Library/Homebrew/cmd/update-reset.sh
Labels: critical

#11254 Unbottled: fix use of invalid argument
  Library/Homebrew/dev-cmd/unbottled.rb
Labels: critical

#11253 dev-cmd/bottle: use gnu-tar universally, sort entries & use PAX
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11255 Interesting-Taps-and-Forks.md: add gromgit/fuse
  docs/Interesting-Taps-and-Forks.md
Labels: critical

#11263 upgrade: fix broken dependents never being built from source
  Library/Homebrew/upgrade.rb
Labels: critical

#10329 Improve livecheck docs.
  docs/Brew-Livecheck.md
Labels: outdated, stale

#11264 unpack_strategy/zip: ensure consistent timezone management
  Library/Homebrew/extend/os/mac/unpack_strategy/zip.rb
  Library/Homebrew/unpack_strategy/zip.rb
Labels: critical

#11269 dev-cmd: add more --verbose bottle, pr-upload output.
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/pr-upload.rb
Labels: critical

#10813 Conditional formulae and casks completion for Fish
  Library/Homebrew/completions.rb
  Library/Homebrew/test/completions_spec.rb
  completions/fish/brew.fish
Labels: needs response

#11270 dev-cmd/bottle: add missing verbose puts.
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11271 dev-cmd/bottle: improve filename handling.
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11272 dev-cmd/bottle: output more filenames when verbose.
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11274 dev-cmd/bottle: fix `all` JSON filename
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11279 services: fix array being flattened
  Library/Homebrew/service.rb
  Library/Homebrew/test/service_spec.rb
Labels: critical

#11278 bottle: do not fail on missing bottle block
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/test/dev-cmd/bottle_spec.rb
Labels: critical

#11283 dev-cmd/bottle: handle empty collector tags.
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11285 dev-cmd/bottle: remove double [tag].
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#11295 formula_installer: don't require unpinning build deps when pouring.
  Library/Homebrew/formula_installer.rb
Labels: critical
