Repository Homebrew/brew, pull requests merged in 2022-06, with the labels that each got.

#12241 bump-cask-pr: bump language checksums in non-running hardware
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: cask

#13364 version: tokenize prior to freezing
  Library/Homebrew/version.rb
Labels: critical

#13365 exceptions: fix did_you_mean error in some scenarios
  Library/Homebrew/exceptions.rb
Labels: critical

#13363 named_args: handle additional cask exception
  Library/Homebrew/cli/named_args.rb
Labels: critical

#13369 cask/quarantine: fix quarantine not working under some setups
  Library/Homebrew/cask/quarantine.rb
Labels: cask, critical

#13374 software_spec: handle nil manifests_annotations.
  Library/Homebrew/software_spec.rb
Labels: critical

#13376 Portable Ruby 2.6.8_1
  Library/Homebrew/cmd/vendor-install.sh
  Library/Homebrew/vendor/portable-ruby-version
Labels: critical

#13375 cmd/update-report: use better wording when appropriate.
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/description_cache_store.rb
  Library/Homebrew/env_config.rb
  Library/Homebrew/test/cmd/update-report_spec.rb
  Library/Homebrew/test/description_cache_store_spec.rb
  Library/Homebrew/utils.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#13384 Remove download sha file from .metadata dir when uninstalling casks
  Library/Homebrew/cask/installer.rb
Labels: bug, cask

#13378 os/mac/version: remove Yosemite.
  Library/Homebrew/os/mac/version.rb
  Library/Homebrew/requirements/macos_requirement.rb
Labels: critical

#13390 Preliminary macOS 13 (Ventura) support
  Library/Homebrew/extend/os/mac/diagnostic.rb
  Library/Homebrew/os/mac/pkgconfig/13/expat.pc
  Library/Homebrew/os/mac/pkgconfig/13/libcurl.pc
  Library/Homebrew/os/mac/pkgconfig/13/libedit.pc
  Library/Homebrew/os/mac/pkgconfig/13/libexslt.pc
  Library/Homebrew/os/mac/pkgconfig/13/libffi.pc
  Library/Homebrew/os/mac/pkgconfig/13/libxml-2.0.pc
  Library/Homebrew/os/mac/pkgconfig/13/libxslt.pc
  Library/Homebrew/os/mac/pkgconfig/13/ncurses.pc
  Library/Homebrew/os/mac/pkgconfig/13/ncursesw.pc
  Library/Homebrew/os/mac/pkgconfig/13/sqlite3.pc
  Library/Homebrew/os/mac/pkgconfig/13/uuid.pc
  Library/Homebrew/os/mac/pkgconfig/13/zlib.pc
  Library/Homebrew/os/mac/version.rb
  Library/Homebrew/os/mac/xcode.rb
  Library/Homebrew/test/os/mac/pkgconfig_spec.rb
  Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.ventura.bottle.tar.gz
Labels: do not merge, critical

#13397 livecheck: update --newer-only and --quiet behavior
  Library/Homebrew/livecheck/livecheck.rb
Labels: critical

#13404 sandbox: allow file-write-setugid
  Library/Homebrew/sandbox.rb
Labels: critical

#13408 dev-cmd/extract: strip out old bottle disable reasons
  Library/Homebrew/dev-cmd/extract.rb
Labels: critical

#13419 language/node: also strip postpack
  Library/Homebrew/language/node.rb
Labels: critical

#12936 Improve consistency between Git and API formula handling
  Library/Homebrew/api.rb
  Library/Homebrew/api/bottle.rb
  Library/Homebrew/api/formula.rb
  Library/Homebrew/brew.sh
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cask/caskroom.rb
  Library/Homebrew/cask_dependent.rb
  Library/Homebrew/cli/named_args.rb
  Library/Homebrew/cmd/fetch.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/outdated.rb
  Library/Homebrew/cmd/reinstall.rb
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/dependency.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/extend/os/linux/keg_relocate.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/api/bottle_spec.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: in progress

#13437 Formulary Improvements with `HOMEBREW_INSTALL_FROM_API`
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: critical

#13439 Allow more developer commands with `HOMEBREW_INSTALL_FROM_API`
  Library/Homebrew/brew.rb
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/reinstall.rb
  Library/Homebrew/commands.rb
  Library/Homebrew/dev-cmd/unbottled.rb
Labels: critical

#13444 cask/audit: skip additional livecheck audit when cask is discontinued
  Library/Homebrew/cask/audit.rb
Labels: critical

#13445 Formula-Cookbook.md: added missing dirs
  docs/Formula-Cookbook.md
Labels: critical

#13454 livecheck: fix path to livecheck watchlist
  Library/Homebrew/dev-cmd/livecheck.rb
  Library/Homebrew/env_config.rb
Labels: bug, critical

#13456 env_config: clean up default text for `HOMEBREW_LIVECHECK_WATCHLIST`
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#13462 workflows/triage: use PAT with read:org to indentify private members
  .github/workflows/triage.yml
Labels: critical

#13346 livecheck: allow custom url in extract_plist strategy
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/dsl.rb
  Library/Homebrew/livecheck/livecheck.rb
  Library/Homebrew/livecheck/strategy/extract_plist.rb
Labels: cask

#13474 bump-formula-pr: handle url with specs hash
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
Labels: bug, critical

#13470 update-report: always write non-blank lattesttag.
  Library/Homebrew/cmd/update-report.rb
Labels: critical

#13483 Remove HOMEBREW_FORCE_BREWED_SSH
  Library/Homebrew/brew.sh
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical
