Repository Homebrew/brew, pull requests merged in 2022-08, with the labels that each got.

#13631 keg_relocate (linux): prepend `gcc/lib/current` to `RPATH` when needed
  Library/Homebrew/extend/os/linux/keg_relocate.rb
Labels: critical

#13632 pr-pull: fix typo
  Library/Homebrew/dev-cmd/pr-pull.rb
Labels: critical

#13637 official_taps: Refer to `Homebrew/homebrew-cask-versions` properly
  Library/Homebrew/official_taps.rb
Labels: critical

#13640 official_taps: Add `cask-fonts`, `cask-drivers` taps
  Library/Homebrew/official_taps.rb
Labels: critical

#13638 github/pr-pull: fix/improve parameters
  Library/Homebrew/dev-cmd/pr-pull.rb
  Library/Homebrew/utils/github.rb
Labels: critical

#13644 utils/ruby.sh: fix `HOMEBREW_USE_RUBY_FROM_PATH` on non-latest macOS
  Library/Homebrew/utils/ruby.sh
Labels: critical

#13651 pr-pull: fix check conflicts
  Library/Homebrew/dev-cmd/pr-pull.rb
Labels: critical

#13645 Add `on_{system}` methods to formula cookbook
  docs/Formula-Cookbook.md
  manpages/brew.1
Labels: documentation

#13655 pr-pull: fix PRs conflicting with themselves
  Library/Homebrew/dev-cmd/pr-pull.rb
Labels: critical

#13656 linux/keg_relocate: remove patchelf exemption
  Library/Homebrew/extend/os/linux/keg_relocate.rb
Labels: critical

#13662 update-report: reset `version_scheme` only for runtime dependents
  Library/Homebrew/cmd/update-report.rb
Labels: critical

#13669 language/python: use versioned Python name in `detected_python_shebang`
  Library/Homebrew/language/python.rb
  Library/Homebrew/test/language/python/shebang_spec.rb
Labels: critical

#13679 Remove `arch` from cask stanza ordering temporarily
  Library/Homebrew/rubocops/cask/constants/stanza.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/arch-arm-only.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/invalid/invalid-two-arch.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/multiple-versions.rb
Labels: critical

#13680 Fix `nil` handling in `arch` cask DSL
  Library/Homebrew/extend/on_system.rb
Labels: critical

#13684 dev-cmd/rubocop: use bundle check.
  Library/Homebrew/dev-cmd/rubocop.sh
Labels: critical

#13681 Add and adjust cask rubocops to handle variables
  Library/Homebrew/rubocops/cask/ast/stanza.rb
  Library/Homebrew/rubocops/cask/constants/stanza.rb
  Library/Homebrew/rubocops/cask/extend/node.rb
  Library/Homebrew/rubocops/cask/variables.rb
  Library/Homebrew/rubocops/rubocop-cask.rb
  Library/Homebrew/test/rubocops/cask/stanza_grouping_spec.rb
  Library/Homebrew/test/rubocops/cask/stanza_order_spec.rb
  Library/Homebrew/test/rubocops/cask/variables_spec.rb
Labels: critical

#13688 `bump-cask-pr`: fix `sha256` replacement with `arch`
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: critical

#13698 Refactor `on_system` rubocops for use in casks
  Library/Homebrew/rubocops/cask/on_system_conditionals.rb
  Library/Homebrew/rubocops/lines.rb
  Library/Homebrew/rubocops/rubocop-cask.rb
  Library/Homebrew/rubocops/shared/on_system_conditionals_helper.rb
  Library/Homebrew/test/rubocops/cask/on_system_conditionals_spec.rb
Labels: critical

#13683 build_environment: add proper types to dump() and fix inreplace error
  Library/Homebrew/build_environment.rb
  Library/Homebrew/cmd/--env.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/formula.rb
Labels: critical

#13695 Update `brew ls` to work when the cellar doesn't exist
  Library/Homebrew/cmd/list.rb
Labels: critical

#13708 Cask: fix signing audit checking all artifacts
  Library/Homebrew/cask/audit.rb
Labels: critical

#13711 Cask: fix signing audit using unexpected pkg method
  Library/Homebrew/cask/audit.rb
Labels: critical

#13718 Fix multi-arch cask `sha256` updates
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: critical

#13734 Gemfile: stricter Ruby version requirement
  Library/Homebrew/Gemfile
Labels: critical

#13725 formula_auditor: skip rename audit for `glib-utils`
  Library/Homebrew/formula_auditor.rb
Labels: critical

#13730 Ignore HOMEBREW_NO_CLEANUP_FORMULAE deps in `brew autoremove`
  Library/Homebrew/cleanup.rb
Labels: bug, critical

#13595 bin/brew: remove HOMEBREW_NO_ENV_FILTERING.
  bin/brew
Labels: in progress

#13742 README: add Mercedes-Benz Group.
  README.md
Labels: critical

#13739 linkage_checker: don't reinstall formula on some linkage failures
  Library/Homebrew/dev-cmd/linkage.rb
  Library/Homebrew/extend/os/linux/linkage_checker.rb
  Library/Homebrew/linkage_checker.rb
Labels: critical

#13743 Remove odisabled for 3.6.0
  Library/Homebrew/cask/dsl/version.rb
  Library/Homebrew/compat/cask.rb
  Library/Homebrew/compat/formula.rb
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
  Library/Homebrew/dev-cmd/pr-upload.rb
Labels: critical

#13740 linkage_checker: disable libcrypt.so.1 linkage
  Library/Homebrew/extend/os/linux/linkage_checker.rb
Labels: critical

#13741 linkage_checker: deprecate libnsl.so.1 linkage
  Library/Homebrew/extend/os/linux/linkage_checker.rb
Labels: critical

#13745 glibc related cleanup
  Library/Homebrew/compilers.rb
  Library/Homebrew/dependency_collector.rb
  Library/Homebrew/development_tools.rb
  Library/Homebrew/extend/os/linux/compilers.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_auditor.rb
  Library/Homebrew/github_packages.rb
  Library/Homebrew/keg_relocate.rb
  Library/Homebrew/os.rb
  Library/Homebrew/test/compiler_selector_spec.rb
  Library/Homebrew/test/formula_spec.rb
  docs/Linux-CI.md
Labels: critical

#13748 Revert "formula_auditor: skip rename audit for `glib-utils`"
  Library/Homebrew/formula_auditor.rb
Labels: critical

#13749 Include `on_{system}` blocks as stanzas in rubocop
  Library/Homebrew/rubocops/cask/ast/cask_block.rb
  Library/Homebrew/rubocops/cask/constants/stanza.rb
  Library/Homebrew/rubocops/cask/extend/node.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/multiple-versions.rb
Labels: critical

#13755 formula: try optimise `versioned_formulae_names`
  Library/Homebrew/formula.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/formula_spec.rb
Labels: critical

#13761 linux/dependency_collector: bump maximum_tree_depth.
  Library/Homebrew/extend/os/linux/dependency_collector.rb
Labels: critical

#13765 linux/diagnostic: fix `rpath` returning `nil`.
  Library/Homebrew/extend/os/linux/diagnostic.rb
  Library/Homebrew/os/linux/elf.rb
Labels: critical

#13764 diagnostic: automatically tap homebrew/core.
  Library/Homebrew/diagnostic.rb
Labels: critical

#13777 cmd/deps: return failing exit code on circular dependencies.
  Library/Homebrew/cmd/deps.rb
Labels: critical

#13776 shims/gems/rubocop: handle when `brew` isn't in PATH.
  Library/Homebrew/shims/gems/rubocop
Labels: critical

#13778 extend/os/linux: improve glibc, gcc dependency handling.
  Library/Homebrew/extend/os/linux/dependency_collector.rb
  Library/Homebrew/extend/os/linux/formula.rb
Labels: critical

#13783 util/ruby.sh: fix HOMEBREW_USE_RUBY_FROM_PATH to actually use user's PATH
  Library/Homebrew/utils/ruby.sh
Labels: critical
