Repository Homebrew/brew, pull requests merged in 2022-07, with the labels that each got.

#13503 Update `components_order` cop to check other `on_{system}` methods
  Library/Homebrew/ast_constants.rb
  Library/Homebrew/rubocops/components_order.rb
  Library/Homebrew/test/rubocops/components_order_spec.rb
  manpages/brew.1
Labels: critical

#13505 cmd/update.sh: fix race condition reporting fetch failures
  Library/Homebrew/cmd/update.sh
Labels: critical

#13496 Extend the `livecheck` DSL to work for resources
  Library/Homebrew/livecheck.rb
  Library/Homebrew/resource.rb
  Library/Homebrew/test/resource_spec.rb
Labels: gsoc-outreachy

#13517 Fix `on_{macos_version}` blocks on Linux
  Library/Homebrew/extend/on_system.rb
Labels: critical

#13538 keg: create subdirectories of `lib/lua` instead of symlinks
  Library/Homebrew/keg.rb
Labels: critical

#13545 cask/cmd/list_spec.rb: fix leaky version variable
  Library/Homebrew/test/cask/cmd/list_spec.rb
Labels: bug, critical

#13562 utils/ruby_check_version_script: fix and test.
  Library/Homebrew/test/utils/ruby_check_version_script_spec.rb
  Library/Homebrew/utils/ruby_check_version_script.rb
Labels: critical

#13552 dev-cmd/update-test: test against merge-base rather than latest master
  Library/Homebrew/dev-cmd/update-test.rb
Labels: critical

#13576 Ignore empty `patch` blocks
  Library/Homebrew/software_spec.rb
  Library/Homebrew/test/software_spec_spec.rb
Labels: critical

#13568 Add flags to superenv when building with glibc@2.13
  Library/Homebrew/extend/os/linux/extend/ENV/super.rb
  Library/Homebrew/shims/super/cc
Labels: critical

#13582 Gemfile: denote minimum Ruby
  Library/Homebrew/Gemfile
  Library/Homebrew/Gemfile.lock
Labels: critical

#13591 Add GITHUB_RUN_ATTEMPT to FILTERED_ENV
  bin/brew
Labels: critical

#13593 bin/brew: never use HOMEBREW_PATH from users.
  bin/brew
Labels: critical

#13594 bin/brew: remove GITHUB_ACTIONS_HOMEBREW_MACOS_SELF_HOSTED.
  bin/brew
Labels: critical

#13598 Allow `ignore_missing_libraries` when simulating Linux on macOS
  Library/Homebrew/formula.rb
Labels: critical

#13493 Improve `OnSystem` RuboCop
  Library/Homebrew/rubocops/lines.rb
  Library/Homebrew/rubocops/lines.rbi
  Library/Homebrew/test/rubocops/text/on_os_conditionals_spec.rb
  Library/Homebrew/test/rubocops/text/on_system_conditionals_spec.rb
Labels: do not merge

#13618 audit_glibc: Permit glibc 2.27, 2.31, or 2.35 and fix the error message
  Library/Homebrew/formula_auditor.rb
Labels: needs response, critical

#12770 formula_auditor: audit for deprecated dependencies
  Library/Homebrew/formula_auditor.rb
Labels: in progress
