Repository Homebrew/brew, pull requests merged in 2022-11, with the labels that each got.

#14072 devcontainer/on-create-command: install Sorbet.
  .devcontainer/on-create-command.sh
Labels: critical

#14074 fix: allow sparkle without a macOS version
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/dsl/depends_on.rb
Labels: critical

#14080 Fix: Sparkle audit prior to el_capitan
  Library/Homebrew/cask/audit.rb
Labels: critical

#14084 test/rubocops/formula_desc: Add some tests I should have written in 2017
  Library/Homebrew/test/rubocops/formula_desc_spec.rb
Labels: critical

#14086 sorbet/tapioca/require: make aware of platform-specific gem resolution
  Library/Homebrew/sorbet/rbi/gems/nokogiri@1.13.9.rbi
  Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
  Library/Homebrew/sorbet/rbi/parlour.rbi
  Library/Homebrew/sorbet/tapioca/require.rb
Labels: critical

#14094 Update patchelf.rb to 1.4.0
  Library/Homebrew/Gemfile.lock
  Library/Homebrew/sorbet/rbi/gems/patchelf@1.4.0.rbi
  Library/Homebrew/vendor/bundle/bundler/setup.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/cli.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/exceptions.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/helper.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/logger.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/mm.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/patcher.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/saver.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/version.rb
Labels: dependencies, critical

#14093 rubyext: align workaround with upstream
  Library/Homebrew/rubyext/rubygems/defaults/operating_system.rb
Labels: critical

#14095 dev-cmd/bottle: add --no-all-checks
  Library/Homebrew/dev-cmd/bottle.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#14096 docs: Bump various OS versions
  docs/Acceptable-Casks.md
  docs/Cask-Cookbook.md
Labels: documentation, critical

#14098 Universally apply Ruby disable options
  Library/Homebrew/brew.sh
  Library/Homebrew/dev-cmd/rubocop.sh
  Library/Homebrew/startup/config.rb
  Library/Homebrew/test/support/lib/startup/config.rb
Labels: critical

#14099 style: use HOMEBREW_RUBY_EXEC_ARGS, fix some cops erroring with empty formula body
  Library/Homebrew/dev-cmd/prof.rb
  Library/Homebrew/rubocops/class.rb
  Library/Homebrew/rubocops/components_order.rb
  Library/Homebrew/rubocops/components_redundancy.rb
  Library/Homebrew/rubocops/conflicts.rb
  Library/Homebrew/rubocops/extend/formula.rb
  Library/Homebrew/rubocops/formula_desc.rb
  Library/Homebrew/rubocops/homepage.rb
  Library/Homebrew/rubocops/lines.rb
  Library/Homebrew/rubocops/options.rb
  Library/Homebrew/rubocops/patches.rb
  Library/Homebrew/rubocops/text.rb
  Library/Homebrew/rubocops/urls.rb
  Library/Homebrew/rubocops/uses_from_macos.rb
  Library/Homebrew/style.rb
Labels: critical

#14114 minor typo fixes
  Library/Homebrew/PATH.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/linuxbrew-core-migration.rb
Labels: critical

#14115 devcontainer/on-create-command: fix Ubuntu 18.04, add debugging.
  .devcontainer/on-create-command.sh
Labels: critical

#14122 Allow multiple macOS requirements
  Library/Homebrew/requirement.rb
  Library/Homebrew/requirements/macos_requirement.rb
Labels: critical

#14127 Dockerfile: install jq.
  Dockerfile
Labels: critical

#14128 devcontainer/on-create-command: fix prebuild handling.
  .devcontainer/on-create-command.sh
Labels: critical

#14129 style: check more shell scripts.
  .devcontainer/on-create-command.sh
  Library/Homebrew/style.rb
Labels: critical

#14137 uses_from_macos: add mandoc to allowed list
  Library/Homebrew/rubocops/uses_from_macos.rb
Labels: critical

#14134 docs: Fix env variable typo
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: documentation, critical

#14139 rubydoc: fixes for output
  Library/Homebrew/cache_store.rb
  Library/Homebrew/formula.rb
Labels: critical

#14138 Fix `install` <cask> `--dry-run`
  Library/Homebrew/cask/cmd/install.rb
Labels: cask

#14140 Docs: update Cookbooks
  docs/Cask-Cookbook.md
  docs/Formula-Cookbook.md
Labels: documentation

#14147 dev-cmd/unbottled: simulate target tag
  Library/Homebrew/dev-cmd/unbottled.rb
  Library/Homebrew/hardware.rb
Labels: critical

#14159 utils/gems: use env shebang when installing gems
  Library/Homebrew/utils/gems.rb
Labels: critical

#14161 dev-cmd/bump-{cask,formula}-pr: `args.message` is before the default
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
Labels: critical

#14162 rubocop_todo: Clean up deleted paths & excludes without offenses
  Library/Homebrew/.rubocop_todo.yml
Labels: critical

#14172 workflows/doctor: use ephemeral runners
  .github/workflows/doctor.yml
Labels: critical

#14185 diagnostic: remove some checks.
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/test/diagnostic_checks_spec.rb
Labels: critical

#14163 Add cop for `OS.linux?` and `OS.mac?` usage
  Library/.rubocop.yml
  Library/Homebrew/cask/cmd/install.rb
  Library/Homebrew/cleanup.rb
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/default_prefix.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/dev-cmd/update-test.rb
  Library/Homebrew/extend/os/cleanup.rb
  Library/Homebrew/extend/os/formula_installer.rb
  Library/Homebrew/extend/os/linux/cleanup.rb
  Library/Homebrew/extend/os/linux/formula_installer.rb
  Library/Homebrew/extend/os/linux/simulate_system.rb
  Library/Homebrew/extend/os/mac/cleanup.rb
  Library/Homebrew/extend/os/mac/formula_installer.rb
  Library/Homebrew/extend/os/mac/sandbox.rb
  Library/Homebrew/extend/os/mac/simulate_system.rb
  Library/Homebrew/extend/os/sandbox.rb
  Library/Homebrew/extend/os/simulate_system.rb
  Library/Homebrew/extend/os/unpack_strategy/zip.rb
  Library/Homebrew/formula_cellar_checks.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/rubocops/all.rb
  Library/Homebrew/rubocops/platform.rb
  Library/Homebrew/sandbox.rb
  Library/Homebrew/simulate_system.rb
  Library/Homebrew/test/rubocops/platform_spec.rb
  Library/Homebrew/unpack_strategy/zip.rb
Labels: features

#14192 Dockerfile: install gpg
  Dockerfile
Labels: critical
