Repository Homebrew/brew, pull requests merged in 2022-10, with the labels that each got.

#13979 Support non-master init.defaultbranch
  Library/Homebrew/formula_auditor.rb
  Library/Homebrew/test/cmd/install_spec.rb
  Library/Homebrew/test/dev-cmd/audit_spec.rb
  Library/Homebrew/test/dev-cmd/bottle_spec.rb
  Library/Homebrew/test/download_strategies/git_spec.rb
  Library/Homebrew/test/formula_spec.rb
Labels: critical

#13912 service: use default.target on Linux
  Library/Homebrew/service.rb
  Library/Homebrew/test/service_spec.rb
Labels: critical

#13980 os/mac/xcode: require Xcode 14.1 on Ventura
  Library/Homebrew/os/mac/xcode.rb
Labels: critical

#13981 formula: fix inreplace errors not being printed
  Library/Homebrew/formula.rb
Labels: critical

#13983 update*: enforce sane symlinks setting
  Library/Homebrew/cmd/update-reset.sh
  Library/Homebrew/cmd/update.sh
Labels: critical

#13990 Simulate all OS/arch combinations in `brew readall`
  Library/Homebrew/cli/args.rbi
  Library/Homebrew/cmd/readall.rb
  Library/Homebrew/extend/os/linux/readall.rb
  Library/Homebrew/readall.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#13994 workflows: migrate from deprecated set-output
  .github/workflows/sorbet.yml
  .github/workflows/spdx.yml
  .github/workflows/sponsors-maintainers-man-completions.yml
  .github/workflows/vendor-gems.yml
Labels: critical

#13964 extend/os/mac: ensure writable file for codesign
  Library/Homebrew/extend/os/mac/keg.rb
Labels: critical

#14005 os/mac/pkgconfig/13: update for beta 9 SDK
  Library/Homebrew/os/mac/pkgconfig/13/expat.pc
  Library/Homebrew/os/mac/pkgconfig/13/libcurl.pc
  Library/Homebrew/os/mac/pkgconfig/13/libexslt.pc
  Library/Homebrew/os/mac/pkgconfig/13/libxslt.pc
  Library/Homebrew/os/mac/pkgconfig/13/sqlite3.pc
Labels: critical

#14008 Restore ARM Linux support when installing gems
  Library/Homebrew/Gemfile.lock
  Library/Homebrew/utils/gems.rb
Labels: critical

#14021 Mark macOS Ventura as supported
  Library/Homebrew/os/mac/version.rb
  docs/Installation.md
Labels: critical

#14020 Allow livecheck method in on_system blocks
  Library/Homebrew/rubocops/components_order.rb
Labels: critical

#14022 utils/gems: set SDKROOT for macOS system Ruby
  Library/Homebrew/utils/gems.rb
Labels: critical

#14024 macOS Ventura (and related) test fixes
  Library/Homebrew/test/diagnostic_checks_spec.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.arm64_ventura.bottle.tar.gz
Labels: critical

#14025 integration_test: fix Bundler deprecation.
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
Labels: critical

#14028 Ventura RC version bumps
  Library/Homebrew/extend/os/mac/diagnostic.rb
  Library/Homebrew/os/mac.rb
  Library/Homebrew/os/mac/xcode.rb
Labels: critical

#14030 Add stable checksum to the JSON API
  Library/Homebrew/formula.rb
  Library/Homebrew/formulary.rb
Labels: critical

#14039 docs: Fix minor version typo
  docs/Installation.md
Labels: documentation, critical

#14035 Support git partial clones with sparse checkouts (take 2)
  Library/Homebrew/cask/artifact/relocated.rb
  Library/Homebrew/cask/url.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/utils/git.rb
  docs/Cask-Cookbook.md
Labels: cask

#14043 os/mac/diagnostic: allow Ruby 2.6.10 on < Ventura
  Library/Homebrew/extend/os/mac/diagnostic.rb
Labels: critical

#14044 Gemfile: bump nokogiri.
  Library/Homebrew/Gemfile.lock
  Library/Homebrew/vendor/bundle/bundler/setup.rb
Labels: critical

#14041 Remove sitedir from LOAD_PATH
  Library/Homebrew/brew.sh
  Library/Homebrew/standalone/load_path.rb
  Library/Homebrew/utils/gems.rb
Labels: critical

#14046 dev-cmd/unbottled: fix --dependents erroring
  Library/Homebrew/dev-cmd/unbottled.rb
Labels: critical

#14045 dev-cmd/bump-formula-pr: allow --version for version formatting changes
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
Labels: critical

#14033 Add `--adopt` switch
  Library/Homebrew/cask/artifact/moved.rb
  Library/Homebrew/cask/cmd/install.rb
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/test/cask/artifact/app_spec.rb
Labels: cask

#14061 os/mac/xcode: do not recommend `softwareupdate` CLI
  Library/Homebrew/os/mac/xcode.rb
Labels: critical

#14062 rubocop: Deal with some TODOs for `Naming/MethodParameterName`
  Library/.rubocop.yml
Labels: critical

#14065 cask/artifact/relocated: don't evaluate URL on creation
  Library/Homebrew/cask/artifact/relocated.rb
Labels: critical

#14066 devcontainer/on-create-command: do more stuff.
  .devcontainer/on-create-command.sh
Labels: critical
