Repository Homebrew/brew, pull requests merged in 2022-12, with the labels that each got.

#14200 Dockerfile: install acl
  Dockerfile
Labels: critical

#14190 dev-cmd/bump: don't use Repology version if livecheckable
  Library/Homebrew/dev-cmd/bump.rb
Labels: critical

#14219 dev-cmd/audit: enable --[no-]signing flag for audits
  Library/Homebrew/dev-cmd/audit.rb
Labels: critical

#14222 cmd/desc: fix searching.
  Library/Homebrew/cmd/desc.rb
  Library/Homebrew/description_cache_store.rb
  Library/Homebrew/descriptions.rb
Labels: critical

#14207 Cleanup `brew prof`
  Library/Homebrew/brew.rb
Labels: bug

#14223 formula_installer: output fetching headers.
  Library/Homebrew/formula_installer.rb
Labels: critical

#14233 Homebrew-Leadership-Responsibilities: import changes.
  docs/Homebrew-Leadership-Responsibilities.md
Labels: critical

#14221 api/formula: handle JSON file corruption.
  Library/Homebrew/api/formula.rb
Labels: critical

#14236 Only use OS cop internally
  Library/.rubocop.yml
  Library/Homebrew/.rubocop.yml
Labels: bug, critical

#14240 Show casks in install not found output
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/extend/os/mac/search.rb
  Library/Homebrew/search.rb
Labels: cask, enhancement

#14255 docs: Document that casks should pass GateKeeper
  docs/Acceptable-Casks.md
Labels: critical

#14272 python: reinstate pip's `--no-binary`
  Library/Homebrew/language/python.rb
  Library/Homebrew/test/language/python/virtualenv_spec.rb
Labels: critical

#14278 Fix access to `livecheck` constants in formulae
  Library/Homebrew/formula.rb
Labels: critical

#14297 Improve minimum macOS version audit for casks
  Library/Homebrew/cask/audit.rb
Labels: critical

#14295 Comment out path args deprecation
  Library/Homebrew/dev-cmd/audit.rb
Labels: critical

#14298 cask/audit: improve sparkle minimum version audit
  Library/Homebrew/cask/audit.rb
Labels: critical

#14301 Expand `on_system` rubocops
  Library/Homebrew/rubocops/cask/on_system_conditionals.rb
  Library/Homebrew/rubocops/shared/on_system_conditionals_helper.rb
  Library/Homebrew/test/rubocops/cask/on_system_conditionals_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/with-depends-on-macos-failure.rb
Labels: critical

#14302 cask/audit: improve handling `nil` in sparkle
  Library/Homebrew/cask/audit.rb
Labels: critical

#14123 cask/artifact/abstract_uninstall: allow wildcard entries for launchctl
  Library/Homebrew/cask/artifact/abstract_uninstall.rb
  Library/Homebrew/test/cask/artifact/shared_examples/uninstall_zap.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/with-uninstall-launchctl-wildcard.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/with-zap-launchctl-wildcard.rb
Labels: in progress

#14303 Use JSON instead of `#inspect` to include cask container in API
  Library/Homebrew/cask/cask.rb
Labels: critical
