Repository Homebrew/brew, pull requests merged in 2022-09, with the labels that each got.

#13787 README: update sponsors.
  README.md
Labels: critical

#13785 utils: prefer BBEdit over TextWrangler
  Library/Homebrew/utils.rb
Labels: critical

#13784 cmd/deps: drop `--installed` requirement for `--formula`/`--cask`
  Library/Homebrew/cmd/deps.rb
Labels: critical

#13786 formula_auditor: use symbols for spec iteration
  Library/Homebrew/formula_auditor.rb
Labels: critical

#13791 resource: determine version before freezing
  Library/Homebrew/resource.rb
  Library/Homebrew/software_spec.rb
Labels: critical

#13793 resource: style tweak
  Library/Homebrew/resource.rb
Labels: critical

#13801 dev-cmd/pr-pull: avoid expensive search API calls
  Library/Homebrew/dev-cmd/pr-pull.rb
  Library/Homebrew/test/utils/github_spec.rb
  Library/Homebrew/utils/github.rb
Labels: critical

#13788 Automate sponsors updates
  .github/workflows/sorbet.yml
  .github/workflows/spdx.yml
  .github/workflows/sponsors-maintainers-man-completions.yml
  .github/workflows/vendor-gems.yml
  Library/Homebrew/dev-cmd/generate-man-completions.rb
  Library/Homebrew/dev-cmd/typecheck.rb
  Library/Homebrew/dev-cmd/update-license-data.rb
  Library/Homebrew/dev-cmd/update-maintainers.rb
  Library/Homebrew/dev-cmd/update-sponsors.rb
  Library/Homebrew/test/dev-cmd/update-sponsors_spec.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/internal_commands_list.txt
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#13799 Ignore renamed formulae when checking for unversioned formulae
  Library/Homebrew/formula_auditor.rb
Labels: bug, critical

#13802 bump-cask-pr: cleanup handling of multiple hashes
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: critical

#13805 .github/workflows: various fixes.
  .github/workflows/maintainers-man-completions.yml
  .github/workflows/spdx.yml
Labels: critical

#13790 Deprecate reading all formulae through commands
  .github/workflows/tests.yml
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cli/args.rbi
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/desc.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/cmd/options.rb
  Library/Homebrew/cmd/readall.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/cmd/tap.rb
  Library/Homebrew/cmd/uses.rb
  Library/Homebrew/description_cache_store.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
  Library/Homebrew/dev-cmd/livecheck.rb
  Library/Homebrew/dev-cmd/typecheck.rb
  Library/Homebrew/dev-cmd/unbottled.rb
  Library/Homebrew/env_config.rb
  Library/Homebrew/extend/os/linux/readall.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/readall.rb
  Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
  Library/Homebrew/tap.rb
  Library/Homebrew/test/cmd/desc_spec.rb
  Library/Homebrew/test/cmd/uses_spec.rb
  Library/Homebrew/test/description_cache_store_spec.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#13807 cmd/fetch: `--retry` with exponential backoff.
  Library/Homebrew/cmd/fetch.rb
Labels: critical

#13813 Revert "Cask: automatically add cask audits"
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/auditor.rb
  Library/Homebrew/test/cask/audit_spec.rb
Labels: critical

#13812 cmd/fetch: rename `fetch_failed` to `fetch_tries`.
  Library/Homebrew/cmd/fetch.rb
Labels: critical

#13814 brew: improve Docker detection.
  Library/Homebrew/brew.rb
  Library/Homebrew/brew.sh
Labels: critical

#13815 Allow developers to use dev commands and `HOMEBREW_INSTALL_FROM_API`
  Library/Homebrew/brew.rb
Labels: critical

#13819 Add messaging for `homebrew/ubuntu16.04:master` image deprecation
  .github/workflows/tests.yml
  Library/Homebrew/brew.sh
Labels: critical

#13823 test/dev-cmd/audit_spec: use `eq` instead of `match`
  Library/Homebrew/test/dev-cmd/audit_spec.rb
Labels: critical

#13825 Prevent `require` executing some scripts (fixes `brew typecheck --update`)
  Library/Homebrew/brew.rb
  Library/Homebrew/build.rb
  Library/Homebrew/extend/os/linux/extend/pathname.rbi
  Library/Homebrew/extend/os/mac/extend/pathname.rbi
  Library/Homebrew/postinstall.rb
  Library/Homebrew/sorbet/rbi/gems/addressable@2.8.1.rbi
  Library/Homebrew/sorbet/rbi/gems/bootsnap@1.13.0.rbi
  Library/Homebrew/sorbet/rbi/gems/minitest@5.16.3.rbi
  Library/Homebrew/sorbet/rbi/gems/msgpack@1.5.6.rbi
  Library/Homebrew/sorbet/rbi/gems/nokogiri@1.13.8.rbi
  Library/Homebrew/sorbet/rbi/gems/parallel_tests@3.12.0.rbi
  Library/Homebrew/sorbet/rbi/gems/parser@3.1.2.1.rbi
  Library/Homebrew/sorbet/rbi/gems/public_suffix@5.0.0.rbi
  Library/Homebrew/sorbet/rbi/gems/rubocop-ast@1.21.0.rbi
  Library/Homebrew/sorbet/rbi/gems/rubocop@1.35.1.rbi
  Library/Homebrew/sorbet/rbi/gems/sorbet-runtime-stub@0.2.0.rbi
  Library/Homebrew/sorbet/rbi/gems/tapioca@0.7.3.rbi
  Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
  Library/Homebrew/sorbet/rbi/parlour.rbi
  Library/Homebrew/test.rb
Labels: critical

#13820 update-sponsors: don't require admin token.
  .github/workflows/sponsors-maintainers-man-completions.yml
  Library/Homebrew/dev-cmd/update-sponsors.rb
  Library/Homebrew/test/utils/github_spec.rb
  Library/Homebrew/utils/github.rb
  Library/Homebrew/utils/github/api.rb
  README.md
Labels: critical

#13829 sponsors-maintainers-man-completions: various fixes.
  .github/workflows/sponsors-maintainers-man-completions.yml
  Library/Homebrew/dev-cmd/update-sponsors.rb
  Library/Homebrew/utils/github.rb
  README.md
Labels: critical

#13832 Don't fallback to building from source with `HOMEBREW_INSTALL_FROM_API`
  Library/Homebrew/formula_installer.rb
Labels: critical

#13838 Create GCC and glibc symlinks after install is complete
  Library/Homebrew/extend/os/linux/install.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/install.rb
Labels: critical

#13840 formula_auditor: fix false positive in `audit_gcc_dependency`.
  Library/Homebrew/formula_auditor.rb
Labels: critical

#13841 cask/artifact/relocated: widen type
  Library/Homebrew/cask/artifact/relocated.rb
Labels: cask, critical

#13858 formula_auditor: disallow SSPL.
  Library/Homebrew/formula_auditor.rb
Labels: critical

#13871 Load formulae from their aliases using the API
  Library/Homebrew/api/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/formulary.rb
Labels: critical

#13842 Include `loaded_from_api` key in `Tab`
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/tab.rb
Labels: critical

#13888 formulary: fix error with absolute alias paths
  Library/Homebrew/formulary.rb
Labels: critical

#13882 Use GCC 12 for runtime libraries
  Library/Homebrew/extend/os/linux/compilers.rb
  Library/Homebrew/extend/os/linux/dependency_collector.rb
  Library/Homebrew/extend/os/linux/formula.rb
  Library/Homebrew/extend/os/linux/install.rb
  Library/Homebrew/os.rb
Labels: critical

#13833 linkage_checker: ignore broken linkage with LLVM libc++.
  Library/Homebrew/linkage_checker.rb
Labels: critical

#13889 extend/os/linux/system_config: support gcc 12 & keg-only glibc
  Library/Homebrew/extend/os/linux/system_config.rb
Labels: critical

#13873 Changes to allow keg-only glibc
  Library/Homebrew/extend/os/linux/development_tools.rb
  Library/Homebrew/extend/os/linux/install.rb
Labels: do not merge

#13899 extend/os/linux/development_tools: handle no /usr/bin/gcc
  Library/Homebrew/extend/os/linux/development_tools.rb
Labels: critical

#13895 Separate test from runtime dependencies in `Formula#to_hash`
  Library/Homebrew/formula.rb
Labels: critical

#13908 Include test deps when loading a formula from the API
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: critical

#13914 linux/keg_relocate: clean up GCC RPATH fix.
  Library/Homebrew/extend/os/linux/keg_relocate.rb
Labels: critical

#13918 formula_auditor: fix false negatives in `audit_gcc_dependency`
  Library/Homebrew/formula_auditor.rb
Labels: critical

#13926 Audit: complain if no targets are found
  Library/Homebrew/dev-cmd/audit.rb
Labels: critical

#13828 brew: remove HOMEBREW_ON_DEBIAN7
  Library/Homebrew/brew.sh
Labels: critical
