Repository Homebrew/brew, pull requests merged in 2023-05, with the labels that each got.

#15348 Fix DownloadError erroring itself
  Library/Homebrew/cask/download.rb
  Library/Homebrew/downloadable.rb
Labels: critical

#15138 Don't remove cask directories when upgrading.
  Library/Homebrew/cask/artifact/abstract_uninstall.rb
  Library/Homebrew/cask/artifact/moved.rb
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/cask/quarantine.rb
  Library/Homebrew/cask/reinstall.rb
  Library/Homebrew/cask/upgrade.rb
  Library/Homebrew/cask/utils/copy-xattrs.swift
  Library/Homebrew/test/cask/artifact/app_spec.rb
  Library/Homebrew/test/cask/upgrade_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/outdated/renamed-app.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/renamed-app.rb
  Library/Homebrew/test/support/fixtures/cask/NewApp.app/Contents/Info.plist
  Library/Homebrew/test/support/fixtures/cask/NewApp.app/Contents/MacOS/NewApp
  Library/Homebrew/test/support/fixtures/cask/NewApp.app/Contents/PkgInfo
  Library/Homebrew/test/support/fixtures/cask/NewApp.app/Contents/Resources/Caffeine.icns
  Library/Homebrew/test/support/fixtures/cask/new-app.tar.gz
  Library/Homebrew/test/support/fixtures/cask/old-app.tar.gz
Labels: cask

#15368 Revert "Enable Sorbet by default for Homebrew developers and developer commands."
  Library/Homebrew/brew.sh
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#15370 Revert "Merge pull request #15369 from carlocab/sorbet-runtime"
  Library/Homebrew/brew.sh
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#15381 utils/bottles: fix typechecking error
  Library/Homebrew/extend/os/mac/utils/bottles.rb
  Library/Homebrew/utils/bottles.rb
Labels: critical

#15385 Revert "Merge pull request #15377 from carlocab/sorbet-runtime-take2"
  Library/Homebrew/brew.sh
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#15428 simulate_system: fix `tap_syntax` job errors
  Library/Homebrew/simulate_system.rb
Labels: critical

#15438 Fix `BundleVersion` comparison.
  Library/Homebrew/bundle_version.rb
  Library/Homebrew/test/bundle_version_spec.rb
Labels: bug

#15455 formulary: use a lot more `.presence`.
  Library/Homebrew/formulary.rb
Labels: critical

#15456 service: fix API compatibility break
  Library/Homebrew/service.rb
Labels: critical

#15460 Fix failing test.
  Library/Homebrew/test/download_strategies/curl_spec.rb
  Library/Homebrew/utils/curl.rb
Labels: critical

#15458 Fix wrong token in `Cask::Migrator`.
  Library/Homebrew/cask/migrator.rb
Labels: bug

#15475 Fix wrong method in `--cache` and `fetch`.
  Library/Homebrew/cmd/--cache.rb
  Library/Homebrew/cmd/fetch.rb
Labels: bug, critical

#15498 unpack_strategy/zip: avoid loading formulae unnecessarily
  Library/Homebrew/unpack_strategy/zip.rb
Labels: critical

#15500 utils/github/api: avoid loading `gh`
  Library/Homebrew/utils/github/api.rb
Labels: critical
