Repository Homebrew/brew, pull requests merged in 2023-01, with the labels that each got.

#14313 cmd/prof: Fix gem errors
  .gitignore
  Library/Homebrew/brew.rb
  Library/Homebrew/dev-cmd/prof.rb
  Library/Homebrew/test/dev-cmd/prof_spec.rb
Labels: critical

#14323 workflows/tests: only `brew tests --online` twice.
  .github/workflows/tests.yml
Labels: critical

#14315 cli/parser: Better error message for cask on linux
  Library/Homebrew/cli/parser.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/extend/os/linux/parser.rb
  Library/Homebrew/test/cli/parser_spec.rb
Labels: bug, critical

#14324 Include `*flight` block source in cask API
  Library/Homebrew/Gemfile
  Library/Homebrew/Gemfile.lock
  Library/Homebrew/cask/artifact/abstract_flight_block.rb
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/test/cask/cask_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/conditional-flight.rb
Labels: critical

#14330 Vendor `method_source` gem
  .gitignore
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source/code_helpers.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source/source_location.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source/version.rb
Labels: critical

#14331 dev-cmd/edit: handle editing with `install_from_api`.
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/dev-cmd/edit.rb
Labels: critical

#14340 cask/installer: ensure config_path exists.
  Library/Homebrew/cask/installer.rb
Labels: critical

#14339 docs: Fixes broken link to SPDX expressions docs
  docs/License-Guidelines.md
Labels: critical

#14344 Allow --cask for linux dev cmds
  Library/Homebrew/cli/parser.rb
  Library/Homebrew/test/cli/parser_spec.rb
Labels: cask, linux

#14350 Fix `depends_on arch:` when loading casks from API
  Library/Homebrew/cask/cask_loader.rb
Labels: critical

#14359 show/check Homebrew branch
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/system_config.rb
Labels: critical

#14380 Revert "show/check Homebrew branch"
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/system_config.rb
Labels: critical

#14376 Change HOMEBREW_INSTALL_FROM_API update frequency
  Library/Homebrew/brew.sh
  Library/Homebrew/env_config.rb
  Library/Homebrew/test/env_config_spec.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#14375 Add HOMEBREW_NO_INSTALL_FROM_API
  Library/Homebrew/cmd/formulae.sh
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#14372 rubocops/caveats: Disallow ANSI escape codes
  Library/Homebrew/rubocops/caveats.rb
  Library/Homebrew/test/rubocops/caveats_spec.rb
Labels: critical

#13356 analytics: optionally duplicate to InfluxDB
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/extend/os/mac/utils/analytics.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/test/utils/analytics_spec.rb
  Library/Homebrew/utils/analytics.rb
Labels: in progress

#14389 Options: Add #to_s method
  Library/Homebrew/options.rb
  Library/Homebrew/test/options_spec.rb
Labels: critical

#14391 some needs_network specs: temporarily disable.
  Library/Homebrew/test/cmd/search_spec.rb
  Library/Homebrew/test/dev-cmd/bump_spec.rb
  Library/Homebrew/test/dev-cmd/prof_spec.rb
  Library/Homebrew/test/utils/repology_spec.rb
Labels: critical

#14397 cmd/install: fail when pkg not found
  Library/Homebrew/cmd/install.rb
Labels: critical

#14396 Add closed PR check to bump cmds
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
  Library/Homebrew/dev-cmd/bump.rb
  Library/Homebrew/utils/github.rb
Labels: critical

#14409 rubocops/lines: update hard-coded compiler check
  Library/Homebrew/rubocops/lines.rb
  Library/Homebrew/test/rubocops/text/miscellaneous_spec.rb
Labels: critical

#14407 Fix `brew search` for `HOMEBREW_INSTALL_FROM_API`
  Library/Homebrew/search.rb
  Library/Homebrew/tap.rb
Labels: critical

#14413 dev-cmd/vendor-gems: set SDKROOT for older macOS
  Library/Homebrew/dev-cmd/vendor-gems.rb
Labels: critical

#14422 HOMEBREW_INSTALL_FROM_API: various improvements.
  Library/Homebrew/brew.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/reinstall.rb
  Library/Homebrew/dev-cmd/edit.rb
  Library/Homebrew/formula_installer.rb
Labels: critical

#14423 cask_loader: fixup artifacts/caveats from JSON API.
  Library/Homebrew/cask/cask_loader.rb
Labels: critical

#14425 Improve Codespaces behaviour
  .devcontainer/on-create-command.sh
  Library/Homebrew/rubocops/files.rb
Labels: critical

#14426 extend/ENV/shared: use `try`.
  Library/Homebrew/extend/ENV/shared.rb
Labels: critical

#14432 Revert "Enable RSpec/LeakyConstantDeclaration"
  Library/.rubocop_rspec.yml
  Library/Homebrew/test/exceptions_spec.rb
  Library/Homebrew/test/formula_free_port_spec.rb
  Library/Homebrew/test/patching_spec.rb
Labels: critical

#14435 install: better error when using API and --HEAD.
  Library/Homebrew/brew.rb
  Library/Homebrew/dev-cmd/edit.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/install.rb
Labels: critical

#14434 cmd/update: tweak API update behaviour.
  Library/Homebrew/cmd/update.sh
Labels: critical

#14436 cask/artifact/stage_only: allow string argument.
  Library/Homebrew/cask/artifact/stage_only.rb
Labels: critical

#14453 Add `languages` to cask API
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/test/cask/cmd/list_spec.rb
Labels: critical, install from api

#14460 docs: Remove Lion reference
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: documentation
