Repository Homebrew/brew, pull requests merged in 2023-10, with the labels that each got.

#16077 Improve building Homebrew*.pkg
  .github/workflows/pkg-installer.yml
  Library/Homebrew/brew.sh
  package/Distribution.xml
  package/scripts/postinstall
Labels: critical

#16080 workflows/pkg-installer: fix filename.
  .github/workflows/pkg-installer.yml
  Library/Homebrew/brew.sh
Labels: critical

#16083 Revert "Version: Improve date version parsing"
  Library/Homebrew/version.rb
Labels: critical

#16088 Revert "standalone/bootsnap: relax restrictions"
  Library/Homebrew/startup/bootsnap.rb
Labels: critical

#16078 api: ignore HTTPS errors if minimum curl version isn't installed
  Library/Homebrew/api.rb
  Library/Homebrew/development_tools.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/resource.rb
Labels: install from api

#16090 standalone/bootsnap: relax restrictions
  Library/Homebrew/startup/bootsnap.rb
Labels: critical

#16091 workflows: replace `hub` with `gh`
  .github/workflows/sorbet.yml
  .github/workflows/spdx.yml
  .github/workflows/sponsors-maintainers-man-completions.yml
Labels: critical

#16094 Improve Mac package for enterprise install scenarios
  docs/Installation.md
  package/scripts/postinstall
  package/scripts/preinstall
Labels: critical

#16102 api: add `using:` attribute to head & stable URLs
  Library/Homebrew/formula.rb
  Library/Homebrew/formulary.rb
Labels: install from api

#16109 utils/gems: fix Sonoma compatibility check
  Library/Homebrew/utils/gems.rb
Labels: critical

#16111 cmd/fetch: support retrying manifest downloads
  Library/Homebrew/cmd/fetch.rb
Labels: critical

#16113 Add retries to some online audit checks
  Library/Homebrew/resource_auditor.rb
  Library/Homebrew/utils/curl.rb
Labels: critical

#16132 dev-cmd/bump-cask-pr: replace url before downloading files
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: cask

#16144 dev-cmd/pr-upload: fix gems not being installed with --upload-only
  Library/Homebrew/dev-cmd/pr-upload.rb
Labels: critical

#16151 dev-cmd/bump-formula-pr: fix specs passing under Ruby 3
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
Labels: critical

#16153 dev-cmd: fix GitHub.workflow_dispatch_event kwarg calls
  Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
  Library/Homebrew/dev-cmd/pr-publish.rb
Labels: critical

#16157 extend/kernel: fix `odisabled` kwargs handling
  Library/Homebrew/extend/kernel.rb
Labels: critical

#16150 Pull in REXML gem as it doesn't ship with Ruby 3
  Library/Homebrew/Gemfile
  Library/Homebrew/Gemfile.lock
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
  Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
  Library/Homebrew/dev-cmd/livecheck.rb
  Library/Homebrew/livecheck/strategy/sparkle.rb
  Library/Homebrew/livecheck/strategy/xml.rb
Labels: critical

#16166 README: change `labeled` to `labelled` for a consistent BE-style
  README.md
Labels: needs response

#16170 utils/gems: make `.homebrew_gem_groups` writing atomic
  Library/Homebrew/utils/gems.rb
Labels: critical

#16171 dev-cmd/audit: fix for Ruby 3
  Library/Homebrew/dev-cmd/audit.rb
Labels: critical
