Repository Homebrew/brew, pull requests merged in 2023-04, with the labels that each got.

#15120 service: handle string run cmd
  Library/Homebrew/service.rb
  Library/Homebrew/test/service_spec.rb
Labels: bug, critical, install from api

#15142 Revert "Split prof gems into their own group"
  .github/workflows/sorbet.yml
  .github/workflows/tests.yml
  Library/Homebrew/Gemfile
  Library/Homebrew/dev-cmd/install-bundler-gems.rb
  Library/Homebrew/dev-cmd/prof.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/dev-cmd/vendor-gems.rb
  Library/Homebrew/utils/gems.rb
Labels: critical

#15158 tap: remove some CoreTap installed? checks.
  Library/Homebrew/tap.rb
Labels: critical

#15205 github_runner_matrix: fix dependent runner assignment
  Library/Homebrew/github_runner_matrix.rb
Labels: critical

#15224 brew: don't filter `GITHUB_EVENT_NAME`
  bin/brew
Labels: critical

#15240 cask: remove os_versions
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/test/support/fixtures/cask/caffeine.json
  Library/Homebrew/test/support/fixtures/cask/everything.json
Labels: cask

#15247 Fix 'undefined method git_default_origin_branch?'
  Library/Homebrew/diagnostic.rb
Labels: critical

#15246 fix: fix undefined 'git_origin_branch' methods
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
  Library/Homebrew/utils/github.rb
Labels: bug, critical

#15287 dev-cmd/audit: fix audit annotations
  Library/Homebrew/dev-cmd/audit.rb
Labels: critical

#15290 formulary: sub home placeholder in caveats
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: install from api

#15300 git_repository: implement `#to_s`
  Library/Homebrew/dev-cmd/pr-pull.rb
  Library/Homebrew/git_repository.rb
Labels: critical

#15333 determine-test-runners: add debug output
  Library/Homebrew/dev-cmd/determine-test-runners.rb
  Library/Homebrew/test/dev-cmd/determine-test-runners_spec.rb
Labels: critical

#15337 rubocops/service: check for more cellar paths
  Library/Homebrew/rubocops/service.rb
  Library/Homebrew/test/rubocops/service_spec.rb
Labels: cask
