Repository Homebrew/brew, pull requests merged in 2023-02, with the labels that each got.

#14474 brew.sh: add missing dev-cmd aliases
  Library/Homebrew/brew.sh
  Library/Homebrew/commands.rb
Labels: critical

#14471 version: fix bad regexps in version parsers
  Library/Homebrew/version.rb
Labels: critical

#14480 Don't allow HOMEBREW_INSTALL_FROM_API when building from source
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/brew.rb
  Library/Homebrew/brew.sh
  Library/Homebrew/env_config.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/os.rb
  docs/Installation.md
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#14486 OS: Fix supported prefix check
  Library/Homebrew/os.rb
Labels: bug, critical

#14472 Cask loader improvements
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/tap_constants.rb
Labels: cask, critical, install from api

#14456 Support `languages` when installing from the API
  Library/Homebrew/cask/cask_loader.rb
Labels: critical, install from api

#14490 brew.sh: fix HOMEBREW_INSTALL_FROM_API logic.
  Library/Homebrew/brew.sh
Labels: critical

#14491 api: warn rather than fail if we've got a cached version.
  Library/Homebrew/api.rb
  Library/Homebrew/test/api/cask_spec.rb
Labels: critical

#14492 `Homebrew::API::fetch_file_source`: remove debug line
  Library/Homebrew/api.rb
Labels: critical

#14496 `update`: increase max time for API JSON updates
  Library/Homebrew/cmd/update.sh
Labels: critical

#14497 Fix JSON file download failure fallback
  Library/Homebrew/api.rb
Labels: critical, install from api

#14500 api/versions: remove.
  Library/Homebrew/api.rb
  Library/Homebrew/api/versions.rb
  Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
  Library/Homebrew/test/api/versions_spec.rb
Labels: critical

#14501 docs: Clarify dependency values
  docs/Formula-Cookbook.md
Labels: documentation, critical

#14506 Fix cask not found error when upgrading certain casks
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cask/installer.rb
Labels: critical

#14503 Don't convert boolean and blank values to strings in cask artifacts API
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/cask_loader.rb
Labels: critical, install from api

#14511 Fix error when showing `brew config` JSON update time
  Library/Homebrew/system_config.rb
Labels: critical

#14509 Add error message with instructions for the missing cask file
  Library/Homebrew/cask/cmd/upgrade.rb
Labels: critical, install from api

#14382 Add deprecations and disables
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/desc.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/cmd/options.rb
  Library/Homebrew/cmd/readall.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/cmd/uses.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/generate-man-completions.rb
  Library/Homebrew/dev-cmd/livecheck.rb
  Library/Homebrew/dev-cmd/typecheck.rb
  Library/Homebrew/dev-cmd/unbottled.rb
  Library/Homebrew/dev-cmd/update-license-data.rb
  Library/Homebrew/extend/os/linux/linkage_checker.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/rubocops/components_order.rb
  Library/Homebrew/test/caveats_spec.rb
  Library/Homebrew/test/formula_installer_spec.rb
  Library/Homebrew/test/formula_spec.rb
  Library/Homebrew/utils.rb
Labels: do not merge

#14412 HOMEBREW_INSTALL_FROM_API: make the default for everyone.
  .github/workflows/tests.yml
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/formulae.sh
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/env_config.rb
  docs/Installation.md
  docs/Manpage.md
  manpages/brew.1
Labels: critical, install from api

#14482 Homebrew-Governance: import merged PRs from homebrew-governance-private
  docs/Homebrew-Governance.md
  docs/New-Maintainer-Checklist.md
Labels: do not merge, critical

#14514 Adds logging to cask loader
  Library/Homebrew/cask/cask_loader.rb
Labels: cask, critical

#14515 cmd/doctor: respect `--quiet`
  Library/Homebrew/cmd/doctor.rb
Labels: critical

#14522 Properly load booleans from the API
  Library/Homebrew/cask/cask_loader.rb
Labels: critical, install from api

#14524 Set `HOMEBREW_NO_INSTALL_FROM_API` for certain commands
  Library/Homebrew/brew.rb
  Library/Homebrew/brew.sh
  Library/Homebrew/commands.rb
  Library/Homebrew/dev-cmd/edit.rb
Labels: critical, install from api

#14525 analytics: stop sending analytics in tests
  Library/Homebrew/test/utils/analytics_spec.rb
  Library/Homebrew/utils/analytics.rb
Labels: critical

#14527 Refix bash completions 1
  Library/Homebrew/completions/bash.erb
  completions/bash/brew
Labels: critical

#14534 extend/time: restore rfc3339 method
  Library/Homebrew/extend/time.rb
Labels: critical

#14523 cmd/gist-logs: On 404, the PAT probably needs more permissions
  Library/Homebrew/cmd/gist-logs.rb
  Library/Homebrew/utils/github/api.rb
Labels: critical

#14536 brew.sh: add `bump` to `HOMEBREW_NO_INSTALL_FROM_API` commands
  Library/Homebrew/brew.sh
Labels: critical

#14545 Bash completions: clean up basic functions
  Library/Homebrew/completions/bash.erb
  completions/bash/brew
Labels: critical

#14540 Bash completions: speed up Tap completions
  Library/Homebrew/completions/bash.erb
  completions/bash/brew
Labels: critical

#14543 cmd/info: generate `--json=v2` from local taps.
  Library/Homebrew/cmd/info.rb
Labels: critical

#14547 Revert "HOMEBREW_INSTALL_FROM_API: make the default for everyone."
  .github/workflows/tests.yml
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/formulae.sh
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/env_config.rb
  docs/Installation.md
  docs/Manpage.md
  manpages/brew.1
Labels: do not merge, critical

#14548 Revert "Add deprecations and disables"
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/desc.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/cmd/options.rb
  Library/Homebrew/cmd/readall.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/cmd/uses.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/generate-man-completions.rb
  Library/Homebrew/dev-cmd/livecheck.rb
  Library/Homebrew/dev-cmd/typecheck.rb
  Library/Homebrew/dev-cmd/unbottled.rb
  Library/Homebrew/dev-cmd/update-license-data.rb
  Library/Homebrew/extend/os/linux/linkage_checker.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/rubocops/components_order.rb
  Library/Homebrew/test/caveats_spec.rb
  Library/Homebrew/test/formula_installer_spec.rb
  Library/Homebrew/test/formula_spec.rb
  Library/Homebrew/utils.rb
Labels: do not merge, critical

#14554 brew.sh: declare commands that call `auto-update` as an array
  Library/Homebrew/brew.sh
Labels: critical

#14510 Pass `only` and `except` to cask audits.
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/auditor.rb
  Library/Homebrew/cask/cmd/audit.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/test/cask/audit_spec.rb
  Library/Homebrew/test/cask/cmd/audit_spec.rb
Labels: critical

#14558 README: add Mastodon link.
  README.md
Labels: critical

#14559 New-Maintainer-Checklist: clarify 1Password groups.
  docs/New-Maintainer-Checklist.md
Labels: critical

#14553 Changes for 4.0.0
  .github/workflows/tests.yml
  Library/Homebrew/brew.sh
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/desc.rb
  Library/Homebrew/cmd/formulae.sh
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/cmd/options.rb
  Library/Homebrew/cmd/readall.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/cmd/uses.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/generate-man-completions.rb
  Library/Homebrew/dev-cmd/livecheck.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/dev-cmd/typecheck.rb
  Library/Homebrew/dev-cmd/unbottled.rb
  Library/Homebrew/dev-cmd/update-license-data.rb
  Library/Homebrew/env_config.rb
  Library/Homebrew/extend/os/linux/linkage_checker.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/rubocops/components_order.rb
  Library/Homebrew/test/caveats_spec.rb
  Library/Homebrew/test/formula_installer_spec.rb
  Library/Homebrew/test/formula_spec.rb
  Library/Homebrew/utils.rb
  docs/Installation.md
  docs/Manpage.md
  manpages/brew.1
Labels: do not merge, critical

#14564 utils/github: get artifact from last run
  Library/Homebrew/utils/github.rb
Labels: critical

#14561 Tweak `version :latest` docs.
  docs/Cask-Cookbook.md
Labels: critical

#14568 increase `JSON_API_MAX_TIME`
  Library/Homebrew/api.rb
  Library/Homebrew/cmd/update.sh
Labels: critical

#14569 Ignore livecheckable casks in `bump-unversioned-casks`.
  Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
Labels: critical

#14572 Use --speed-time over --max-time for API downloads
  Library/Homebrew/api.rb
  Library/Homebrew/cmd/update.sh
Labels: critical

#14581 dev-cmd/cat: accept multiple formula/cask arguments
  Library/Homebrew/dev-cmd/cat.rb
Labels: critical

#14588 brew.sh: move shared curl speed limit settings here.
  Library/Homebrew/api.rb
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/update.sh
Labels: critical

#14589 Add HOMEBREW_API_AUTO_UPDATE_SECS
  Library/Homebrew/api.rb
  Library/Homebrew/brew.sh
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#14603 Fix duration calculation in `bump-unversioned-casks`.
  Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
Labels: bug, critical

#14601 cmd/edit: stop double warning
  Library/Homebrew/dev-cmd/edit.rb
  Library/Homebrew/utils.rb
Labels: bug, critical

#14576 extend/os: remove cask install on linux
  Library/Homebrew/cask/cmd/install.rb
  Library/Homebrew/extend/os/cask/cmd/install.rb
  Library/Homebrew/extend/os/linux/cask/cmd/install.rb
Labels: cask, critical

#14193 formula_creator: use tool-agnostic meson commands
  Library/Homebrew/formula_creator.rb
Labels: stale

#14587 Allow `brew info --json=v2` without taps with JSON API
  Library/Homebrew/api.rb
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/formula_spec.rb
  completions/zsh/_brew
Labels: critical, install from api

#14599 Bash completions: use HOMEBREW_CELLAR, if set
  Library/Homebrew/completions/bash.erb
  completions/bash/brew
Labels: critical

#14608 cask: replace Caskroom in API for relocated artifacts
  Library/Homebrew/cask/cask.rb
Labels: critical, install from api

#14596 livecheck_version: only split on commas in cask version
  Library/Homebrew/livecheck/livecheck_version.rb
  Library/Homebrew/test/livecheck/livecheck_version_spec.rb
Labels: critical

#14611 Stop including flight block source in json
  .gitignore
  Library/Homebrew/Gemfile
  Library/Homebrew/Gemfile.lock
  Library/Homebrew/cask/artifact/abstract_flight_block.rb
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/test/cask/cask_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/conditional-flight.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source/code_helpers.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source/source_location.rb
  Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source/version.rb
Labels: cask

#14613 Improve homebrew/{core,cask} autotapping.
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/env_config.rb
  Library/Homebrew/extend/os/mac/tap.rb
  Library/Homebrew/tap.rb
Labels: critical, install from api

#14618 formula: fix `to_hash` tampering with requirement names
  Library/Homebrew/formula.rb
Labels: critical, install from api

#14621 formulary: fix uses_from_macos handling on macOS
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: critical, install from api

#14617 formulary: support requirements, aliases etc from API
  Library/Homebrew/dependency_collector.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: critical, install from api

#14615 Overhaul Formula/Cask JSON generation
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cask/dsl.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/global.rb
  Library/Homebrew/test/cask/cask_spec.rb
  Library/Homebrew/test/cask/cmd/list_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/placeholders.rb
Labels: critical, install from api

#14627 cask/cask: fix non-absolute home error.
  Library/Homebrew/cask/cask.rb
Labels: critical

#14622 prefix.sh: support API mode
  Library/Homebrew/prefix.sh
Labels: critical, install from api

#14638 test/cask/cask_spec: fix test
  Library/Homebrew/test/cask/cask_spec.rb
Labels: critical

#14635 Fix analytics handling when core/cask taps are untapped
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/utils/analytics.rb
Labels: critical, install from api

#14637 formulary: fix git clone handling for API formulae
  Library/Homebrew/formulary.rb
Labels: critical, install from api

#14640 bin/brew: refine generation of `HOMEBREW_*` env vars
  bin/brew
Labels: critical

#14633 docs: no more homedir installs
  docs/Homebrew-on-Linux.md
  docs/Manpage.md
Labels: critical

#14630 Enable typing in Requirement classes
  Library/Homebrew/requirements/codesign_requirement.rb
  Library/Homebrew/requirements/macos_requirement.rb
  Library/Homebrew/requirements/xcode_requirement.rb
Labels: critical

#14628 Enable typing in Homebrew::Upgrade
  Library/Homebrew/upgrade.rb
  Library/Homebrew/upgrade.rbi
Labels: critical

#14644 env_config: reduce api_auto_update_secs.
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#14646 Further adjust `HOMEBREW_AUTO_UPDATE_SECS`
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/brew.sh
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#14648 analytics: update token.
  Library/Homebrew/utils/analytics.rb
Labels: critical

#14647 analytics: report to InfluxDB by default.
  Library/Homebrew/test/utils/analytics_spec.rb
  Library/Homebrew/utils/analytics.rb
Labels: critical

#14654 cmd/analytics: note Google Analytics differences.
  Library/Homebrew/cmd/analytics.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#14655 api: use formulae.brew.sh for cask-source API again.
  Library/Homebrew/api.rb
  Library/Homebrew/api/cask.rb
  Library/Homebrew/test/api/cask_spec.rb
  Library/Homebrew/test/api_spec.rb
Labels: critical

#14657 tap: return the default_remote if not installed.
  Library/Homebrew/tap.rb
  Library/Homebrew/test/tap_spec.rb
Labels: critical

#14658 utils/analytics: cleanup reporting.
  Library/Homebrew/utils/analytics.rb
Labels: critical

#14668 cmd/update.sh: provide full JSON URL.
  Library/Homebrew/cmd/update.sh
Labels: critical

#14669 Bash completions: warn and exit if POSIX mode detected
  Library/Homebrew/completions/bash.erb
  completions/bash/brew
Labels: critical

#14666 api: avoid unnecessary file write operation
  Library/Homebrew/api.rb
Labels: critical

#14677 test/utils/analytics_spec: fix flaky test
  Library/Homebrew/test/utils/analytics_spec.rb
Labels: critical

#14670 utils/analytics: make on_request a proper boolean.
  Library/Homebrew/utils/analytics.rb
Labels: critical

#14680 docs/FAQ: fix HOMEBREW_NO_INSTALL_FROM_API mention
  docs/FAQ.md
Labels: critical

#14678 cask: add FromAPILoader tests
  Library/Homebrew/test/cask/cask_loader/from_api_loader_spec.rb
Labels: cask, critical

#14679 formula_installer: fix resource fetching for source builds under API
  Library/Homebrew/formula_installer.rb
Labels: critical

#14672 docs/Analytics: update with post-4.0.0 info
  docs/Analytics.md
Labels: critical

#14683 cmd/--version: don't always output homebrew/core.
  Library/Homebrew/cmd/--version.sh
Labels: critical

#14660 workflows/tests: faster, more reliable tests.
  .github/workflows/tests.yml
  Library/Homebrew/.rspec_parallel
  Library/Homebrew/.simplecov
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/test/cmd/search_spec.rb
  Library/Homebrew/test/cmd/services_spec.rb
  Library/Homebrew/test/dev-cmd/bump_spec.rb
  Library/Homebrew/test/dev-cmd/prof_spec.rb
  Library/Homebrew/test/os/mac/pkgconfig_spec.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/test/support/quiet_progress_formatter.rb
  Library/Homebrew/test/utils/analytics_spec.rb
Labels: critical

#14688 workflows/tests: cache update-test's bundler.
  .github/workflows/tests.yml
Labels: critical

#14691 More tweaks to testing output and speed
  .github/workflows/tests.yml
  Library/Homebrew/.simplecov
  Library/Homebrew/dev-cmd/tests.rb
Labels: critical

#14700 workflows/tests: fix failing CI when Homebrew/core not present
  .github/workflows/tests.yml
Labels: critical

#14689 package: fix ARM name and owner of prefix
  package/scripts/postinstall
Labels: critical

#14686 Warn more when building from source
  Library/Homebrew/brew.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/reinstall.rb
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/formula_installer.rb
Labels: critical

#14684 analytics: remove UUID.
  Library/Homebrew/cmd/analytics.rb
  Library/Homebrew/utils/analytics.rb
  Library/Homebrew/utils/analytics.sh
  completions/bash/brew
  docs/Analytics.md
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#14704 Remove redundant rubocop configs
  Library/.rubocop.yml
Labels: critical

#14710 rubocop: Clean up some `Exclude`s
  Library/.rubocop.yml
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/lazy_object.rb
  Library/Homebrew/test/cask/artifact/shared_examples/uninstall_zap.rb
  Library/Homebrew/test/dev-cmd/audit_spec.rb
  Library/Homebrew/test/exceptions_spec.rb
  Library/Homebrew/test/patching_spec.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/utils/github.rb
Labels: critical

#14711 Fix permissions before moving extracted files.
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/unpack_strategy.rb
  Library/Homebrew/unpack_strategy/uncompressed.rb
Labels: critical

#14712 dev-cmd/contributions: Add `--repositories=primary` to scan only `brew,core,cask`
  Library/Homebrew/dev-cmd/contributions.rb
Labels: critical

#14702 cmd/(outdated,upgrade): Document `-g` as a shorter `--greedy` for Casks
  Library/Homebrew/cask/cmd/upgrade.rb
  Library/Homebrew/cmd/outdated.rb
Labels: critical

#14714 docs: add missing template file edits
  Library/Homebrew/completions/bash.erb
  Library/Homebrew/completions/fish.erb
  Library/Homebrew/completions/zsh.erb
  Library/Homebrew/manpages/brew.1.md.erb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#14719 formulary: use default bottle root_url.
  Library/Homebrew/formulary.rb
Labels: critical

#14727 dev-cmd/contributions: fix spacing.
  Library/Homebrew/dev-cmd/contributions.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#14725 Support `link_overwrite` and `conflicts_with` in API
  Library/Homebrew/formula.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: critical

#14729 Revert "Fix permissions before moving extracted files."
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/unpack_strategy.rb
  Library/Homebrew/unpack_strategy/uncompressed.rb
Labels: critical

#14709 rubocop: Some more config cleanup
  Library/.rubocop.yml
  Library/Homebrew/.rubocop.yml
Labels: critical

#14723 utils/gzip: set `mtime = 1` when `mtime == 0`.
  Library/Homebrew/utils/gzip.rb
Labels: critical

#14739 rubocop: Entirely disable `Metrics` cops
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/livecheck/livecheck.rb
  Library/Homebrew/rubocops/lines.rb
  Library/Homebrew/test/cask/artifact/shared_examples/uninstall_zap.rb
  Library/Homebrew/test/dev-cmd/audit_spec.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/utils/github.rb
Labels: critical

#14742 api: respect --quiet
  Library/Homebrew/api.rb
Labels: critical

#14750 rubocop.yml: disable more metrics.
  Library/.rubocop.yml
  Library/Homebrew/.rubocop.yml
Labels: critical

#14744 Ignore discontinued casks in `bump-unversioned-casks`.
  Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
Labels: critical

#14745 Look for all packages if specified packages are not found.
  Library/Homebrew/unversioned_cask_checker.rb
Labels: critical

#14743 Use `OFFICIAL_CASK_TAPS` constant.
  Library/Homebrew/diagnostic.rb
Labels: critical

#14751 utils/analytics: tweaks constants.
  Library/Homebrew/utils/analytics.rb
Labels: critical

#14740 Formula-Cookbook: update for Homebrew v4
  docs/Formula-Cookbook.md
Labels: needs response

#14747 cask: audit for correct signing of pkg installers
  Library/Homebrew/cask/audit.rb
Labels: critical

#14755 Consolidate some rubocop configurations
  Library/.rubocop.yml
  Library/.rubocop_rspec.yml
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/rubocops/all.rb
  Library/Homebrew/style.rb
Labels: critical

#14758 Don't preprocess URL for `:extract_plist` strategy.
  Library/Homebrew/livecheck/livecheck.rb
Labels: critical

#14768 dev-cmd/contributions: Correctly order the trailers method args
  Library/Homebrew/dev-cmd/contributions.rb
Labels: critical

#14770 utils/github/api: Smarter pagination in `paginate_rest`
  Library/Homebrew/utils/github/api.rb
Labels: critical

#14774 Revert "cask: audit for correct signing of pkg installers"
  Library/Homebrew/cask/audit.rb
Labels: critical

#14775 utils/github: Add date filtering to the commit author API query
  Library/Homebrew/dev-cmd/contributions.rb
  Library/Homebrew/utils/github.rb
Labels: critical

#14762 Add generate-{cask,formula}-api commands
  Library/Homebrew/brew.sh
  Library/Homebrew/dev-cmd/generate-cask-api.rb
  Library/Homebrew/dev-cmd/generate-formula-api.rb
  Library/Homebrew/test/dev-cmd/generate-cask-api_spec.rb
  Library/Homebrew/test/dev-cmd/generate-formula-api_spec.rb
Labels: critical

#14756 extend/os: clean up requires
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/dev-cmd/update-test.rb
  Library/Homebrew/extend/os/linux/dev-cmd/update-test.rb
Labels: bug, critical

#14772 CI: check for changes to autogenerated files
  .github/workflows/autogenerated-files.yml
Labels: critical

#14781 dev-cmd/generate-*-api: don't use same constant name.
  Library/Homebrew/dev-cmd/generate-cask-api.rb
  Library/Homebrew/dev-cmd/generate-formula-api.rb
Labels: critical

#14779 which_editor: remove Atom.
  Library/Homebrew/utils.rb
Labels: critical

#14782 api: don't download files as root when Homebrew's not owned by root.
  Library/Homebrew/api.rb
  Library/Homebrew/brew.rb
  Library/Homebrew/global.rb
Labels: critical

#14784 os/mac/extend/ENV/super: handle nil sdk.
  Library/Homebrew/extend/os/mac/extend/ENV/super.rb
Labels: critical

#14773 Add signatures for extraction functions.
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/unpack_strategy.rb
  Library/Homebrew/unpack_strategy/uncompressed.rb
Labels: critical

#14783 Support loading formulae/casks from subdirectories
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cmd/tap-info.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/cask/cask_loader/from_path_loader_spec.rb
  Library/Homebrew/test/cask/cask_loader/from_tap_loader_spec.rb
  Library/Homebrew/test/formulary_spec.rb
  Library/Homebrew/test/missing_formula_spec.rb
  Library/Homebrew/test/tap_spec.rb
Labels: critical

#14793 Scope `HOMEBREW_NO_INSTALL_FROM_API` to core formulae in `brew audit`
  Library/Homebrew/brew.sh
  Library/Homebrew/dev-cmd/audit.rb
Labels: critical

#14795 cask: support url specs in API
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/test/cask/cmd/list_spec.rb
Labels: critical

#14797 cmd/info: handle casks with API.
  Library/Homebrew/cmd/info.rb
Labels: critical

#14800 Fix references to `formula.json` and `cask.json`
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/system_config.rb
  docs/Formula-Cookbook.md
Labels: critical

#14801 generate-*-api: better errors
  Library/Homebrew/dev-cmd/generate-cask-api.rb
  Library/Homebrew/dev-cmd/generate-formula-api.rb
Labels: critical

#14803 cask: handle nil URLs
  Library/Homebrew/cask/cask.rb
Labels: critical

#14794 Move `HOMEBREW_NO_INSTALL_FROM_API` defaults to shell
  Library/Homebrew/brew.sh
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/untap.rb
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/default_prefix.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/env_config.rb
  Library/Homebrew/extend/os/default_prefix.rb
  Library/Homebrew/extend/os/linux/default_prefix.rb
  Library/Homebrew/extend/os/linux/diagnostic.rb
  Library/Homebrew/extend/os/mac/default_prefix.rb
  Library/Homebrew/extend/os/mac/tap.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/global.rb
  Library/Homebrew/os/mac/version.rb
  Library/Homebrew/requirements/macos_requirement.rb
  Library/Homebrew/search.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/cask/cask_loader/from_api_loader_spec.rb
Labels: critical

#14812 dev-cmd/contributions: Order the CSV by highest contributions total
  Library/Homebrew/dev-cmd/contributions.rb
Labels: critical

#14813 dev-cmd/contributions: Count PR reviews since they're super important
  Library/Homebrew/dev-cmd/contributions.rb
  Library/Homebrew/test/search_spec.rb
  Library/Homebrew/utils/github.rb
Labels: critical

#14814 Set tap for casks when loading from contents via API
  Library/Homebrew/cask/cask_loader.rb
Labels: critical

#14808 Fixed type error in 'brew audit'
  Library/Homebrew/cask/audit.rb
Labels: critical

#14816 utils/github: Tiny improvements, boolean methods end in `?` and remove unnecessary `.delete_prefix("/")`
  Library/Homebrew/utils/github.rb
Labels: critical

#14804 readall: reject casks with no URL
  Library/Homebrew/readall.rb
Labels: cask, critical

#14822 Use 'wslview' instead of 'xdg-open' on Windows
  Library/Homebrew/extend/os/linux/system_config.rb
  Library/Homebrew/os.rb
  Library/Homebrew/os/linux.rb
  Library/Homebrew/utils.rb
Labels: critical

#14824 dev-cmd/cat: improve error message.
  Library/Homebrew/dev-cmd/cat.rb
Labels: critical

#14830 Strategy#from_url: Amend conditions for Json
  Library/Homebrew/livecheck/strategy.rb
Labels: critical

#14820 Delay loading from cask source api
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cask/dsl.rb
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/test/cask/cask_loader/from_api_loader_spec.rb
  Library/Homebrew/test/cask/installer_spec.rb
Labels: cask

#14834 Allow `version :latest` if `livecheck` is `skip`.
  Library/Homebrew/cask/audit.rb
Labels: critical

#14825 More Formula/Casks sharding fixes
  Library/.rubocop.yml
  Library/Homebrew/dev-cmd/edit.rb
Labels: critical
