Repository Homebrew/brew, pull requests merged in 2023-03, with the labels that each got.

#14848 cask/cmd/upgrade: fix missing versions variable
  Library/Homebrew/cask/cmd/upgrade.rb
Labels: cask, critical

#14850 rubocop: Consolidate more rules into the right files
  Library/.rubocop.yml
  Library/Homebrew/.rubocop.yml
Labels: critical

#14849 formula: fix alias loading
  Library/Homebrew/formula.rb
  Library/Homebrew/test/formula_spec.rb
Labels: critical

#14857 dev-cmd/tests: better output for BuildPulse failures
  Library/Homebrew/dev-cmd/tests.rb
Labels: critical

#14862 cmd/update.sh: limit setting `core.fsmonitor` to `false`
  Library/Homebrew/cmd/update.sh
Labels: critical

#14869 rubocop: Disable RSpec metrics cops
  Library/.rubocop.yml
Labels: critical

#14865 os.rb: fix for WSL systems without wslview
  Library/Homebrew/os.rb
Labels: critical

#14871 rubocop: Alphabetise, remove config that's default, in-line some disables
  Library/.rubocop.yml
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/test/utils/spdx_spec.rb
Labels: critical

#14860 dev-cmd/contributions: Count the number of commits a user committed
  Library/Homebrew/dev-cmd/contributions.rb
  Library/Homebrew/utils/github.rb
Labels: critical

#14866 Note that `brew update` will only report all without API.
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/env_config.rb
  Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#14890 livecheck: Skip #preprocess_url for new strategies
  Library/Homebrew/livecheck/livecheck.rb
Labels: critical

#14889 utils/github: Fix double counting of author/committer numbers
  Library/Homebrew/dev-cmd/contributions.rb
  Library/Homebrew/test/utils/github_spec.rb
  Library/Homebrew/utils/github.rb
Labels: critical

#14877 rubocop: Enable `Layout/MultilineMethodCallIndentation` & fix offenses
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/test/cask/cask_spec.rb
  Library/Homebrew/test/cask/cmd/install_spec.rb
  Library/Homebrew/test/cask/cmd/uninstall_spec.rb
  Library/Homebrew/test/compiler_selector_spec.rb
  Library/Homebrew/test/dev-cmd/bottle_spec.rb
  Library/Homebrew/test/download_strategies/curl_github_packages_spec.rb
  Library/Homebrew/test/download_strategies/curl_post_spec.rb
  Library/Homebrew/test/download_strategies/curl_spec.rb
  Library/Homebrew/test/resource_spec.rb
  Library/Homebrew/test/utils/autoremove_spec.rb
  Library/Homebrew/test/utils/user_spec.rb
Labels: critical

#14884 rubocop: Deal with `RSpec` cop TODOs
  Library/.rubocop.yml
Labels: critical

#14886 rubocops/cask: Disallow protocol in cask URL verified stanza
  Library/Homebrew/rubocops/cask/mixin/on_url_stanza.rbi
  Library/Homebrew/rubocops/cask/url.rb
  Library/Homebrew/rubocops/cask/url_legacy_comma_separators.rb
  Library/Homebrew/rubocops/rubocop-cask.rb
  Library/Homebrew/test/rubocops/cask/url_spec.rb
Labels: critical

#14891 rubocops/cask: Clean up unnecessary `require`s
  Library/Homebrew/rubocops/cask/desc.rb
  Library/Homebrew/rubocops/cask/url_legacy_comma_separators.rb
Labels: critical

#14893 sorbet: Bump more files to `typed: true`
  Library/Homebrew/cask/dsl/caveats.rb
  Library/Homebrew/cask/info.rb
  Library/Homebrew/cask/list.rb
  Library/Homebrew/cmd/cleanup.rb
  Library/Homebrew/dependency.rb
  Library/Homebrew/extend/os/cleanup.rb
  Library/Homebrew/extend/os/linux/cleanup.rb
  Library/Homebrew/extend/os/linux/cmd/update-report.rb
  Library/Homebrew/extend/os/linux/keg.rb
  Library/Homebrew/extend/os/mac/cleanup.rb
  Library/Homebrew/startup/bootsnap.rb
  Library/Homebrew/test/support/helper/integration_mocks.rb
  Library/Homebrew/test/utils/repology_spec.rb
  Library/Homebrew/utils/popen.rb
Labels: critical

#14885 irb: add cask monkey patch
  Library/Homebrew/dev-cmd/irb.rb
Labels: critical

#14883 cask: retry audit for correct signing of pkg installers
  Library/Homebrew/cask/audit.rb
Labels: critical

#14878 rubocop: Trim exclude paths without offenses; move some more config
  Library/.rubocop.yml
  Library/Homebrew/.rubocop.yml
Labels: critical

#14903 Fix "undefined local variable" error in update-report
  Library/Homebrew/cmd/update-report.rb
Labels: critical

#14911 Enable typing in cmd/
  Library/Homebrew/cmd/--cache.rb
  Library/Homebrew/cmd/--prefix.rb
  Library/Homebrew/cmd/commands.rb
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/desc.rb
  Library/Homebrew/cmd/doctor.rb
  Library/Homebrew/cmd/fetch.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/list.rb
  Library/Homebrew/cmd/log.rb
  Library/Homebrew/cmd/options.rb
  Library/Homebrew/cmd/outdated.rb
  Library/Homebrew/cmd/reinstall.rb
  Library/Homebrew/cmd/search.rb
  Library/Homebrew/cmd/tap-info.rb
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/cmd/uses.rb
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
  Library/Homebrew/utils.rb
Labels: critical

#14879 lock_file: better message if too many open files
  Library/Homebrew/lock_file.rb
Labels: critical

#14910 ci: Move from Ubuntu 18.04 to Ubuntu 20.04 Actions runners
  .github/workflows/tests.yml
Labels: critical

#14914 Revert splat changes to AbstractUninstall
  Library/Homebrew/cask/artifact/abstract_uninstall.rb
Labels: critical

#14916 Refactor searchable
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/description_cache_store.rb
  Library/Homebrew/descriptions.rb
  Library/Homebrew/search.rb
  Library/Homebrew/search.rbi
  Library/Homebrew/searchable.rb
  Library/Homebrew/test/search_spec.rb
  Library/Homebrew/test/searchable_spec.rb
Labels: critical

#14870 Fix `{MacOS,Xcode}Requirement` handling and improve output
  Library/Homebrew/api.rb
  Library/Homebrew/dev-cmd/unbottled.rb
  Library/Homebrew/requirements/macos_requirement.rb
  Library/Homebrew/requirements/xcode_requirement.rb
Labels: critical

#14917 Remove ActiveSupport String inflections
  Library/Homebrew/extend/kernel.rb
  Library/Homebrew/global.rb
  Library/Homebrew/livecheck/strategy.rb
  Library/Homebrew/test/utils_spec.rb
  Library/Homebrew/utils.rb
Labels: critical

#14918 bump-formula-pr: add release notes if found
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
Labels: critical

#14922 rubocop: Trim `Naming/MethodParameterName` allowlist
  Library/.rubocop.yml
  Library/Homebrew/cask/download.rb
  Library/Homebrew/cleaner.rb
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/fetch.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/extend/kernel.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_text_auditor.rb
  Library/Homebrew/os/linux.rb
  Library/Homebrew/os/mac.rb
  Library/Homebrew/os/mac/sdk.rb
  Library/Homebrew/os/mac/xcode.rb
  Library/Homebrew/readall.rb
  Library/Homebrew/resource.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/utils/formatter.rb
Labels: critical

#14926 github_packages: retry skopeo copy 5 times
  Library/Homebrew/github_packages.rb
Labels: critical

#14927 Make `str` variable names longer
  Library/Homebrew/formula_text_auditor.rb
  Library/Homebrew/utils/formatter.rb
Labels: critical

#14932 github_packages: additional retry of skopeo copy with backoff
  Library/Homebrew/github_packages.rb
Labels: critical

#14941 Fix DescriptionCacheStore searching
  Library/Homebrew/description_cache_store.rb
  Library/Homebrew/search.rb
Labels: critical

#14940 Cleanup irb history file in tests
  Library/Homebrew/test/dev-cmd/irb_spec.rb
Labels: bug, critical

#14943 Auto-update from the API less often
  Library/Homebrew/api.rb
  Library/Homebrew/brew.sh
  Library/Homebrew/global.rb
Labels: critical

#14945 rubocop: Remove comment about RSpec from `Style/BlockDelimiters` config
  Library/.rubocop.yml
Labels: critical

#14944 rubocop: Further trim `Naming/MethodParameterName` allowlist
  Library/.rubocop.yml
  Library/Homebrew/build.rb
  Library/Homebrew/build_environment.rb
  Library/Homebrew/caveats.rb
  Library/Homebrew/cleaner.rb
  Library/Homebrew/cleanup.rb
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/fetch.rb
  Library/Homebrew/cmd/gist-logs.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/debrew.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/test.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/extend/kernel.rb
  Library/Homebrew/extend/os/mac/system_config.rb
  Library/Homebrew/fetch.rb
  Library/Homebrew/formula_pin.rb
  Library/Homebrew/install.rb
  Library/Homebrew/options.rb
  Library/Homebrew/os/mac.rb
  Library/Homebrew/rubocops/components_order.rb
  Library/Homebrew/system_config.rb
  Library/Homebrew/tab.rb
  Library/Homebrew/test/caveats_spec.rb
  Library/Homebrew/test/formula_installer_bottle_spec.rb
  Library/Homebrew/upgrade.rb
  Library/Homebrew/utils/analytics.rb
  Library/Homebrew/utils/bottles.rb
  Library/Homebrew/version.rb
Labels: critical

#14951 Check `CUSTOM_IMPLEMENTATIONS` for all variables.
  Library/Homebrew/env_config.rb
Labels: critical

#14950 sorbet: Autogenerate the RBI file for `Homebrew::EnvConfig`
  Library/Homebrew/dev-cmd/typecheck.rb
  Library/Homebrew/env_config.rbi
  Library/Homebrew/formula.rb
  Library/Homebrew/resource.rb
  Library/Homebrew/sorbet/custom_generators/env_config.rb
  Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
Labels: critical

#14958 Retry if DMG BOM is empty.
  Library/Homebrew/unpack_strategy/dmg.rb
Labels: critical

#14959 Remove artifact debug output.
  Library/Homebrew/cask/installer.rb
Labels: critical

#14965 rubocop: Enable `Style/AccessorGrouping` and autofix offenses
  Library/.rubocop.yml
  Library/Homebrew/utils/pypi.rb
Labels: critical

#14967 debrew: fix undefined variable
  Library/Homebrew/debrew.rb
Labels: critical

#14968 Dockerfile: `apt-get install` more useful things
  Dockerfile
Labels: critical

#14969 Enable types for most dev commands
  Library/Homebrew/cask/uninstall.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
  Library/Homebrew/dev-cmd/cat.rb
  Library/Homebrew/dev-cmd/extract.rb
  Library/Homebrew/dev-cmd/pr-publish.rb
  Library/Homebrew/dev-cmd/pr-pull.rb
  Library/Homebrew/dev-cmd/sh.rb
  Library/Homebrew/dev-cmd/tap-new.rb
  Library/Homebrew/extend/kernel.rb
  Library/Homebrew/test/extend/kernel_spec.rb
  Library/Homebrew/utils/git.rb
Labels: critical

#14970 Dockerfile: fix build of Ubuntu 18.04 image.
  Dockerfile
Labels: critical

#14973 Minor Kernel cleanup
  Library/Homebrew/extend/kernel.rb
  Library/Homebrew/test/extend/kernel_spec.rb
  Library/Homebrew/test/utils_spec.rb
  Library/Homebrew/utils.rb
Labels: critical

#14979 Fix `env_config` generator.
  Library/Homebrew/env_config.rb
  Library/Homebrew/sorbet/custom_generators/env_config.rb
Labels: critical

#14980 Simplify SPDX test.
  Library/Homebrew/test/utils/spdx_spec.rb
Labels: critical

#14981 Remove OpenStruct use in Tab
  Library/.rubocop.yml
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/extend/os/mac/keg_relocate.rb
  Library/Homebrew/tab.rb
  Library/Homebrew/test/support/lib/startup/config.rb
  Library/Homebrew/test/tab_spec.rb
Labels: critical

#14972 cmd/{rb,nod}env-sync: add new commands.
  Library/Homebrew/cmd/nodenv-sync.rb
  Library/Homebrew/cmd/rbenv-sync.rb
Labels: critical

#14982 Dockerfile: fix installation of `gh`, et al.
  Dockerfile
Labels: critical

#14985 Remove compatibility layer
  .github/workflows/tests.yml
  Library/Homebrew/.simplecov
  Library/Homebrew/.yardopts
  Library/Homebrew/compat/cask.rb
  Library/Homebrew/compat/early.rb
  Library/Homebrew/compat/formula.rb
  Library/Homebrew/compat/late.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/env_config.rb
  Library/Homebrew/env_config.rbi
  Library/Homebrew/extend/kernel.rb
  Library/Homebrew/global.rb
  Library/Homebrew/rubocops/extend/formula_cop.rb
  Library/Homebrew/test/spec_helper.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Homebrew-brew-Maintainer-Guide.md
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#14986 sorbet: Fix (not) committing Spoom automatic sigil bumps
  .github/workflows/sorbet.yml
Labels: critical

#14989 workflows/tests: also run update-tests for merge_group.
  .github/workflows/tests.yml
Labels: critical

#14983 Update GitHubPackages for new Tab implementation
  Library/Homebrew/github_packages.rb
Labels: critical

#14990 Revert "Update GitHubPackages for new Tab implementation"
  Library/Homebrew/github_packages.rb
Labels: critical

#14984 utils/gzip: don't mark API as private
  Library/Homebrew/utils/gzip.rb
Labels: critical

#14992 Fix GitHub.last_commit and enable more typing
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/download_strategy.rbi
  Library/Homebrew/patch.rb
  Library/Homebrew/pkg_version.rb
  Library/Homebrew/pkg_version.rbi
  Library/Homebrew/style.rb
  Library/Homebrew/utils/git.rb
  Library/Homebrew/utils/github.rb
Labels: critical

#14997 Update path to system settings on Ventura
  Library/Homebrew/cask/artifact/abstract_uninstall.rb
  Library/Homebrew/cask/dsl/caveats.rb
  Library/Homebrew/os/mac/xcode.rb
  docs/Cask-Cookbook.md
Labels: critical

#15001 test/cask: Fix "System Settings" caveats for (non-)Ventura OSes
  Library/Homebrew/test/cask/cask_spec.rb
  Library/Homebrew/test/support/fixtures/cask/everything-systemsettings-caveats.json
Labels: critical

#15002 utils/github/actions: add `format_multiline_string` method
  Library/Homebrew/utils/github/actions.rb
Labels: critical

#15005 utils/github/actions: remove `Error` class
  Library/Homebrew/utils/github/actions.rb
Labels: critical

#15006 Enable typing in Library/Homebrew/brew.rb
  Library/Homebrew/Gemfile
  Library/Homebrew/Gemfile.lock
  Library/Homebrew/brew.rb
  Library/Homebrew/sorbet/rbi/gems/stackprof@0.2.23.rbi
  Library/Homebrew/sorbet/rbi/todo.rbi
Labels: critical

#15000 caveats: Remove extra blank line between `keg_only` and other caveats
  Library/Homebrew/caveats.rb
  Library/Homebrew/test/caveats_spec.rb
Labels: critical

#15008 Enable types in Library/Homebrew/cask, etc.
  Library/Homebrew/cask/dsl/conflicts_with.rb
  Library/Homebrew/cask/dsl/depends_on.rb
  Library/Homebrew/cask/dsl/depends_on.rbi
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/cask/quarantine.rb
  Library/Homebrew/cask/upgrade.rb
  Library/Homebrew/extend/git_repository.rbi
  Library/Homebrew/extend/pathname.rbi
  Library/Homebrew/os/mac/version.rb
  Library/Homebrew/os/mac/version.rbi
Labels: waiting for feedback

#15009 cask: remove old prefix placeholder
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/cask_loader.rb
Labels: waiting for feedback

#15011 pr-pull: add `--no-cherry-pick` flag
  Library/Homebrew/dev-cmd/pr-pull.rb
Labels: waiting for feedback

#15015 dev-cmd/contributions: appropriately pluralize contribution statement
  Library/Homebrew/dev-cmd/contributions.rb
Labels: waiting for feedback

#15019 Remove misleading upstream.rbi, enable types in on_system
  Library/Homebrew/cask/config.rb
  Library/Homebrew/cask/dsl.rb
  Library/Homebrew/cask/dsl/version.rb
  Library/Homebrew/extend/on_system.rb
  Library/Homebrew/sorbet/rbi/upstream.rbi
Labels: waiting for feedback

#15018 Use ActiveSupport Hash#assert_valid_keys instead of refinement
  Library/Homebrew/cask/artifact/abstract_uninstall.rb
  Library/Homebrew/cask/artifact/artifact.rb
  Library/Homebrew/cask/artifact/installer.rb
  Library/Homebrew/cask/artifact/pkg.rb
  Library/Homebrew/cask/artifact/relocated.rb
  Library/Homebrew/cask/config.rb
  Library/Homebrew/cask/dsl/conflicts_with.rb
  Library/Homebrew/extend/hash_validator.rb
  Library/Homebrew/extend/hash_validator.rbi
  Library/Homebrew/system_command.rb
Labels: waiting for feedback

#15020 Add include_count parameter to pluralize util
  Library/Homebrew/cask/cmd/install.rb
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/cmd/tap-info.rb
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/contributions.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/extend/kernel.rb
  Library/Homebrew/install.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/utils_spec.rb
  Library/Homebrew/upgrade.rb
  Library/Homebrew/utils.rb
Labels: waiting for feedback

#15021 analytics: improve InfluxDB cardinality
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/test/utils/analytics_spec.rb
  Library/Homebrew/utils/analytics.rb
Labels: critical

#14971 cmd/postgresql-upgrade-database: import from homebrew/core.
  Library/Homebrew/cmd/postgresql-upgrade-database.rb
Labels: critical

#15027 Remove explicit error for empty BOM retry.
  Library/Homebrew/unpack_strategy/dmg.rb
Labels: waiting for feedback

#15028 Fix `toplevel_stanzas`.
  Library/Homebrew/rubocops/cask/ast/cask_block.rb
  Library/Homebrew/rubocops/cask/ast/stanza.rb
  Library/Homebrew/rubocops/cask/extend/node.rb
Labels: waiting for feedback

#15034 update*: check shim output
  Library/Homebrew/cmd/update-reset.sh
  Library/Homebrew/cmd/update.sh
Labels: waiting for feedback

#15033 Enable more typing
  Library/Homebrew/keg.rb
  Library/Homebrew/mktemp.rb
  Library/Homebrew/options.rb
  Library/Homebrew/options.rbi
  Library/Homebrew/os/linux/elf.rb
  Library/Homebrew/os/linux/elf.rbi
  Library/Homebrew/os/mac/mach.rb
  Library/Homebrew/os/mac/mach.rbi
Labels: waiting for feedback

#15038 cmd/update-report: fix ordering.
  Library/Homebrew/cmd/update-report.rb
Labels: critical

#15044 Revert "move `cask/cmd/reinstall`"
  Library/Homebrew/cask/cmd.rb
  Library/Homebrew/cask/cmd/reinstall.rb
  Library/Homebrew/cask/reinstall.rb
  Library/Homebrew/cmd/reinstall.rb
  Library/Homebrew/test/cask/cmd/reinstall_spec.rb
Labels: critical

#15007 Add service block to formula api
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cask/dsl.rb
  Library/Homebrew/dev-cmd/generate-formula-api.rb
  Library/Homebrew/extend/api_hashable.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/global.rb
  Library/Homebrew/service.rb
  Library/Homebrew/test/cask/cask_spec.rb
  Library/Homebrew/test/formulary_spec.rb
  Library/Homebrew/test/service_spec.rb
Labels: bug, install from api

#15052 formulary: require service.
  Library/Homebrew/formulary.rb
Labels: critical

#15067 triage-issues.yml: update to match main configuration
  .github/workflows/triage-issues.yml
Labels: critical

#15058 readall: fix no simulate
  Library/Homebrew/extend/os/linux/readall.rb
  Library/Homebrew/extend/os/mac/readall.rb
  Library/Homebrew/extend/os/readall.rb
  Library/Homebrew/readall.rb
Labels: bug

#15078 formula: add missing extend/os require
  Library/Homebrew/extend/os/formula.rb
Labels: critical

#15079 Revert "Allow `resource` blocks to include `on_*` blocks or conditionals"
  Library/Homebrew/rubocops/lines.rb
  Library/Homebrew/rubocops/shared/on_system_conditionals_helper.rb
Labels: critical

#15110 dev-cmd/tests: temporary fix for BuildPulse failure
  Library/Homebrew/dev-cmd/tests.rb
Labels: critical

#15111 Revert "Remove `--request GET` workaround for HEAD requests."
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/livecheck/strategy.rb
Labels: critical

#15112 Split prof gems into their own group
  .github/workflows/tests.yml
  Library/Homebrew/Gemfile
  Library/Homebrew/dev-cmd/install-bundler-gems.rb
  Library/Homebrew/dev-cmd/prof.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/dev-cmd/vendor-gems.rb
  Library/Homebrew/utils/gems.rb
Labels: critical
