Repository Homebrew/brew, pull requests merged in 2023-09, with the labels that each got.

#15938 os/mac/hardware: remove TODO.
  Library/Homebrew/extend/os/mac/hardware.rb
Labels: critical

#15941 formula_auditor: make Linux-only GCC dep audit non-strict.
  Library/Homebrew/formula_auditor.rb
Labels: critical

#15943 Handle nil cask urls caused by unsupported macOS version
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cask/download.rb
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/cmd/fetch.rb
Labels: bug, cask

#15937 Cleanup various TODOs
  Library/.rubocop.yml
  Library/Homebrew/cmd/fetch.rb
  Library/Homebrew/download_strategy.rb
Labels: critical

#15935 api: use `Utils::Curl.curl_args`
  Library/Homebrew/api.rb
  Library/Homebrew/utils/curl.rb
Labels: critical

#15949 formula_installer: handle another exception in fetch_bottle_tab.
  Library/Homebrew/formula_installer.rb
Labels: critical

#15961 utils/github/artifacts: fix missing Utils::Curl reference.
  Library/Homebrew/utils/github/artifacts.rb
Labels: critical

#15963 formula_installer: don't ignore deps when fetching and pouring bottles.
  Library/Homebrew/formula_installer.rb
Labels: critical

#15964 Fix more `Utils::Curl` usage
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/resource_auditor.rb
Labels: critical

#15936 Audit invalid versions
  Library/Homebrew/github_packages.rb
  Library/Homebrew/resource_auditor.rb
Labels: critical

#15967 utils/github: fully scope curl usage.
  Library/Homebrew/utils/github.rb
Labels: critical

#15968 cask/quarantine: sudo correctly during tests.
  Library/Homebrew/cask/artifact/moved.rb
  Library/Homebrew/cask/quarantine.rb
Labels: critical

#15977 Improve cask audit
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/download.rb
  Library/Homebrew/cmd/fetch.rb
  Library/Homebrew/dev-cmd/audit.rb
Labels: bug, cask

#15992 os/mac/keg: fix `change_rpath` type signature.
  Library/Homebrew/os/mac/keg.rb
Labels: critical

#15997 os/mac/pkgconfig: update for macOS 14 RC SDK
  Library/Homebrew/os/mac/pkgconfig/13/libcurl.pc
  Library/Homebrew/os/mac/pkgconfig/14/libcurl.pc
Labels: critical

#15999 docs/Rakefile: fix broken link.
  docs/Rakefile
Labels: critical

#16000 utils/shared_audits: handle 404 metadata errors from GitLab API.
  Library/Homebrew/utils/shared_audits.rb
Labels: critical

#16002 Formula, BuildError: Update type signatures
  Library/Homebrew/exceptions.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/test/exceptions_spec.rb
Labels: critical

#16005 superenv: help gettext-based configure scripts
  Library/Homebrew/extend/os/mac/extend/ENV/super.rb
Labels: critical

#16014 utils/backtrace: scrub sorbet-runtime from backtrace
  Library/Homebrew/brew.rb
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/dev-cmd/test.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/formula_versions.rb
  Library/Homebrew/livecheck/livecheck.rb
  Library/Homebrew/migrator.rb
  Library/Homebrew/test/utils/backtrace_spec.rb
  Library/Homebrew/utils.rb
  Library/Homebrew/utils/backtrace.rb
  Library/Homebrew/utils/repology.rb
Labels: discussion

#16031 docs: update commit style guidelines
  docs/Formula-Cookbook.md
Labels: documentation

#16038 manpage: note env files do not support expansion.
  Library/Homebrew/manpages/brew.1.md.erb
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#16039 dev-cmd/audit: load formulae from files
  Library/Homebrew/dev-cmd/audit.rb
Labels: bug

#16047 utils/gems: redirect bundler output to stderr
  Library/Homebrew/utils/gems.rb
Labels: critical

#16048 Gemfile: fix pr_upload group typo
  Library/Homebrew/Gemfile
Labels: critical

#16054 Revert "service: support multiple sockets in DSL"
  Library/Homebrew/service.rb
  Library/Homebrew/test/service_spec.rb
  docs/Formula-Cookbook.md
Labels: critical
