Repository Homebrew/brew, pull requests merged in 2023-07, with the labels that each got.

#15619 test/utils/github_spec: fix artifact URL test
  Library/Homebrew/test/utils/github_spec.rb
Labels: critical

#15631 Remove `Tap#versioned_formula_files`
  Library/Homebrew/formula.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/formula_spec.rb
Labels: critical

#14592 cmd/update-report: nudge people to tweak settings.
  Library/Homebrew/cmd/update-report.rb
Labels: in progress

#15637 cmd/update-report: use api_auto_update_secs default.
  Library/Homebrew/cmd/update-report.rb
Labels: critical

#15647 cmd/update: adjustments for setup-homebrew in brew CI
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/test/formulary_spec.rb
  Library/Homebrew/test/os/mac/formula_spec.rb
  Library/Homebrew/test/software_spec_spec.rb
Labels: critical

#15648 tap: fix handling of taps without formulae
  Library/Homebrew/tap.rb
Labels: critical

#15657 livecheck: fix implicit no-api handling
  Library/Homebrew/livecheck/livecheck.rb
  Library/Homebrew/livecheck/strategy/extract_plist.rb
Labels: critical

#15672 shims/mac/super/make: use standard exec routines
  Library/Homebrew/shims/mac/super/make
Labels: critical

#15677 generate-*-api: fix on-disk tap migrations not being used
  Library/Homebrew/dev-cmd/generate-cask-api.rb
  Library/Homebrew/dev-cmd/generate-formula-api.rb
Labels: critical

#15684 os/mac/mach: report duplicate rpaths
  Library/Homebrew/os/mac/mach.rb
Labels: critical

#15688 utils/analytics: hide InfluxDB message correctly.
  Library/Homebrew/utils/analytics.rb
Labels: critical

#15695 Fix (again) InfluxDB analytics messaging
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/utils/analytics.rb
Labels: critical

#15697 cmd/tap: remove --list-pinned option.
  Library/Homebrew/cmd/tap.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#15698 diagnostic: don't complain about missing homebrew/cask.
  Library/Homebrew/diagnostic.rb
Labels: critical

#15700 docs/Installation: fix Mac OS X reference.
  docs/Installation.md
Labels: critical

#15701 dev-cmd/bump-*-pr: avoid installing gems when unneeded.
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
Labels: critical

#15702 api_hashable: remove HOMEBREW_CELLAR.
  Library/Homebrew/extend/api_hashable.rb
Labels: critical

#15722 os/mac/keg_relocate: avoid rpath re-ordering
  Library/Homebrew/extend/os/mac/keg_relocate.rb
Labels: critical

#15734 formula: fix typechecking error in `std_cmake_args`
  Library/Homebrew/formula.rb
Labels: critical

#15735 github_packages: ensure only OCI format is uploaded
  Library/Homebrew/github_packages.rb
Labels: critical

#15738 formula: fix `inreplace` typechecking error
  Library/Homebrew/formula.rb
Labels: critical

#15739 utils/inreplace: fix typechecking error
  Library/Homebrew/utils/inreplace.rb
Labels: critical

#15746 cmd/install: upgrade already installed casks
  Library/Homebrew/cask/exceptions.rb
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/env_config.rb
  Library/Homebrew/test/cask/installer_spec.rb
Labels: cask

#15749 cmd/install: add missing require.
  Library/Homebrew/cmd/install.rb
Labels: critical

#15752 docs/vale-styles: fix configuration.
  CONTRIBUTING.md
  docs/Acceptable-Casks.md
  docs/Adding-Software-to-Homebrew.md
  docs/vale-styles/Homebrew/Terms.yml
Labels: critical

#15751 macOS .pkg improvements
  .github/workflows/build-pkg.yml
  .gitignore
  package/Distribution.xml
  package/resources/CONCLUSION.rtf
  package/resources/Homebrew.png
  package/resources/WELCOME.rtf
  package/scripts/postinstall
  package/scripts/preinstall
Labels: critical

#15754 cask/url: accept `Class` for `using`.
  Library/Homebrew/cask/url.rb
Labels: critical

#15762 pkg installer: install cached API data.
  .github/workflows/build-pkg.yml
  package/scripts/postinstall
Labels: critical

#15765 brew.sh: don't set `HOMEBREW_NO_INSTALL_FROM_API` automatically.
  Library/Homebrew/brew.sh
  docs/Installation.md
Labels: critical

#15766 analytics: fix `@` in formulae names with `--github-packages-downloads`
  Library/Homebrew/utils/analytics.rb
Labels: critical

#15768 Revert "brew.sh: don't set `HOMEBREW_NO_INSTALL_FROM_API` automatically."
  Library/Homebrew/brew.sh
  docs/Installation.md
Labels: critical

#15755 docs/Installation: document macOS .pkg installer.
  docs/Installation.md
Labels: critical

#15777 keg_relocate: fix all text files being marked as changed
  Library/Homebrew/github_packages.rb
  Library/Homebrew/keg_relocate.rb
Labels: critical

#15780 `brew update` core/homebrew-cask taps properly
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/update.sh
Labels: critical

#15781 post_install: improvements and fixes.
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/postinstall.rb
  Library/Homebrew/commands.rb
  Library/Homebrew/formula_installer.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/internal_commands_list.txt
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: critical

#15782 Improve VSCode extensions/settings
  .vscode/extensions.json
  .vscode/settings.json
Labels: critical

#15794 package/resources: improve text output.
  .github/workflows/build-pkg.yml
  package/resources/CONCLUSION.rtf
  package/resources/WELCOME.rtf
Labels: critical

#15795 workflows/build-pkg: install `gh`.
  .github/workflows/build-pkg.yml
Labels: critical
