Repository Homebrew/brew, pull requests merged in 2023-11, with the labels that each got.

#16178 Manpage: update GitHub rate limit link
  Library/Homebrew/env_config.rb
  docs/Manpage.md
  manpages/brew.1
Labels: documentation

#16181 manpages: fix error under Ruby 3
  Library/Homebrew/manpages.rb
Labels: critical

#16182 formula_auditor: handle nil tap
  Library/Homebrew/formula_auditor.rb
Labels: critical

#16195 cmd/desc: fix handling of `--eval-all` with formulae
  Library/Homebrew/description_cache_store.rb
Labels: bug

#16216 Pass original tap to formula when loaded from the API via `TapLoader`
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: critical, install from api

#16218 ENV/shared: fix macOS code not applying under HOMEBREW_SORBET_RUNTIME
  Library/Homebrew/extend/os/mac/extend/ENV/shared.rb
Labels: critical

#16226 Gemfile.lock: restore missing platform
  Library/Homebrew/Gemfile.lock
Labels: critical

#16231 dev-cmd/vendor-gems: workaround Dependabot removing lockfile platforms
  Library/Homebrew/dev-cmd/vendor-gems.rb
Labels: critical

#16232 dev-cmd/vendor-gems: git add Gemfile.lock
  Library/Homebrew/dev-cmd/vendor-gems.rb
Labels: critical

#16245 Dockerfile: set `XDG_CACHE_HOME` to fix `umask` in GitHub Actions
  Dockerfile
Labels: critical

#16246 brew.sh: set HOMEBREW_RUBY3 earlier
  Library/Homebrew/brew.sh
  Library/Homebrew/test/os/mac/diagnostic_spec.rb
Labels: critical

#16253 brew.sh: always run test-bot under Ruby 3
  Library/Homebrew/brew.sh
Labels: critical
