Repository Homebrew/brew, pull requests merged in 2023-12, with the labels that each got.

#16288 unpack_strategy/zip: fix extraction issues on macOS without developer mode
  Library/Homebrew/extend/os/mac/unpack_strategy/zip.rb
  Library/Homebrew/extend/os/mac/unpack_strategy/zip.rbi
Labels: critical

#16298 utils/svn_spec: change remote used in test.
  Library/Homebrew/test/utils/svn_spec.rb
Labels: critical

#16300 Lazy load Debrew (fixes setupterm error on some environments)
  Library/Homebrew/build.rb
  Library/Homebrew/debrew.rb
  Library/Homebrew/postinstall.rb
  Library/Homebrew/test.rb
Labels: critical

#16319 docs: remove `pip search` recommendation
  docs/Homebrew-and-Python.md
Labels: documentation

#16328 Cask#full_name: properly output Homebrew org names
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/livecheck/livecheck.rb
  Library/Homebrew/test/cask/audit_spec.rb
Labels: critical

#16330 cmd/untap: fix untapping syntax failure.
  Library/Homebrew/cask/caskroom.rb
  Library/Homebrew/cmd/untap.rb
  Library/Homebrew/formula.rb
Labels: critical

#16292 Add `deprecate!` and `disable!` to casks
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/cask.rbi
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cask/dsl.rb
  Library/Homebrew/cask/dsl/caveats.rb
  Library/Homebrew/cask/exceptions.rb
  Library/Homebrew/cask/info.rb
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/deprecate_disable.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_auditor.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/livecheck/skip_conditions.rb
  Library/Homebrew/rubocops/cask/ast/stanza.rb
  Library/Homebrew/rubocops/cask/constants/stanza.rb
  Library/Homebrew/test/deprecate_disable_spec.rb
  Library/Homebrew/test/formulary_spec.rb
  Library/Homebrew/test/livecheck/skip_conditions_spec.rb
  Library/Homebrew/test/support/fixtures/cask/everything.json
Labels: cask

#16352 Re-add some `discontinued?` checks for casks
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/cask/cask.rbi
  Library/Homebrew/cask/dsl.rb
  Library/Homebrew/livecheck/skip_conditions.rb
  Library/Homebrew/test/livecheck/skip_conditions_spec.rb
Labels: critical

#16354 Add `deprecate!` and `disable!` to cask docs
  docs/Brew-Livecheck.md
  docs/Cask-Cookbook.md
Labels: documentation

#16372 cask/artifact/abstract_uninstall: handle signal failures.
  Library/Homebrew/cask/artifact/abstract_uninstall.rb
Labels: critical

#16375 vscode/settings: update shellcheck.
  .vscode/settings.json
Labels: critical

#16376 rubocops/cask/on_system_conditionals: allow blocks.
  Library/Homebrew/rubocops/cask/on_system_conditionals.rb
Labels: critical

#16384 Fix Cask::Cask.all bug
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/cmd/uses.rb
  Library/Homebrew/description_cache_store.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/livecheck.rb
Labels: bug, cask
