Repository Homebrew/brew, pull requests merged in 2023-08, with the labels that each got.

#15740 dev-cmd/edit: suggest tapping core repositories if untapped
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cli/named_args.rb
  Library/Homebrew/dev-cmd/edit.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/exceptions_spec.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: install from api

#15812 Revert "Make `inreplace` a purely static method"
  Library/Homebrew/cask/migrator.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/utils/inreplace.rb
  Library/Homebrew/utils/inreplace.rbi
Labels: critical

#15818 bin/brew: handle missing `$HOME`.
  bin/brew
Labels: critical

#15820 Make more warnings quiet with environment hints disabled.
  Library/Homebrew/formula_cellar_checks.rb
  Library/Homebrew/upgrade.rb
Labels: critical

#15819 bottle: reproducibility fixes.
  .github/workflows/tests.yml
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/extend/os/dev-cmd/bottle.rb
  Library/Homebrew/extend/os/linux/dev-cmd/bottle.rb
  Library/Homebrew/extend/os/mac/dev-cmd/bottle.rb
Labels: critical

#15826 dev-cmd/bump : stop using API to load formulae/casks
  Library/Homebrew/dev-cmd/bump.rb
Labels: bug, critical

#15828 os/mac/mach: avoid recursively resolving rpaths
  Library/Homebrew/os/mac/mach.rb
Labels: critical

#15829 cmd/bump: add --installed flag
  Library/Homebrew/dev-cmd/bump.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: enhancement

#15847 tap: always create new casks in subdirectory.
  Library/Homebrew/tap.rb
Labels: critical

#15848 formula_cop: fix `style_exceptions_dir` handling.
  Library/Homebrew/rubocops/extend/formula_cop.rb
Labels: critical

#15850 Fix cask sharding issues
  Library/Homebrew/cask/info.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/cask/audit_spec.rb
  Library/Homebrew/test/cask/cask_spec.rb
  Library/Homebrew/test/cask/info_spec.rb
  Library/Homebrew/test/cask/upgrade_spec.rb
  Library/Homebrew/test/livecheck/strategy/extract_plist_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-discontinued-reference.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-discontinued.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-installer-manual.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-url-unversioned-reference.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-url-unversioned.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-version-latest-reference.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-version-latest.rb
  Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb
Labels: critical

#15864 os/mac/mach: fix rpath deletion of fat machos
  Library/Homebrew/os/mac/mach.rb
Labels: critical

#15877 brew.sh: fix shellcheck warning.
  Library/Homebrew/brew.sh
Labels: critical

#15889 dev-cmd/bottle: install gnu-tar before keg lock.
  Library/Homebrew/dev-cmd/bottle.rb
Labels: critical

#15895 api: ignore HTTPS errors if required certs aren't installed
  Library/Homebrew/api.rb
Labels: install from api

#15913 workflows/tests: workaround GitHub Actions python issues.
  .github/workflows/tests.yml
Labels: critical

#15892 dependency_helpers: rework recursive dependency resolution
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/uses.rb
  Library/Homebrew/dependencies_helpers.rb
  Library/Homebrew/test/cmd/deps_spec.rb
  Library/Homebrew/test/cmd/uses_spec.rb
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: bug

#15922 cmd/deps: fix documentation and handling of formula_options.
  Library/Homebrew/cmd/deps.rb
  docs/Manpage.md
  manpages/brew.1
Labels: critical
