Repository Homebrew/brew, pull requests merged in 2024-08, with the labels that each got.

#17922 Homebrew-and-Python: more PEP 668 guidance
  docs/Homebrew-and-Python.md
Labels: documentation

#17940 Show dependencies for casks
  Library/Homebrew/cask/info.rb
  Library/Homebrew/test/cask/info_spec.rb
Labels: cask

#18020 Make Cask::Artifact::Installer typesafe
  Library/Homebrew/cask/artifact/installer.rb
  Library/Homebrew/cask/artifact/installer.rbi
  Library/Homebrew/cask/upgrade.rb
  Library/Homebrew/test/cask/dsl_spec.rb
Labels: cask

#17827 feat: add attestation to installer
  .github/workflows/docker.yml
  .github/workflows/pkg-installer.yml
  .github/workflows/tests.yml
Labels: in progress

#18217 Adjust typing around #check_pull_requests
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
  Library/Homebrew/utils/github.rb
Labels: bug
