Repository Homebrew/brew, pull requests merged in 2024-02, with the labels that each got.

#16541 Next gen api formula json v3
  Library/Homebrew/dev-cmd/generate-formula-api.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/service.rb
  Library/Homebrew/test/formula_spec.rb
  Library/Homebrew/test/service_spec.rb
Labels: install from api

#16613 workflows/tests: remove `brew cleanup --prune-prefix`
  .github/workflows/tests.yml
Labels: critical

#16617 Fix loading aliases from API.
  Library/Homebrew/formulary.rb
Labels: critical

#16635 Stop following recursive tap migrations.
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/formulary.rb
Labels: critical

#16637 Fix support of formulae aliases in taps
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: critical

#16650 test/cask/upgrade_spec: remove flaky specs.
  Library/Homebrew/test/cask/upgrade_spec.rb
Labels: critical

#16634 docs: modernize BrewTestBot info for maintainers
  docs/Brew-Test-Bot-For-Core-Contributors.md
Labels: documentation

#16666 docs: `Brew Test Bot` -> `BrewTestBot`
  docs/Bottles.md
  docs/BrewTestBot.md
  docs/Formula-Cookbook.md
  docs/Homebrew-homebrew-core-Maintainer-Guide.md
  docs/README.md
Labels: documentation

#16670 docs: redirect from old BrewTestBot URLs
  docs/Bottles.md
  docs/BrewTestBot-For-Maintainers.md
  docs/BrewTestBot.md
  docs/Formula-Cookbook.md
  docs/Homebrew-and-Python.md
  docs/Homebrew-homebrew-core-Maintainer-Guide.md
Labels: documentation

#16681 Fix flaky `CaskDependent` tests.
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
Labels: critical

#16680 Fix flaky `Formulary` test.
  Library/Homebrew/test/cask/cask_loader_spec.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: critical

#16684 Revert "Refactor `Formulary::loader_for`."
  Library/Homebrew/api/formula.rb
  Library/Homebrew/cleanup.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/formula_auditor.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/tap_constants.rb
  Library/Homebrew/test/formula_spec.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: critical

#16728 Fix tap constants.
  Library/Homebrew/tap_constants.rb
  Library/Homebrew/test/tap_spec.rb
Labels: critical

#16729 Pass `warn` in `FromNameLoader`.
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: critical

#16760 test: clear tap instance caches between test runs again
  Library/Homebrew/test/spec_helper.rb
Labels: critical

#16638 Load internal json v3
  Library/Homebrew/api.rb
  Library/Homebrew/api/formula.rb
  Library/Homebrew/dev-cmd/generate-formula-api.rb
  Library/Homebrew/extend/cachable.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/api/internal_tap_json/formula_spec.rb
  Library/Homebrew/test/support/fixtures/internal_tap_json/homebrew-core.json
  Library/Homebrew/test/support/fixtures/internal_tap_json/homebrew-core/Formula/f/fennel.rb
  Library/Homebrew/test/support/fixtures/internal_tap_json/homebrew-core/Formula/p/ponyc.rb
  Library/Homebrew/test/support/fixtures/internal_tap_json/homebrew-core/formula_renames.json
  Library/Homebrew/test/support/fixtures/internal_tap_json/homebrew-core/tap_migrations.json
Labels: install from api

#16766 Only show installed taps in `brew tap` output.
  Library/Homebrew/cmd/tap.rb
  Library/Homebrew/tap.rb
Labels: bug

#16768 internal json v3: parse ruby source checksum correctly
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/api/internal_tap_json/formula_spec.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: bug

#16731 docs: update info on setuptools for Python 3.12
  docs/Homebrew-and-Python.md
Labels: documentation
