Repository Homebrew/brew, pull requests merged in 2024-04, with the labels that each got.

#17041 docs: update info as `linux-only` labels are automerged
  docs/Homebrew-homebrew-core-Maintainer-Guide.md
Labels: documentation

#17043 dev-cmd/bump-cask-pr: use FromContentLoader when relevant.
  Library/Homebrew/dev-cmd/bump-cask-pr.rb
Labels: bug

#17073 dev-cmd/tests: fix when euid != uid.
  Library/Homebrew/dev-cmd/tests.rb
Labels: bug

#17083 docs(Python): reapply suggestions and update outdated info
  docs/Python-for-Formula-Authors.md
Labels: documentation

#17088 docs/Installation: use HEAD similar to install repo README.md
  docs/Installation.md
Labels: documentation

#17106 ensure_executable!: add opt_bin path to search
  Library/Homebrew/extend/kernel.rb
Labels: bug

#17125 cmd/list: support listing formulae installed on request or automatically
  Library/Homebrew/cmd/list.rb
  Library/Homebrew/sorbet/rbi/dsl/homebrew/cmd/list.rbi
  Library/Homebrew/test/sorbet/tapioca/compilers/args_spec.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: features

#17138 utils/github: paginate artifact API result
  Library/Homebrew/utils/github.rb
  Library/Homebrew/utils/github/api.rb
Labels: bug

#16476 feat: add audit for wayback machine URLs
  Library/Homebrew/formula_auditor.rb
Labels: stale
