Repository Homebrew/brew, pull requests merged in 2024-05, with the labels that each got.

#17153 New formula internal json v3 dependencies format
  Library/Homebrew/formula.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/api/internal_tap_json/formula_spec.rb
  Library/Homebrew/test/support/fixtures/internal_tap_json/homebrew-core.json
  Library/Homebrew/test/support/fixtures/internal_tap_json/homebrew-core/Formula/i/inko.rb
Labels: install from api

#17200 cmd/leaves: fix an `undefined method` error
  Library/Homebrew/cmd/leaves.rb
Labels: bug

#17208 docs: update for Homebrew/cask-versions deprecation
  docs/Acceptable-Casks.md
  docs/Cask-Cookbook.md
  docs/Homebrew-homebrew-cask-Maintainer-Guide.md
  docs/Maintainer-Guidelines.md
Labels: documentation

#17210 Cask-Cookbook: remove outdated URL
  docs/Cask-Cookbook.md
Labels: documentation

#17212 dev-cmd/tests: skip tests that require core if it's not tapped
  Library/Homebrew/test/cmd/--prefix_spec.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/test/support/helper/spec/shared_examples/formulae_exist.rb
Labels: bug

#17242 Fix cask source file path loading issues
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cli/named_args.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/bump.rb
  Library/Homebrew/dev-cmd/livecheck.rb
  Library/Homebrew/test/cask/cask_loader/from_path_loader_spec.rb
Labels: bug, cask

#17314 docs: update for Homebrew/cask-fonts deprecation
  .github/workflows/tests.yml
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/official_taps.rb
  Library/Homebrew/test/cask/cask_loader/from_api_loader_spec.rb
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Acceptable-Casks.md
  docs/Cask-Cookbook.md
  docs/Homebrew-homebrew-cask-Maintainer-Guide.md
  docs/Maintainer-Guidelines.md
  docs/Manpage.md
  manpages/brew.1
Labels: documentation

#16702 Dockerfile: drop libz-dev
  Dockerfile
Labels: in progress

#17339 build(deps): bump ruby/setup-ruby from 1.176.0 to 1.177.0
  .github/workflows/docs.yml
Labels: dependencies, github_actions

#17345 docs: clarify upstream taps
  docs/How-to-Create-and-Maintain-a-Tap.md
Labels: documentation
