Repository Homebrew/brew, pull requests merged in 2024-03, with the labels that each got.

#16789 docs: update language on commit messages & notability
  docs/Acceptable-Formulae.md
  docs/Formula-Cookbook.md
  docs/How-To-Open-a-Homebrew-Pull-Request.md
Labels: documentation

#16791 tap: fix performance regression in *_files_by_name
  Library/Homebrew/tap.rb
Labels: bug

#16797 tap: revert caching `Tap.reverse_tap_migrations_renames`
  Library/Homebrew/tap.rb
Labels: critical

#16843 Import Homebrew governance changes from private repository
  docs/Homebrew-Governance.md
Labels: critical

#16798 dev-cmd/generate-cask-api: start generating cask internal JSON v3
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/dev-cmd/generate-cask-api.rb
  Library/Homebrew/dev-cmd/generate-formula-api.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/api/internal_tap_json/formula_spec.rb
Labels: cask, install from api

#16870 docs: remove some system Python notes
  docs/Gems,-Eggs-and-Perl-Modules.md
  docs/Homebrew-and-Python.md
Labels: documentation

#16875 Fix untap cmd bugs
  Library/Homebrew/cmd/untap.rb
  Library/Homebrew/test/support/helper/formula.rb
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
  Library/Homebrew/test/untap_spec.rb
  Library/Homebrew/untap.rb
Labels: bug

#16900 utils/github: fix variable scope
  Library/Homebrew/utils/github.rb
Labels: critical

#16903 Prevent unexpected network calls in tests
  Library/Homebrew/cli/named_args.rb
  Library/Homebrew/test/cask/cask_loader/from_api_loader_spec.rb
  Library/Homebrew/test/cask/cask_loader_spec.rb
  Library/Homebrew/test/cask/cask_spec.rb
  Library/Homebrew/test/cask/info_spec.rb
  Library/Homebrew/test/formulary_spec.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/test/tap_spec.rb
Labels: discussion

#16759 livecheck: add --extract-plist
  Library/Homebrew/dev-cmd/livecheck.rb
  Library/Homebrew/livecheck/livecheck.rb
  completions/bash/brew
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/Manpage.md
  manpages/brew.1
Labels: cask

#16874 docs: move test-only resource into test block
  docs/Formula-Cookbook.md
Labels: documentation, discussion
