Repository Homebrew/brew, pull requests merged in 2024-09, with the labels that each got.

#18035 formula_auditor: reject more SPDX licenses
  Library/Homebrew/formula_auditor.rb
Labels: in progress

#18228 docs: remove references to deprecated/disabled GCC formulae
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/test/ENV_spec.rb
  Library/Homebrew/test/compiler_selector_spec.rb
  completions/fish/brew.fish
  completions/zsh/_brew
  docs/C++-Standard-Libraries.md
  docs/Custom-GCC-and-cross-compilers.md
  docs/Manpage.md
  docs/Tips-N'-Tricks.md
  docs/Versions.md
  manpages/brew.1
Labels: documentation

#17823 Set correct tap when loading installed casks
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cask/caskroom.rb
  Library/Homebrew/cli/named_args.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/test/cask/cask_loader_spec.rb
  Library/Homebrew/test/cli/named_args_spec.rb
  Library/Homebrew/test/exceptions_spec.rb
Labels: cask

#18127 compilers: drop support for GCC 4.9, 5 and 6
  Library/Homebrew/compilers.rb
  Library/Homebrew/shims/linux/super/gcc-4.2
  Library/Homebrew/shims/linux/super/gcc-4.9
  Library/Homebrew/shims/linux/super/gcc-5
  Library/Homebrew/shims/linux/super/gcc-6
  Library/Homebrew/shims/linux/super/llvm-gcc-4.2
  Library/Homebrew/shims/mac/super/gcc-4.2
  Library/Homebrew/shims/mac/super/gcc-4.9
  Library/Homebrew/shims/mac/super/gcc-5
  Library/Homebrew/shims/mac/super/gcc-6
  Library/Homebrew/shims/mac/super/i686-apple-darwin11-llvm-gcc-4.2
  Library/Homebrew/shims/mac/super/llvm-gcc-4.2
  Library/Homebrew/shims/super/gcc-4.9
  Library/Homebrew/shims/super/gcc-5
  Library/Homebrew/shims/super/gcc-6
  Library/Homebrew/shims/super/i686-apple-darwin11-llvm-gcc-4.2
  Library/Homebrew/shims/super/llvm-gcc-4.2
Labels: in progress

#18404 style: forbid `url do` blocks in `homebrew/cask`
  Library/Homebrew/rubocops/cask/mixin/cask_help.rb
  Library/Homebrew/rubocops/cask/url.rb
  Library/Homebrew/test/rubocops/cask/url_spec.rb
Labels: cask, install from api

#18417 Cask-Cookbook: update `verified` example
  docs/Cask-Cookbook.md
Labels: documentation
