Repository Homebrew/brew, pull requests merged in 2024-07, with the labels that each got.

#17599 Load tap migration renames from api
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/formulary.rb
  Library/Homebrew/test/cask/cask_loader/from_api_loader_spec.rb
  Library/Homebrew/test/formulary_spec.rb
Labels: bug

#17584 ci: improve Dockerfile to make proper use of build cache
  Dockerfile
Labels: needs response

#17628 dev-cmd/bump-formula-pr: `formula_version` should return `Version` not `String`
  Library/Homebrew/dev-cmd/bump-formula-pr.rb
Labels: bug

#17615 Use cached json API file for formulae and cask specified paths
  Library/Homebrew/api/cask.rb
  Library/Homebrew/api/formula.rb
  Library/Homebrew/cask/cask_loader.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/test/cask/cask_loader/from_api_loader_spec.rb
  Library/Homebrew/test/formula_spec.rb
Labels: install from api

#17681 cli/named_args: raise priority of core casks
  Library/Homebrew/cli/named_args.rb
  Library/Homebrew/test/cli/named_args_spec.rb
  Library/Homebrew/test/support/helper/formula.rb
Labels: cask

#17554 Add cask install receipts
  Library/Homebrew/cask.rb
  Library/Homebrew/cask/cask.rb
  Library/Homebrew/cask/info.rb
  Library/Homebrew/cask/installer.rb
  Library/Homebrew/cask/tab.rb
  Library/Homebrew/cmd/tab.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/sorbet/rbi/parlour.rbi
  Library/Homebrew/tab.rb
  Library/Homebrew/test/cask/cask_spec.rb
  Library/Homebrew/test/cask/info_spec.rb
  Library/Homebrew/test/cask/tab_spec.rb
  Library/Homebrew/test/cmd/deps_spec.rb
  Library/Homebrew/test/cmd/untap_spec.rb
  Library/Homebrew/test/cmd/uses_spec.rb
  Library/Homebrew/test/formula_spec.rb
  Library/Homebrew/test/installed_dependents_spec.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/many-artifacts.rb
  Library/Homebrew/test/support/fixtures/cask/Casks/with-depends-on-everything.rb
  Library/Homebrew/test/support/fixtures/cask_receipt.json
  Library/Homebrew/test/support/fixtures/receipt.json
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
  Library/Homebrew/test/tab_spec.rb
  Library/Homebrew/test/uninstall_spec.rb
  Library/Homebrew/utils/bottles.rb
Labels: cask

#17692 attestations: widen the beta
  Library/Homebrew/attestation.rb
  Library/Homebrew/formula_installer.rb
Labels: enhancement

#17704 attestation: don't dupe stderr
  Library/Homebrew/attestation.rb
  Library/Homebrew/test/attestation_spec.rb
Labels: enhancement

#17700 Don't allow special characters in sandbox rule paths
  Library/Homebrew/sandbox.rb
  Library/Homebrew/test/sandbox_spec.rb
Labels: sandbox

#17708 Deny file mode changes outside of specified paths in sandbox
  Library/Homebrew/sandbox.rb
  Library/Homebrew/test/sandbox_spec.rb
Labels: sandbox

#17724 pypi: allow universal wheels as resources
  Library/Homebrew/resource_auditor.rb
  Library/Homebrew/test/formula_auditor_spec.rb
  Library/Homebrew/utils/pypi.rb
Labels: python, enhancement

#17719 sandbox: deny signal to other processes
  Library/Homebrew/sandbox.rb
  Library/Homebrew/test/sandbox_spec.rb
Labels: sandbox

#17798 Update Brew-Livecheck.md: add examples for modify version information
  docs/Brew-Livecheck.md
Labels: documentation

#17778 Fix missing requires for `tap-info` command
  Library/Homebrew/api.rb
  Library/Homebrew/downloadable.rb
  Library/Homebrew/tap.rb
Labels: bug

#17809 Add missing_formula require to Homebrew::CLI::NamedArgs
  Library/Homebrew/cli/named_args.rb
Labels: bug

#17806 contributions, github: add missing requires, fix type errors
  Library/Homebrew/dev-cmd/contributions.rb
  Library/Homebrew/utils/github.rb
  Library/Homebrew/utils/github/api.rb
Labels: bug

#17793 Avoid frozen array errors in `brew upgrade`
  Library/Homebrew/attestation.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/reinstall.rb
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/test/attestation_spec.rb
Labels: bug

#17761 Add better "--quiet" support to cask upgrade
  Library/Homebrew/cask/upgrade.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/upgrade.rb
Labels: cask

#17881 Formula-Cookbook: add `std_npm_args`
  docs/Formula-Cookbook.md
Labels: documentation
