Repository Homebrew/brew, pull requests merged in 2024-01, with the labels that each got.

#16422 build: fix bad modify_build_environment call
  Library/Homebrew/build.rb
Labels: critical

#16443 cmd/audit: fix type error in cask livecheck url audit
  Library/Homebrew/cask/audit.rb
Labels: bug, critical

#16452 completions: ignore errors on cask list generation.
  Library/Homebrew/completions/bash.erb
  Library/Homebrew/completions/zsh.erb
Labels: critical

#16453 cmd/*env-sync: use *ENV_ROOT
  Library/Homebrew/cmd/nodenv-sync.rb
  Library/Homebrew/cmd/pyenv-sync.rb
  Library/Homebrew/cmd/rbenv-sync.rb
  bin/brew
Labels: critical

#16455 docs/Homebrew-Governance: import changes.
  docs/Homebrew-Governance.md
Labels: critical

#16465 brew: clarify which user needs to be able to read the working directory.
  Library/Homebrew/brew.sh
  bin/brew
Labels: critical

#16482 docs: remove OpenSSL keg_only information
  docs/Formula-Cookbook.md
Labels: documentation

#16477 extend/ENV/shared: effective_arch as public API
  Library/Homebrew/extend/ENV/shared.rb
  Library/Homebrew/extend/os/linux/extend/ENV/shared.rb
Labels: discussion

#16498 cmd/vendor-install: fix some elses.
  Library/Homebrew/cmd/vendor-install.sh
Labels: critical

#16531 docs: use `--eval-all` with `brew info`
  docs/Querying-Brew.md
Labels: documentation

#16535 docs: drop example that requires `--eval-all`
  docs/Querying-Brew.md
Labels: documentation
