Repository Homebrew/brew, pull requests merged in 2025-05, with the labels that each got.

#19958 docs/Deprecating-Disabling-* review
  docs/Deprecating-Disabling-and-Removing-Casks.md
  docs/Deprecating-Disabling-and-Removing-Formulae.md
Labels: documentation

#19968 docs/Cask-Cookbook review
  docs/Cask-Cookbook.md
Labels: documentation, cask

#19983 cask/audit: skip audit_rosetta on Intel-only casks & OSes
  Library/Homebrew/cask/audit.rb
  Library/Homebrew/requirements/macos_requirement.rb
  Library/Homebrew/test/requirements/macos_requirement_spec.rb
Labels: cask

#20000 docs: localize internal URLs
  .gitignore
  docs/.mdl_ruleset.rb
  docs/Acceptable-Casks.md
  docs/Brew-Bundle-and-Brewfile.md
  docs/Common-Issues.md
  docs/FAQ.md
  docs/Formula-Cookbook.md
  docs/Homebrew-and-Python.md
  docs/Homebrew-on-Linux.md
  docs/How-To-Open-a-Homebrew-Pull-Request.md
  docs/Installation.md
  docs/New-Maintainer-Checklist.md
  docs/Prose-Style-Guidelines.md
  docs/Tips-and-Tricks.md
  docs/vale-styles/Homebrew/README.md
Labels: documentation

#20007 feat: add clarification of macOS patches in Support-Tiers
  docs/Support-Tiers.md
Labels: needs response
