Repository Homebrew/brew, pull requests merged in 2025-03, with the labels that each got.

#19275 workflows/docker: build and publish ARM64 Docker images
  .github/workflows/docker.yml
Labels: in progress

#19385 services: migrate external tap to main repo
  .devcontainer/devcontainer.json
  .devcontainer/on-create-command.sh
  .github/workflows/tests.yml
  Library/Homebrew/cmd/services.rb
  Library/Homebrew/official_taps.rb
  Library/Homebrew/services/cli.rb
  Library/Homebrew/services/commands/cleanup.rb
  Library/Homebrew/services/commands/info.rb
  Library/Homebrew/services/commands/kill.rb
  Library/Homebrew/services/commands/list.rb
  Library/Homebrew/services/commands/restart.rb
  Library/Homebrew/services/commands/run.rb
  Library/Homebrew/services/commands/start.rb
  Library/Homebrew/services/commands/stop.rb
  Library/Homebrew/services/formula_wrapper.rb
  Library/Homebrew/services/formulae.rb
  Library/Homebrew/services/system.rb
  Library/Homebrew/services/system/systemctl.rb
  Library/Homebrew/sorbet/rbi/dsl/homebrew/cmd/services.rbi
  Library/Homebrew/test/cmd/services_spec.rb
  Library/Homebrew/test/services/cli_spec.rb
  Library/Homebrew/test/services/commands/cleanup_spec.rb
  Library/Homebrew/test/services/commands/info_spec.rb
  Library/Homebrew/test/services/commands/list_spec.rb
  Library/Homebrew/test/services/commands/restart_spec.rb
  Library/Homebrew/test/services/formulae_spec.rb
  Library/Homebrew/test/services/formulae_wrapper_spec.rb
  Library/Homebrew/test/services/system/systemctl_spec.rb
  Library/Homebrew/test/services/system_spec.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/test/tap_spec.rb
  docs/External-Commands.md
  docs/Formula-Cookbook.md
Labels: help wanted

#19667 docs/Support-Tiers: update unsupported config examples
  docs/Support-Tiers.md
Labels: documentation
